import test from 'node:test';
import assert from 'node:assert/strict';
import {SOURCES,DEFAULTS} from './model.mjs';
import {pearson,quantile,progress,failureEpisodes,analyze,analysisReport} from './analytics.mjs';
const base=Date.parse('2026-09-24T15:00:00Z');
function round(index){const at=new Date(base+index*30000).toISOString(),height=100+index*2;return {id:'r'+index,started_at:at,finished_at:at,observations:Object.fromEntries(Object.keys(SOURCES).map(source=>[source,{id:source+index,source,at,status:'valid',round_trip_ms:100+index*10,error:null,data:source==='chain'?{height,slot:200+index*2,block_id:'a'.repeat(64),finalized_height:height-index,behind_by_slots:index,transport:{peers:{devnet:20}}}:source==='indexer'?{lag_slots:index*2,indexed_to_height:height}:source==='validators'?{active:5,total:6}:source==='mempool'?{size:index*3}:{}}]))};}
function failed(round,sources){for(const source of sources){round.observations[source].status='failed';round.observations[source].data=null;round.observations[source].error='Synthetic test failure';}return round;}
test('Pearson uses paired values, refuses constants and needs eight pairs',()=>{assert.equal(pearson(Array.from({length:8},(_,i)=>[i,2*i+9])).r,1);assert.equal(pearson(Array.from({length:8},(_,i)=>[i,-3*i])).r,-1);assert.equal(pearson(Array.from({length:8},(_,i)=>[i,0])).r,null);assert.equal(pearson([[1,2],[2,null],[NaN,5]]).n,1);assert.equal(pearson(Array.from({length:7},(_,i)=>[i,i])).r,null);});
test('quantiles interpolate and preserve empty/missing distinction',()=>{assert.equal(quantile([0,10],.5),5);assert.equal(quantile([0,10],.95),9.5);assert.equal(quantile([null,undefined,NaN],.5),null);assert.equal(quantile([0,null,0],.5),0);});
test('head progress excludes failed, regressed and widely separated observations',()=>{assert.equal(progress([round(0),round(1)],30)[1].per_minute,4);assert.equal(progress([round(0),round(5)],30)[1].per_minute,null);const rows=[round(0),failed(round(1),['chain']),round(2)];assert.deepEqual(progress(rows,30).map(r=>r.per_minute),[null,null,null]);const regression=round(1);regression.observations.chain.data.height=99;assert.equal(progress([round(0),regression],30)[1].per_minute,null);const conflict=round(1);conflict.observations.chain.data.height=100;conflict.observations.chain.data.block_id='b'.repeat(64);assert.match(progress([round(0),conflict],30)[1].reason,/Contradictory/);});
test('zero observed progress stays zero and elapsed times determine rates',()=>{const a=round(0),b=round(1);b.observations.chain.data.height=100;assert.equal(progress([a,b],30)[1].per_minute,0);b.observations.chain.at=a.observations.chain.at;assert.equal(progress([a,b],30)[1].per_minute,null);});
test('shared failure episodes split at gaps and never imply continuous outages',()=>{const sources=['chain','validators','admission'],rows=[failed(round(0),sources),failed(round(1),sources),failed(round(6),sources),round(7),failed(round(8),sources)];const episodes=failureEpisodes(rows,30);assert.equal(episodes.length,3);assert.deepEqual(episodes.map(e=>e.end_reason),['sampling_gap','threshold_not_met','window_end']);assert.equal(episodes[0].rounds,2);assert.equal(episodes[0].indexer_valid_rounds,2);assert.equal(episodes[0].peak_failed_methods,3);});
test('two failed methods do not create a shared failure episode',()=>{assert.equal(failureEpisodes([failed(round(0),['chain','build'])],30).length,0);});
test('window analysis counts failed reads and pairwise missingness independently',()=>{const rows=Array.from({length:10},(_,i)=>round(i));failed(rows[3],['chain']);const result=analyze(rows,DEFAULTS);assert.equal(result.reads,60);assert.equal(result.valid_reads,59);assert.equal(result.signals.find(s=>s.key==='latency').missing,1);assert.equal(result.correlations[0][1].n,9);assert.ok(Math.abs(result.correlations[0][1].r-1)<1e-12);assert.equal(result.correlations[0][5].r,null);assert.equal(result.progress_pairs,7);assert.equal(result.median_progress,4);});
test('analysis export carries source evidence and explicit descriptive method limits',()=>{const rows=[round(0)];const report=analysisReport(rows,DEFAULTS);assert.equal(report.schema,'bloch-ops-analysis/1');assert.equal(report.evidence.schema,'bloch-ops-monitor/1');assert.match(report.interpretation,/not uptime/);report.evidence.rounds[0].id='changed';assert.equal(rows[0].id,'r0');assert.equal(analyze([],DEFAULTS).valid_fraction,null);});
