import test from 'node:test';
import assert from 'node:assert/strict';
import {indexerHealth} from './indexer-proxy.mjs';
const request=(url='https://ops-blochinc.xyz/api/indexer-health',method='GET')=>new Request(url,{method,headers:{cookie:'private=value',authorization:'Bearer private'}});
const health={ok:true,indexed_to_height:100,indexed_to_slot:120,finalized_height:90,lag_slots:0,transactions:8,chain_tip:'a'.repeat(64),live_head_available:true,source:'public indexer',verification:'source reported',lag_basis:'indexed vs live',private:'must be omitted'};
test('fixed read relay accepts only GET and no query parameters without contacting upstream',async()=>{const fetcher=()=>assert.fail('must not fetch');assert.equal((await indexerHealth(request(undefined,'POST'),{fetcher})).status,405);assert.equal((await indexerHealth(request('https://ops-blochinc.xyz/api/indexer-health?url=https://other.invalid'),{fetcher})).status,400);});
test('relay strips caller credentials and unknown fields, rejects redirects, disables caching',async()=>{const response=await indexerHealth(request(),{fetcher:async(url,options)=>{assert.equal(url,'https://blochl1.com/indexer/health');assert.deepEqual(options.headers,{accept:'application/json'});assert.equal(options.credentials,'omit');assert.equal(options.redirect,'manual');assert.equal(options.cache,'no-store');return Response.json(health);}});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const data=await response.json();assert.equal(data.indexed_to_height,100);assert.equal(data.private,undefined);assert.equal(data.relay.source,'https://blochl1.com/indexer/health');});
test('relay sanitizes HTTP, malformed and oversized upstream failures',async()=>{for(const make of [()=>new Response('',{status:302,headers:{location:'https://other.invalid/'}}),()=>new Response('upstream private body',{status:500}),()=>new Response('{'),()=>Response.json({...health,indexed_to_height:130}),()=>new Response('x',{headers:{'content-length':String(2*1024*1024)}})]){const response=await indexerHealth(request(),{fetcher:async()=>make()});assert.equal(response.status,502);assert.equal((await response.text()).includes('private'),false);}});
test('relay aborts slow upstream reads',async()=>{const response=await indexerHealth(request(),{timeout:5,fetcher:async(url,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted'))))});assert.equal(response.status,504);});
