import test from 'node:test';
import assert from 'node:assert/strict';
import {SOURCES,DEFAULTS,normalize,settings,validateBundle,freshness,evaluate,transitionAlerts,metrics,statistics,stake,csv} from './model.mjs';
import {readSource,readRound} from './source.mjs';
const hash=n=>n.toString(16).padStart(64,'0'),start=Date.parse('2026-09-24T12:00:00Z');
const corroboration={level:'corroborated',source_node:'test-observer',plane:{certified:true,agree_on_head:true,age_ms:0},witness:{available:true,age_ms:100}};
const raw={chain:{height:100,slot:200,block_id:hash(1),finalized_height:90,finalized:{epoch:2,root:hash(2)},epoch:3,behind_by_slots:1,validators:{active:4,total:5},total_active_stake_sat:'900719925474099312345',transport:{peers:{devnet:10,libp2p:null}},corroboration},validators:{active:4,total:5,total_active_stake_sat:'900719925474099312345',corroboration},admission:{active:true,epoch:3,activation_epoch:2,network_domain:hash(3),minimum_stake_sat:'100',maximum_stake_sat:'200',activation_delay_epochs:8,exit_delay_epochs:32,withdrawal_delay_epochs:2048,corroboration},mempool:{size:1,max:100,bytes:123,next_base_fee_millisat_per_gas:'10',corroboration},build:{package_version:'test-only',source_digest:hash(4),source_digest_alg:'sha3-256',corroboration},indexer:{ok:true,indexed_to_height:100,indexed_to_slot:200,finalized_height:90,lag_slots:0,transactions:4,chain_tip:hash(1),live_head_available:true}};
function round(n=0){const at=new Date(start+n*30000).toISOString();return {id:`round-${n}`,started_at:at,finished_at:at,observations:Object.fromEntries(Object.keys(SOURCES).map(source=>[source,{id:`${n}-${source}`,source,at,round_trip_ms:10,status:'valid',error:null,data:normalize(source,raw[source])}]))};}
test('normalizers retain exact stake and nullable finality, omitting unrelated fields',()=>{const c=normalize('chain',{...raw.chain,finalized_height:null,unknown_private_field:'not retained'});assert.equal(c.finalized_height,null);assert.equal(c.total_active_stake_sat,raw.chain.total_active_stake_sat);assert.equal(c.unknown_private_field,undefined);assert.equal(stake('900719925474099312345'),'9,007,199,254,740.99312345');});
test('invalid heights, registry counts and amounts fail validation',()=>{assert.throws(()=>normalize('chain',{...raw.chain,finalized_height:101}));assert.throws(()=>normalize('chain',{...raw.chain,slot:99}));assert.throws(()=>normalize('validators',{...raw.validators,active:6}));assert.throws(()=>normalize('admission',{...raw.admission,minimum_stake_sat:'201'}));assert.throws(()=>normalize('mempool',{...raw.mempool,next_base_fee_millisat_per_gas:10}));});
test('freshness is distinct from failed reads and responds to longer schedules',()=>{const o=round().observations.chain;assert.equal(freshness(o,start+90001),'stale');assert.equal(freshness(o,start+100000,{...DEFAULTS,interval:60}),'valid');assert.equal(freshness({...o,status:'failed'},start),'failed');assert.equal(freshness(o,start-1),'stale');});
test('missing finality does not become zero or a fabricated alert',()=>{const r=round();r.observations.chain.data.finalized_height=null;assert.equal(metrics(r).finality_gap,null);assert.equal(evaluate([r],DEFAULTS,start).find(r=>r.code==='finality_gap').state,'unknown');});
test('read failures preserve open conditions as unobserved instead of clearing them',()=>{const first=round();first.observations.chain.data.behind_by_slots=20;const a=transitionAlerts(new Map(),evaluate([first],DEFAULTS,start),first.finished_at);assert.equal(a.alerts.get('chain:sync_lag').state,'active');a.alerts.get('chain:sync_lag').acknowledged=true;const failed=round(1);failed.observations.chain={...failed.observations.chain,status:'failed',error:'Timed out',data:null};const b=transitionAlerts(a.alerts,evaluate([first,failed],DEFAULTS,start+30000),failed.finished_at);assert.equal(b.alerts.get('chain:sync_lag').state,'unknown');assert.equal(b.alerts.get('chain:sync_lag').acknowledged,true);assert.equal(b.alerts.get('chain:availability').state,'active');const restored=round(2);const c=transitionAlerts(b.alerts,evaluate([first,failed,restored],DEFAULTS,start+60000),restored.finished_at);assert.equal(c.alerts.get('chain:sync_lag').state,'resolved');assert.equal(c.alerts.get('chain:availability').state,'resolved');});
test('regressions and equal-height anchor conflicts are reported as observations',()=>{const a=round(),b=round(1);b.observations.chain.data.height=99;b.observations.chain.data.finalized_height=89;const codes=evaluate([a,b],DEFAULTS,start+30000).filter(r=>r.state==='active').map(r=>r.code);assert.ok(codes.includes('regression'));assert.ok(codes.includes('finality_regression'));const changed=round(1);changed.observations.chain.data.block_id=hash(99);assert.equal(evaluate([a,changed],DEFAULTS,start+30000).find(r=>r.code==='anchor_changed').state,'active');});
test('head stall requires three contiguous valid observations over the configured window',()=>{const config={...DEFAULTS,stall:60},rows=[round(),round(1),round(2)];assert.equal(evaluate(rows,config,start+60000).find(r=>r.code==='no_progress').state,'active');rows[1].observations.chain.status='failed';assert.equal(evaluate(rows,config,start+60000).find(r=>r.code==='no_progress').state,'clear');const gap=[round(),round(1),round(6)];assert.equal(evaluate(gap,config,start+180000).find(r=>r.code==='no_progress').state,'clear');});
test('supplied domain and build expectations are compared without changing source data',()=>{const r=round(),config=settings({...DEFAULTS,expectedDomain:hash(999),expectedDigest:hash(998)});assert.equal(evaluate([r],config,start).find(r=>r.code==='domain').state,'active');assert.equal(evaluate([r],config,start).find(r=>r.code==='digest').state,'active');assert.equal(r.observations.admission.data.network_domain,hash(3));assert.throws(()=>settings({interval:1}));assert.throws(()=>settings({expectedDigest:'not-a-key'}));});
test('session import bounds rounds, chronology, observation IDs and source membership',()=>{const bundle={schema:'bloch-ops-monitor/1',settings:DEFAULTS,rounds:[round(),round(1)]};assert.equal(validateBundle(bundle).rounds.length,2);let bad=structuredClone(bundle);bad.rounds.reverse();assert.throws(()=>validateBundle(bad),/ordering/);bad=structuredClone(bundle);bad.rounds[1].observations.chain.id=bad.rounds[0].observations.chain.id;assert.throws(()=>validateBundle(bad),/Duplicate/);bad=structuredClone(bundle);bad.rounds[0].observations.chain.at=new Date(start-1).toISOString();assert.throws(()=>validateBundle(bad),/outside/);bad=structuredClone(bundle);delete bad.rounds[0].observations.build;assert.throws(()=>validateBundle(bad));assert.throws(()=>validateBundle({...bundle,rounds:Array.from({length:181},()=>round())}));});
test('failed observations remain in success ratios while missing metrics stay blank',()=>{const a=round(),b=round(1);b.observations.chain.status='failed';b.observations.chain.data=null;const s=statistics([a,b]).chain;assert.equal(s.successRatio,.5);assert.equal(s.median,10);assert.equal(metrics(b).height,null);assert.match(csv([b]),/"failed"/);assert.ok(!csv([b]).includes('undefined'));});
test('source reader uses only fixed read endpoints and validates RPC envelopes',async()=>{let calls=0;const fetcher=async(url,init)=>{calls++;assert.equal(url,SOURCES.chain.url);assert.equal(init.credentials,'omit');const request=JSON.parse(init.body);assert.equal(request.method,'getchaininfo');assert.deepEqual(request.params,[]);return Response.json({jsonrpc:'2.0',id:request.id,result:raw.chain});};const o=await readSource('chain',{fetcher});assert.equal(o.status,'valid');assert.equal(calls,1);const bad=await readSource('chain',{fetcher:async()=>Response.json({jsonrpc:'2.0',id:'wrong',result:raw.chain})});assert.equal(bad.status,'failed');assert.equal(bad.data,null);await assert.rejects(()=>readSource('sendrawtransaction',{fetcher}));});
test('HTTP failures are bounded public errors and do not expose response bodies',async()=>{const o=await readSource('chain',{fetcher:async()=>new Response('private diagnostic',{status:503})});assert.equal(o.status,'failed');assert.match(o.error,/503/);assert.ok(!o.error.includes('private'));});
test('a round makes six requests with at most three in flight and retains partial failure',async()=>{let active=0,max=0,calls=0;const fetcher=async(url,init)=>{calls++;active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,2));active--;if(url===SOURCES.indexer.relay)return Response.json(raw.indexer);const request=JSON.parse(init.body),source=Object.keys(SOURCES).find(s=>SOURCES[s].method===request.method);return source==='build'?new Response('',{status:503}):Response.json({jsonrpc:'2.0',id:request.id,result:raw[source]});};const r=await readRound({fetcher});assert.equal(calls,6);assert.equal(max,3);assert.equal(r.observations.build.status,'failed');assert.equal(r.observations.chain.status,'valid');assert.equal(r.observations.indexer.status,'valid');});

test('median averages the middle pair and p95 uses the nearest rank',()=>{const rounds=[round(),round(1)];rounds[0].observations.chain.round_trip_ms=10;rounds[1].observations.chain.round_trip_ms=40;const s=statistics(rounds).chain;assert.equal(s.median,25);assert.equal(s.p95,40);});
