// SPDX-License-Identifier: AGPL-3.0-or-later

//! Keystore + the injected crypto boundary (M2 `keys/`).
//!
//! ## Key hygiene — read before touching (BLOCH-GENESIS-KEYS.md rule zero)
//!
//! **No production key is ever generated by this module in an observable
//! context.** `keygen` here exists for *throwaway devnet* validators only:
//! ephemeral hybrid keypairs written straight to a `0600` file, never printed,
//! never logged — the code below never formats secret bytes into any string.
//! Genesis-4 mainnet keys come from a human running the pinned keygen tool on
//! an air-gapped machine; this node only ever loads them from its keystore
//! file and hands out signatures.
//!
//! ## What implements what
//!
//! - [`HybridVerifier`] implements the pure crate's `SignatureVerifier`
//!   boundary over `bloch_crypto::crypto::verify` — the real
//!   ML-DSA-65 ‖ Falcon-1024 suite, both halves ANDed inside bloch-crypto.
//!   It holds NO key table: callers resolve the key from the committed
//!   validator registry and pass it in. See the type's own docs for why.
//! - [`Keystore`] holds this validator's secret key + RANDAO chain seed and
//!   signs consensus signing roots (block proposals, attestations).
//!
//! Falcon signs through the constant-time `clean` path only: that is pinned
//! inside bloch-crypto (default-features = false on pqcrypto-falcon plus its
//! tripwire test), not re-decided here.

use std::fs;
use std::io::{self};
use std::path::Path;

const KEYSTORE_MAGIC: &[u8; 8] = b"BPOSKEY1";

/// A loaded validator keystore. Secret material lives only in this struct;
/// nothing here implements `Debug`/`Display` for the secret fields.
pub struct Keystore {
    /// Validator index this key was registered under at genesis.
    pub index: u32,
    /// Suite-enveloped hybrid public key.
    pub pubkey: Vec<u8>,
    /// Suite-enveloped hybrid secret key. Never leaves this process.
    secret: Vec<u8>,
    /// 32-byte seed of the SHAKE-256 RANDAO chain (regenerated
    /// deterministically from this seed on every boot).
    pub randao_seed: [u8; 32],
}

impl Keystore {
    /// Generate a throwaway devnet keystore at `dir/validator.key`.
    ///
    /// DEVNET ONLY. The RANDAO seed comes from the OS entropy pool; the
    /// hybrid keypair from bloch-crypto's keygen. File mode 0600.
    pub fn generate(dir: &Path, index: u32) -> io::Result<Keystore> {
        let (pubkey, secret) = bloch_crypto::crypto::generate_keypair();
        let mut randao_seed = [0u8; 32];
        os_random(&mut randao_seed)?;
        let ks = Keystore { index, pubkey, secret, randao_seed };
        ks.save(dir)?;
        Ok(ks)
    }

    fn save(&self, dir: &Path) -> io::Result<()> {
        fs::create_dir_all(dir)?;
        let mut out = Vec::new();
        out.extend_from_slice(KEYSTORE_MAGIC);
        out.extend_from_slice(&self.index.to_le_bytes());
        crate::codec::put_bytes(&mut out, &self.pubkey);
        crate::codec::put_bytes(&mut out, &self.secret);
        out.extend_from_slice(&self.randao_seed);
        let path = dir.join("validator.key");
        fs::write(&path, &out)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&path, fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    }

    pub fn load(dir: &Path) -> io::Result<Keystore> {
        let bytes = fs::read(dir.join("validator.key"))?;
        let mut r = crate::codec::Reader::new(&bytes);
        let bad = |m: &'static str| io::Error::new(io::ErrorKind::InvalidData, m);
        let magic = r.take(8).map_err(|_| bad("truncated keystore"))?;
        if magic != KEYSTORE_MAGIC {
            return Err(bad("not a bloch-pos keystore"));
        }
        let index = r.u32().map_err(|_| bad("truncated keystore"))?;
        let pubkey = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let secret = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let randao_seed = r.h32().map_err(|_| bad("truncated keystore"))?;
        r.finish().map_err(|_| bad("trailing bytes in keystore"))?;
        Ok(Keystore { index, pubkey, secret, randao_seed })
    }

    /// Sign a 32-byte consensus signing root with both halves of the hybrid
    /// suite. The domain tag is already inside the root (DS_PROPOSE /
    /// DS_ATTEST), per the pure crate's derivations.
    pub fn sign(&self, signing_root: &[u8; 32]) -> Vec<u8> {
        bloch_crypto::crypto::sign(&self.secret, signing_root)
            .expect("hybrid signing over a well-formed keystore key cannot fail")
    }
}

/// The real `SignatureVerifier`: bloch-crypto verify over a key the CALLER
/// resolved (both halves of the hybrid suite must pass).
///
/// ## This type used to hold a key table, and that table was the defect
///
/// It carried `pubkeys: Arc<Vec<Vec<u8>>>`, built once at boot from the
/// genesis manifest and never rebuilt — not after sync, not after replay — and
/// served `verify(index, ..)` out of it with `pubkeys.get(index)`. A validator
/// added by an on-chain deposit registered, activated, entered the roster and
/// got drawn for committees, and then every signature it made was rejected as
/// `BadSignature`, because its index was past the end of a vector frozen at
/// genesis. It could not attest, could not propose, and could not even be
/// slashed. Its committee seats were dead weight subtracted from finality.
///
/// The table is now **gone**, not merely unused: this struct holds no state at
/// all. The keys live where they were always committed — in the validator
/// registry inside consensus state, whose `ValidatorRecord::pubkey` doc has
/// said all along that "the registry *is* the authoritative key store". Every
/// consensus call site now resolves the key from a registry it names and
/// passes it to `verify_with_key`; see `attestation::KeyLookup` for which
/// state answers where.
///
/// Deleting the field rather than leaving it unread is deliberate. An unused
/// table is a table someone re-wires later.
#[derive(Clone)]
pub struct HybridVerifier;

impl HybridVerifier {
    pub fn new() -> Self {
        HybridVerifier
    }
}

impl Default for HybridVerifier {
    fn default() -> Self {
        Self::new()
    }
}

impl bloch_pos_committee::attestation::SignatureVerifier for HybridVerifier {
    /// The suite check itself. Robust to arbitrary key bytes by contract:
    /// `bloch_crypto::crypto::verify` documents "any body parse failure ⇒
    /// false, never a panic (consensus rule)" and guards every length before
    /// slicing. That matters more now than it did, because the bytes handed in
    /// here can come from the registry, and the live `Deposit` handler does
    /// **not** validate the suite or check a proof of possession before
    /// inserting a pubkey (`staking::validate_deposit`, which does both, has
    /// no production caller). So a registry key may be arbitrary bytes, and
    /// this must fail closed on them rather than panic. It does.
    fn verify_with_key(&self, pubkey: &[u8], signing_root: &[u8; 32], signature: &[u8]) -> bool {
        bloch_crypto::crypto::verify(pubkey, signing_root, signature)
    }
}

/// Accept-everything verifier for the producer's own `compute_post_state`
/// probe: the state a block commits does not depend on the verifier, and the
/// producer needs the post-state root *before* it can sign the header the
/// real verifier would check. Every block still passes through the real
/// [`HybridVerifier`] in `apply_block` before it is accepted or broadcast.
pub struct ProbeVerifier;

impl bloch_pos_committee::attestation::SignatureVerifier for ProbeVerifier {
    fn verify_with_key(&self, _pk: &[u8], _root: &[u8; 32], _sig: &[u8]) -> bool {
        true
    }
}

/// Fill `buf` from the OS entropy pool (`/dev/urandom`). Devnet-grade.
fn os_random(buf: &mut [u8]) -> io::Result<()> {
    use std::io::Read;
    let mut f = fs::File::open("/dev/urandom")?;
    f.read_exact(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use bloch_pos_committee::attestation::SignatureVerifier;

    /// The real suite, end to end, through the only entry point the trait now
    /// has. Disposable keypair generated in-process — no production or
    /// treasury key material is involved anywhere in this file.
    #[test]
    fn real_hybrid_signature_verifies_through_the_key_form() {
        let (pk, sk) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        assert!(HybridVerifier::new().verify_with_key(&pk, &root, &sig));
    }

    #[test]
    fn a_tampered_signature_fails() {
        let (pk, sk) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let mut sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        let last = sig.len() - 1;
        sig[last] ^= 0x01;
        assert!(!HybridVerifier::new().verify_with_key(&pk, &root, &sig));
    }

    #[test]
    fn a_signature_under_another_key_fails() {
        let (_pk_a, sk_a) = bloch_crypto::crypto::generate_keypair();
        let (pk_b, _sk_b) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let sig = bloch_crypto::crypto::sign(&sk_a, &root).expect("sign");
        assert!(
            !HybridVerifier::new().verify_with_key(&pk_b, &root, &sig),
            "A's signature must not verify under B's key"
        );
    }

    /// The registry can hold arbitrary bytes as a pubkey, because the live
    /// `Deposit` handler checks neither the suite nor a proof of possession
    /// before inserting one (`staking::validate_deposit`, which does both, has
    /// no production caller). Now that those bytes reach the verifier, it must
    /// fail closed on every shape rather than panic — a panic in a consensus
    /// check is a remote halt.
    #[test]
    fn malformed_registry_keys_fail_closed_and_never_panic() {
        let v = HybridVerifier::new();
        let root = [0x11u8; 32];
        let (_pk, sk) = bloch_crypto::crypto::generate_keypair();
        let good_sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        for bad in [
            Vec::new(),
            vec![0u8; 1],
            vec![0u8; 3],
            vec![0xFFu8; 32],
            vec![0u8; 1951],       // ML-DSA half only, nothing after it
            vec![0xB1, 0x0C, 0, 0], // envelope magic, empty body
            vec![7u8; 100_000],
        ] {
            assert!(!v.verify_with_key(&bad, &root, &good_sig));
            assert!(!v.verify_with_key(&bad, &root, &[]));
        }
    }
}
