// SPDX-License-Identifier: AGPL-3.0-or-later

//! Keystore + the injected crypto boundary (M2 `keys/`).
//!
//! ## Key hygiene — read before touching (BLOCH-GENESIS-KEYS.md rule zero)
//!
//! **No production key is ever generated by this module in an observable
//! context.** `keygen` here exists for *throwaway devnet* validators only:
//! ephemeral hybrid keypairs written straight to a `0600` file, never printed,
//! never logged — the code below never formats secret bytes into any string.
//! Genesis-4 mainnet keys come from a human running the pinned keygen tool on
//! an air-gapped machine; this node only ever loads them from its keystore
//! file and hands out signatures.
//!
//! ## What implements what
//!
//! - [`HybridVerifier`] implements the pure crate's `SignatureVerifier`
//!   boundary over `bloch_crypto::crypto::verify` — the real
//!   ML-DSA-65 ‖ Falcon-1024 suite, both halves ANDed inside bloch-crypto.
//!   It maps validator index → registered public key from the genesis set.
//! - [`Keystore`] holds this validator's secret key + RANDAO chain seed and
//!   signs consensus signing roots (block proposals, attestations).
//!
//! Falcon signs through the constant-time `clean` path only: that is pinned
//! inside bloch-crypto (default-features = false on pqcrypto-falcon plus its
//! tripwire test), not re-decided here.

use std::fs;
use std::io::{self};
use std::path::Path;

const KEYSTORE_MAGIC: &[u8; 8] = b"BPOSKEY1";

/// A loaded validator keystore. Secret material lives only in this struct;
/// nothing here implements `Debug`/`Display` for the secret fields.
pub struct Keystore {
    /// Validator index this key was registered under at genesis.
    pub index: u32,
    /// Suite-enveloped hybrid public key.
    pub pubkey: Vec<u8>,
    /// Suite-enveloped hybrid secret key. Never leaves this process.
    secret: Vec<u8>,
    /// 32-byte seed of the SHAKE-256 RANDAO chain (regenerated
    /// deterministically from this seed on every boot).
    pub randao_seed: [u8; 32],
}

impl Keystore {
    /// Generate a throwaway devnet keystore at `dir/validator.key`.
    ///
    /// DEVNET ONLY. The RANDAO seed comes from the OS entropy pool; the
    /// hybrid keypair from bloch-crypto's keygen. File mode 0600.
    pub fn generate(dir: &Path, index: u32) -> io::Result<Keystore> {
        let (pubkey, secret) = bloch_crypto::crypto::generate_keypair();
        let mut randao_seed = [0u8; 32];
        os_random(&mut randao_seed)?;
        let ks = Keystore {
            index,
            pubkey,
            secret,
            randao_seed,
        };
        ks.save(dir)?;
        Ok(ks)
    }

    fn save(&self, dir: &Path) -> io::Result<()> {
        fs::create_dir_all(dir)?;
        let mut out = Vec::new();
        out.extend_from_slice(KEYSTORE_MAGIC);
        out.extend_from_slice(&self.index.to_le_bytes());
        crate::codec::put_bytes(&mut out, &self.pubkey);
        crate::codec::put_bytes(&mut out, &self.secret);
        out.extend_from_slice(&self.randao_seed);
        let path = dir.join("validator.key");
        fs::write(&path, &out)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&path, fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    }

    pub fn load(dir: &Path) -> io::Result<Keystore> {
        let bytes = fs::read(dir.join("validator.key"))?;
        let mut r = crate::codec::Reader::new(&bytes);
        let bad = |m: &'static str| io::Error::new(io::ErrorKind::InvalidData, m);
        let magic = r.take(8).map_err(|_| bad("truncated keystore"))?;
        if magic != KEYSTORE_MAGIC {
            return Err(bad("not a bloch-pos keystore"));
        }
        let index = r.u32().map_err(|_| bad("truncated keystore"))?;
        let pubkey = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let secret = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let randao_seed = r.h32().map_err(|_| bad("truncated keystore"))?;
        r.finish().map_err(|_| bad("trailing bytes in keystore"))?;
        Ok(Keystore {
            index,
            pubkey,
            secret,
            randao_seed,
        })
    }

    /// Sign a 32-byte consensus signing root with both halves of the hybrid
    /// suite. The domain tag is already inside the root (DS_PROPOSE /
    /// DS_ATTEST), per the pure crate's derivations.
    pub fn sign(&self, signing_root: &[u8; 32]) -> Vec<u8> {
        bloch_crypto::crypto::sign(&self.secret, signing_root)
            .expect("hybrid signing over a well-formed keystore key cannot fail")
    }
}

/// The real `SignatureVerifier`: validator index → genesis-registered hybrid
/// public key → bloch-crypto verify (both halves must pass).
///
/// Registry is the *genesis* validator set. Honest limitation, stated: a
/// validator added later by an on-chain deposit would not be verifiable by
/// this map — the devnet has no deposit path wired, so the set is static.
#[derive(Clone)]
pub struct HybridVerifier {
    pubkeys: std::sync::Arc<Vec<Vec<u8>>>,
}

impl HybridVerifier {
    pub fn new(pubkeys: Vec<Vec<u8>>) -> Self {
        HybridVerifier {
            pubkeys: std::sync::Arc::new(pubkeys),
        }
    }
}

impl bloch_pos_committee::attestation::SignatureVerifier for HybridVerifier {
    fn verify(&self, validator: u32, signing_root: &[u8; 32], signature: &[u8]) -> bool {
        match self.pubkeys.get(validator as usize) {
            Some(pk) => bloch_crypto::crypto::verify(pk, signing_root, signature),
            None => false,
        }
    }

    /// Same suite, key supplied directly instead of looked up. Spending an
    /// output must be exactly as hard to forge as attesting, so this is the
    /// same call with the same both-halves check.
    fn verify_with_key(&self, pubkey: &[u8], signing_root: &[u8; 32], signature: &[u8]) -> bool {
        bloch_crypto::crypto::verify(pubkey, signing_root, signature)
    }
}

/// Accept-everything verifier for the producer's own `compute_post_state`
/// probe: the state a block commits does not depend on the verifier, and the
/// producer needs the post-state root *before* it can sign the header the
/// real verifier would check. Every block still passes through the real
/// [`HybridVerifier`] in `apply_block` before it is accepted or broadcast.
pub struct ProbeVerifier;

impl bloch_pos_committee::attestation::SignatureVerifier for ProbeVerifier {
    fn verify(&self, _v: u32, _root: &[u8; 32], _sig: &[u8]) -> bool {
        true
    }
    fn verify_with_key(&self, _pk: &[u8], _root: &[u8; 32], _sig: &[u8]) -> bool {
        true
    }
}

/// Fill `buf` from the OS entropy pool (`/dev/urandom`). Devnet-grade.
fn os_random(buf: &mut [u8]) -> io::Result<()> {
    use std::io::Read;
    let mut f = fs::File::open("/dev/urandom")?;
    f.read_exact(buf)
}
