// SPDX-License-Identifier: AGPL-3.0-or-later

//! Keystore + the injected crypto boundary (M2 `keys/`).
//!
//! ## Key hygiene — read before touching (BLOCH-GENESIS-KEYS.md rule zero)
//!
//! **No production key is ever generated by this module in an observable
//! context.** `generate` here exists for *throwaway devnet* validators only:
//! ephemeral hybrid keypairs written straight to a `0600` file, never printed,
//! never logged — the code below never formats secret bytes into any string.
//! Genesis-4 mainnet keys come from a human running the pinned keygen tool on
//! an air-gapped machine; this node only ever loads them from its keystore
//! file and hands out signatures.
//!
//! ## Encryption at rest (audit I-H1)
//!
//! The keystore used to be **plaintext on disk** — `magic ‖ index ‖ pubkey ‖
//! secret ‖ randao_seed`, with nothing but `chmod 0600` between the hybrid
//! secret key and anyone who could read the file. Mode bits are not a
//! confidentiality boundary: they do not survive a backup, a snapshot, a
//! volume image, a `tar` run as root, a stolen disk, or the operator who
//! copies `validator.key` around to move a validator between hosts. And the
//! bytes behind them are the whole validator: the ML-DSA-65 ‖ Falcon-1024
//! secret key *and* the RANDAO chain seed, which together let the holder
//! propose, attest, and produce a second signature on the same slot — the
//! exact shape a slashing rule punishes the *victim* for.
//!
//! So the on-disk file is now sealed:
//!
//! - **KDF**: Argon2id (RFC 9106), 64 MiB / t=3 / p=1 by default, over a
//!   32-byte random salt from the OS entropy pool. The parameters are written
//!   into the file, so a keystore sealed under one cost still opens after the
//!   default is raised.
//! - **AEAD**: XChaCha20-Poly1305 with a 24-byte random nonce, over
//!   `secret ‖ randao_seed`. The public header (magic, KDF parameters, salt,
//!   nonce, validator index, public key) is the AAD, so an attacker cannot
//!   re-point a sealed secret at another validator index or another public
//!   key without the tag failing.
//! - **In memory**: the secret is a [`Zeroizing<Vec<u8>>`], the derived key
//!   and the passphrase are `Zeroizing`, and [`Keystore`] wipes its RANDAO
//!   seed in `Drop`.
//!
//! ## Plaintext is opt-in, in both directions
//!
//! [`Keystore::load`] **refuses** a legacy plaintext (`BPOSKEY1`) file, and
//! [`Keystore::save_with`] refuses to write one, unless the operator has said
//! so out loud — `--allow-plaintext-keystore` on the command line, or
//! `BLOCH_KEYSTORE_ALLOW_PLAINTEXT=1` in the environment. Nothing infers the
//! opt-in from the file it found: reading a plaintext keystore is a decision,
//! not a fallback, because a silent fallback is how a fleet stays plaintext
//! forever after one host is migrated.
//!
//! The passphrase itself never comes from a prompt — a systemd unit has no
//! tty. It comes from `BLOCH_KEYSTORE_PASSPHRASE_FILE` (preferred: a `0600`
//! file, or a systemd credential path) or `BLOCH_KEYSTORE_PASSPHRASE`.
//!
//! **This module does not migrate anything on its own.** Re-sealing a live
//! validator's key is an operator action on an operator's schedule; a loader
//! that rewrote the file it just read would be writing to a directory that
//! may be shared, replicated, or mid-backup.
//!
//! ## What implements what
//!
//! - [`HybridVerifier`] implements the pure crate's `SignatureVerifier`
//!   boundary over `bloch_crypto::crypto::verify` — the real
//!   ML-DSA-65 ‖ Falcon-1024 suite, both halves ANDed inside bloch-crypto.
//!   It holds NO key table: callers resolve the key from the committed
//!   validator registry and pass it in. See the type's own docs for why.
//! - [`Keystore`] holds this validator's secret key + RANDAO chain seed and
//!   signs consensus signing roots (block proposals, attestations).
//!
//! Falcon signs through the constant-time `clean` path only: that is pinned
//! inside bloch-crypto (default-features = false on pqcrypto-falcon plus its
//! tripwire test), not re-decided here.

use std::fs;
use std::io::{self};
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};

use chacha20poly1305::aead::{Aead, Payload};
use chacha20poly1305::{KeyInit, XChaCha20Poly1305, XNonce};
use zeroize::{Zeroize, Zeroizing};

/// Legacy PLAINTEXT keystore. Still readable, but only behind the explicit
/// opt-in — see the module docs.
const KEYSTORE_MAGIC_V1: &[u8; 8] = b"BPOSKEY1";
/// Sealed keystore: Argon2id + XChaCha20-Poly1305 (audit I-H1).
const KEYSTORE_MAGIC_V2: &[u8; 8] = b"BPOSKEY2";

/// The only KDF this format knows. A byte rather than an implied constant so
/// a future KDF is a *refusal* on old binaries instead of a misparse.
const KDF_ARGON2ID: u8 = 1;

/// Upper bound on the Argon2 memory cost this node will honour when opening a
/// file. The parameters live in the keystore, and a keystore is a file an
/// attacker may hand us; without a cap, `m_cost = u32::MAX` is a 4 TiB
/// allocation request from a header field.
const KDF_MAX_M_COST_KIB: u32 = 1_048_576; // 1 GiB

/// Argon2id cost parameters, written into every sealed keystore.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KdfParams {
    /// Memory cost, in KiB.
    pub m_cost: u32,
    /// Time cost (passes).
    pub t_cost: u32,
    /// Parallelism (lanes).
    pub p_cost: u32,
}

impl KdfParams {
    /// What a real keystore is sealed under. Above the OWASP Argon2id floor
    /// (19 MiB / t=2 / p=1), because this file guards a validator's whole
    /// identity and is unsealed once per boot, not once per request.
    pub const PRODUCTION: KdfParams = KdfParams {
        m_cost: 65_536,
        t_cost: 3,
        p_cost: 1,
    };

    fn to_argon2(self) -> io::Result<argon2::Argon2<'static>> {
        if self.m_cost > KDF_MAX_M_COST_KIB {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "keystore KDF memory cost is over this node's cap",
            ));
        }
        let params = argon2::Params::new(self.m_cost, self.t_cost, self.p_cost, Some(32))
            .map_err(|_| {
                io::Error::new(io::ErrorKind::InvalidData, "keystore KDF parameters are invalid")
            })?;
        Ok(argon2::Argon2::new(
            argon2::Algorithm::Argon2id,
            argon2::Version::V0x13,
            params,
        ))
    }

    /// Argon2id(passphrase, salt) → 32-byte AEAD key, zeroized on drop.
    fn derive(self, passphrase: &str, salt: &[u8; 32]) -> io::Result<Zeroizing<[u8; 32]>> {
        let mut key = Zeroizing::new([0u8; 32]);
        self.to_argon2()?
            .hash_password_into(passphrase.as_bytes(), salt, key.as_mut())
            .map_err(|_| {
                io::Error::new(io::ErrorKind::InvalidData, "keystore key derivation failed")
            })?;
        Ok(key)
    }
}

/// How this process is allowed to open and write a keystore.
///
/// There is deliberately no `Default`. Every call site either carries a
/// passphrase or has said, in one of two places an operator can see, that it
/// accepts plaintext at rest.
pub enum Unlock {
    /// Seal/unseal with this passphrase.
    Passphrase {
        pass: Zeroizing<String>,
        /// Cost used when *writing*. Reading always uses the parameters
        /// recorded in the file.
        kdf: KdfParams,
    },
    /// Explicit, operator-visible opt-in to PLAINTEXT at rest: read a legacy
    /// `BPOSKEY1` file, or write one. Devnet and tests.
    PlaintextOptIn,
}

impl Unlock {
    /// A passphrase at the production Argon2id cost.
    pub fn passphrase(pass: impl Into<String>) -> Unlock {
        Unlock::Passphrase {
            pass: Zeroizing::new(pass.into()),
            kdf: KdfParams::PRODUCTION,
        }
    }

    /// A passphrase at an explicit cost. Used by tests to keep Argon2id off
    /// the critical path of an unoptimized test binary; it changes nothing
    /// about the format, since the cost travels in the file.
    pub fn passphrase_with(pass: impl Into<String>, kdf: KdfParams) -> Unlock {
        Unlock::Passphrase {
            pass: Zeroizing::new(pass.into()),
            kdf,
        }
    }

    /// Resolve the policy from the process environment, in priority order:
    ///
    /// 1. `BLOCH_KEYSTORE_PASSPHRASE_FILE` — path to a file whose contents
    ///    (one trailing newline stripped) are the passphrase. Preferred: it
    ///    keeps the secret out of `/proc/<pid>/environ` and out of the unit
    ///    file, and is what `LoadCredential=` hands you.
    /// 2. `BLOCH_KEYSTORE_PASSPHRASE` — the passphrase itself.
    /// 3. The plaintext opt-in, from `--allow-plaintext-keystore` (see
    ///    [`allow_plaintext_at_rest`]) or `BLOCH_KEYSTORE_ALLOW_PLAINTEXT=1`.
    ///
    /// With none of those set this is an **error**, not a default. A node
    /// that quietly read a plaintext key because nobody configured anything
    /// is the defect this function exists to close.
    pub fn from_env() -> io::Result<Unlock> {
        Self::from_sources(
            std::env::var_os("BLOCH_KEYSTORE_PASSPHRASE_FILE"),
            std::env::var("BLOCH_KEYSTORE_PASSPHRASE").ok(),
            plaintext_opt_in(),
        )
    }

    /// The whole of [`Unlock::from_env`]'s decision, with the three inputs
    /// passed in instead of read from the process. Split out so the rule
    /// below can be tested without mutating a global environment that every
    /// other test in the binary shares.
    ///
    /// ## Not one of these errors is `NotFound` — deliberately
    ///
    /// `NotFound` is a *load-bearing* error kind here: the engine reads
    /// "there is no `validator.key`" as "run as an observer". A refusal from
    /// this function is about the operator's configuration, never about the
    /// keystore, so it must not be able to impersonate a missing keystore.
    /// The passphrase file is where that used to leak: a bare `fs::read(path)?`
    /// on a `LoadCredential=` path that did not exist returned `NotFound`, the
    /// engine took it for "no keystore", and a fully provisioned validator
    /// came back from a restart as a silent observer — attesting nothing,
    /// logging nothing wrong. See `load_optional`.
    pub fn from_sources(
        pass_file: Option<std::ffi::OsString>,
        pass: Option<String>,
        plaintext_opt_in: bool,
    ) -> io::Result<Unlock> {
        if let Some(path) = pass_file {
            let shown = std::path::Path::new(&path).display().to_string();
            let raw = Zeroizing::new(fs::read(&path).map_err(|e| {
                // Re-kinded, not just re-worded: see the doc comment. A
                // missing or unreadable passphrase file is a configuration
                // refusal, and PermissionDenied is what the engine treats as
                // fatal.
                io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "BLOCH_KEYSTORE_PASSPHRASE_FILE={shown} cannot be read ({e}). \
                         This node has a keystore it cannot open; it will NOT \
                         fall back to observer mode"
                    ),
                )
            })?);
            let mut s = String::from_utf8(raw.to_vec()).map_err(|_| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    "BLOCH_KEYSTORE_PASSPHRASE_FILE is not valid UTF-8",
                )
            })?;
            while s.ends_with('\n') || s.ends_with('\r') {
                s.pop();
            }
            if s.is_empty() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "BLOCH_KEYSTORE_PASSPHRASE_FILE is empty",
                ));
            }
            return Ok(Unlock::passphrase(s));
        }
        if let Some(p) = pass {
            if !p.is_empty() {
                return Ok(Unlock::passphrase(p));
            }
        }
        if plaintext_opt_in {
            return Ok(Unlock::PlaintextOptIn);
        }
        Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "no keystore passphrase configured: set BLOCH_KEYSTORE_PASSPHRASE_FILE (preferred) \
             or BLOCH_KEYSTORE_PASSPHRASE. To keep the key in PLAINTEXT on disk anyway — devnet \
             only — pass --allow-plaintext-keystore or set BLOCH_KEYSTORE_ALLOW_PLAINTEXT=1",
        ))
    }
}

/// Set by `main` when `--allow-plaintext-keystore` is on the command line.
static PLAINTEXT_OPT_IN: AtomicBool = AtomicBool::new(false);

/// Record the operator's `--allow-plaintext-keystore`. Call once, from `main`,
/// before anything touches a keystore.
pub fn allow_plaintext_at_rest() {
    PLAINTEXT_OPT_IN.store(true, Ordering::SeqCst);
}

fn plaintext_opt_in() -> bool {
    PLAINTEXT_OPT_IN.load(Ordering::SeqCst)
        || matches!(
            std::env::var("BLOCH_KEYSTORE_ALLOW_PLAINTEXT").as_deref(),
            Ok("1") | Ok("true") | Ok("yes")
        )
}

/// A loaded validator keystore. Secret material lives only in this struct;
/// nothing here implements `Debug`/`Display` for the secret fields.
pub struct Keystore {
    /// Validator index this key was registered under at genesis.
    pub index: u32,
    /// Suite-enveloped hybrid public key.
    pub pubkey: Vec<u8>,
    /// Suite-enveloped hybrid secret key. Never leaves this process, and is
    /// wiped when this struct drops.
    secret: Zeroizing<Vec<u8>>,
    /// 32-byte seed of the SHAKE-256 RANDAO chain (regenerated
    /// deterministically from this seed on every boot). Wiped in `Drop` — on
    /// its own it is enough to predict this validator's RANDAO reveals.
    pub randao_seed: [u8; 32],
}

/// The RANDAO seed is a plain `[u8; 32]` because half the crate reads it as
/// one; `Zeroizing` cannot be bolted onto a `pub` field without changing every
/// reader. So the wipe happens here instead. `secret` wipes itself.
impl Drop for Keystore {
    fn drop(&mut self) {
        self.randao_seed.zeroize();
    }
}

impl Keystore {
    /// Generate a throwaway devnet keystore at `dir/validator.key`, sealed
    /// according to the environment ([`Unlock::from_env`]).
    ///
    /// DEVNET ONLY. The RANDAO seed comes from the OS entropy pool; the
    /// hybrid keypair from bloch-crypto's keygen. File mode 0600.
    pub fn generate(dir: &Path, index: u32) -> io::Result<Keystore> {
        Self::generate_with(dir, index, &Unlock::from_env()?)
    }

    /// [`Keystore::generate`] with the policy passed in rather than read from
    /// the environment.
    pub fn generate_with(dir: &Path, index: u32, unlock: &Unlock) -> io::Result<Keystore> {
        let (pubkey, secret) = bloch_crypto::crypto::generate_keypair();
        let mut randao_seed = [0u8; 32];
        os_random(&mut randao_seed)?;
        let ks = Keystore {
            index,
            pubkey,
            secret: Zeroizing::new(secret),
            randao_seed,
        };
        ks.save_with(dir, unlock)?;
        Ok(ks)
    }

    /// Write `dir/validator.key`, sealed unless the caller explicitly asked
    /// for plaintext.
    pub fn save_with(&self, dir: &Path, unlock: &Unlock) -> io::Result<()> {
        fs::create_dir_all(dir)?;
        let out = match unlock {
            Unlock::Passphrase { pass, kdf } => self.seal(pass, *kdf)?,
            Unlock::PlaintextOptIn => self.encode_plaintext(),
        };
        let path = dir.join("validator.key");
        // Created 0600, not created-then-chmodded. The old order left a window
        // in which the whole file already existed under the umask default
        // (0644 on every fleet host) — small, but it is the same window the
        // finding is about, and closing it costs one call.
        #[cfg(unix)]
        {
            use std::io::Write;
            use std::os::unix::fs::OpenOptionsExt;
            let mut f = fs::OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(0o600)
                .open(&path)?;
            f.write_all(&out)?;
            f.sync_all()?;
            // An existing file keeps its old mode through `.mode()`, which only
            // applies at creation — so a re-seal over a world-readable key
            // still gets tightened.
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&path, fs::Permissions::from_mode(0o600))?;
        }
        #[cfg(not(unix))]
        fs::write(&path, &out)?;
        Ok(())
    }

    /// The legacy `BPOSKEY1` body: the secret key in the clear. Reachable
    /// only through `Unlock::PlaintextOptIn`.
    fn encode_plaintext(&self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend_from_slice(KEYSTORE_MAGIC_V1);
        out.extend_from_slice(&self.index.to_le_bytes());
        crate::codec::put_bytes(&mut out, &self.pubkey);
        crate::codec::put_bytes(&mut out, &self.secret);
        out.extend_from_slice(&self.randao_seed);
        out
    }

    /// `BPOSKEY2`: Argon2id over a fresh salt, XChaCha20-Poly1305 over
    /// `secret ‖ randao_seed`, public header as AAD.
    fn seal(&self, passphrase: &str, kdf: KdfParams) -> io::Result<Vec<u8>> {
        let mut salt = [0u8; 32];
        os_random(&mut salt)?;
        let mut nonce = [0u8; 24];
        os_random(&mut nonce)?;

        let mut header = Vec::new();
        header.extend_from_slice(KEYSTORE_MAGIC_V2);
        header.push(KDF_ARGON2ID);
        header.extend_from_slice(&kdf.m_cost.to_le_bytes());
        header.extend_from_slice(&kdf.t_cost.to_le_bytes());
        header.extend_from_slice(&kdf.p_cost.to_le_bytes());
        header.extend_from_slice(&salt);
        header.extend_from_slice(&nonce);
        header.extend_from_slice(&self.index.to_le_bytes());
        crate::codec::put_bytes(&mut header, &self.pubkey);

        let mut plain = Zeroizing::new(Vec::new());
        crate::codec::put_bytes(&mut plain, &self.secret);
        plain.extend_from_slice(&self.randao_seed);

        let key = kdf.derive(passphrase, &salt)?;
        let cipher = XChaCha20Poly1305::new_from_slice(key.as_ref())
            .map_err(|_| io::Error::new(io::ErrorKind::Other, "AEAD key length"))?;
        let sealed = cipher
            .encrypt(
                XNonce::from_slice(&nonce),
                Payload {
                    msg: &plain,
                    aad: &header,
                },
            )
            .map_err(|_| io::Error::new(io::ErrorKind::Other, "keystore sealing failed"))?;

        let mut out = header;
        crate::codec::put_bytes(&mut out, &sealed);
        Ok(out)
    }

    /// Load `dir/validator.key` under the policy in the environment.
    ///
    /// A missing file still surfaces as `NotFound` — the engine reads that as
    /// "observer mode" and must keep doing so. The policy is only consulted
    /// once a file actually exists, so a node with no key does not fail to
    /// boot over an unconfigured passphrase.
    pub fn load(dir: &Path) -> io::Result<Keystore> {
        let bytes = Zeroizing::new(fs::read(dir.join("validator.key"))?);
        Self::decode(&bytes, &Unlock::from_env()?)
    }

    /// [`Keystore::load`] with the policy passed in rather than read from the
    /// environment.
    pub fn load_with(dir: &Path, unlock: &Unlock) -> io::Result<Keystore> {
        let bytes = Zeroizing::new(fs::read(dir.join("validator.key"))?);
        Self::decode(&bytes, unlock)
    }

    /// **The production loader.** `Ok(None)` means one thing and only one
    /// thing: `dir/validator.key` does not exist, so this node is an observer.
    /// Every other outcome — a keystore that is there but plaintext without
    /// the opt-in, sealed with no passphrase configured, sealed with the
    /// WRONG passphrase, unreadable, truncated, or whose passphrase file is
    /// missing — is a loud `Err`.
    ///
    /// ## Why this exists instead of matching on the error kind
    ///
    /// The engine used to spell the same rule as
    /// `match Keystore::load(..) { Err(e) if e.kind() == NotFound => observer }`,
    /// which quietly assumed that the only `NotFound` reachable from `load`
    /// was the keystore itself. It was not: `Unlock::from_env` read
    /// `BLOCH_KEYSTORE_PASSPHRASE_FILE` with a bare `?`, so a credential path
    /// that had not been provisioned yet — the ordinary first-boot and
    /// `LoadCredential=` failure — surfaced as `NotFound` too. A validator
    /// with a perfectly good sealed key on disk then printed
    /// "observer mode: no keystore in …" and ran on: no proposals, no
    /// attestations, no error, no exit code. On a fleet where restarts are
    /// routine, that is a validator lost to a typo, and the operator's only
    /// evidence is a line that says everything is fine.
    ///
    /// So the observer decision is made HERE, from the one fact that means
    /// it — the file is absent — and the caller gets an `Option` with no
    /// error kind left to misread. `from_sources` additionally guarantees no
    /// configuration refusal is ever kinded `NotFound`; this function does
    /// not depend on that, which is the point of having both.
    pub fn load_optional(dir: &Path) -> io::Result<Option<Keystore>> {
        Self::load_optional_inner(dir, None)
    }

    /// [`Keystore::load_optional`] with the policy passed in rather than read
    /// from the environment. Same contract: `Ok(None)` ⇔ no keystore file.
    pub fn load_optional_with(dir: &Path, unlock: &Unlock) -> io::Result<Option<Keystore>> {
        Self::load_optional_inner(dir, Some(unlock))
    }

    fn load_optional_inner(dir: &Path, unlock: Option<&Unlock>) -> io::Result<Option<Keystore>> {
        let path = dir.join("validator.key");
        let bytes = match fs::read(&path) {
            Ok(b) => Zeroizing::new(b),
            // The one and only observer signal.
            Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(None),
            // Present but unreadable (mode, ACL, I/O error) is NOT observer
            // mode. A node whose key it cannot read has a problem to fix, not
            // a role to assume.
            Err(e) => {
                return Err(io::Error::new(
                    e.kind(),
                    format!(
                        "{} exists but cannot be read ({e}); refusing to start as an \
                         observer with a validator key present",
                        path.display()
                    ),
                ))
            }
        };
        // A keystore IS present from here on, so a policy failure is fatal.
        let owned;
        let unlock = match unlock {
            Some(u) => u,
            None => {
                owned = Unlock::from_env()?;
                &owned
            }
        };
        Self::decode(&bytes, unlock).map(Some)
    }

    fn decode(bytes: &[u8], unlock: &Unlock) -> io::Result<Keystore> {
        let bad = |m: &'static str| io::Error::new(io::ErrorKind::InvalidData, m);
        if bytes.len() < 8 {
            return Err(bad("truncated keystore"));
        }
        match &bytes[..8] {
            m if m == KEYSTORE_MAGIC_V2 => Self::decode_sealed(bytes, unlock),
            m if m == KEYSTORE_MAGIC_V1 => Self::decode_plaintext(bytes, unlock),
            _ => Err(bad("not a bloch-pos keystore")),
        }
    }

    fn decode_plaintext(bytes: &[u8], unlock: &Unlock) -> io::Result<Keystore> {
        // The refusal, and the whole point of audit I-H1: a plaintext key on
        // disk is loaded only when someone said so. Note this fires even when
        // a passphrase IS configured — that operator asked for a sealed
        // keystore and got handed a plaintext one, which is exactly the
        // mismatch worth stopping on.
        if !matches!(unlock, Unlock::PlaintextOptIn) {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "validator.key is a PLAINTEXT (BPOSKEY1) keystore: the hybrid secret key and \
                 RANDAO seed are readable by anyone who can read the file. Re-seal it, or pass \
                 --allow-plaintext-keystore / BLOCH_KEYSTORE_ALLOW_PLAINTEXT=1 to load it as-is",
            ));
        }
        let bad = |m: &'static str| io::Error::new(io::ErrorKind::InvalidData, m);
        let mut r = crate::codec::Reader::new(bytes);
        r.take(8).map_err(|_| bad("truncated keystore"))?;
        let index = r.u32().map_err(|_| bad("truncated keystore"))?;
        let pubkey = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let secret = r.bytes().map_err(|_| bad("truncated keystore"))?;
        let randao_seed = r.h32().map_err(|_| bad("truncated keystore"))?;
        r.finish().map_err(|_| bad("trailing bytes in keystore"))?;
        Ok(Keystore {
            index,
            pubkey,
            secret: Zeroizing::new(secret),
            randao_seed,
        })
    }

    fn decode_sealed(bytes: &[u8], unlock: &Unlock) -> io::Result<Keystore> {
        let bad = |m: &'static str| io::Error::new(io::ErrorKind::InvalidData, m);
        let Unlock::Passphrase { pass, .. } = unlock else {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "validator.key is sealed and no passphrase is configured: set \
                 BLOCH_KEYSTORE_PASSPHRASE_FILE or BLOCH_KEYSTORE_PASSPHRASE",
            ));
        };
        let mut r = crate::codec::Reader::new(bytes);
        r.take(8).map_err(|_| bad("truncated keystore"))?;
        let kdf_id = r.u8().map_err(|_| bad("truncated keystore"))?;
        if kdf_id != KDF_ARGON2ID {
            return Err(bad("keystore uses a KDF this binary does not implement"));
        }
        let kdf = KdfParams {
            m_cost: r.u32().map_err(|_| bad("truncated keystore"))?,
            t_cost: r.u32().map_err(|_| bad("truncated keystore"))?,
            p_cost: r.u32().map_err(|_| bad("truncated keystore"))?,
        };
        let salt = r.h32().map_err(|_| bad("truncated keystore"))?;
        let nonce: [u8; 24] = r
            .take(24)
            .map_err(|_| bad("truncated keystore"))?
            .try_into()
            .unwrap();
        let index = r.u32().map_err(|_| bad("truncated keystore"))?;
        let pubkey = r.bytes().map_err(|_| bad("truncated keystore"))?;
        // Everything read so far is the AAD, byte for byte as written.
        let header_len = 8 + 1 + 12 + 32 + 24 + 4 + 4 + pubkey.len();
        let header = &bytes[..header_len];
        let sealed = r.bytes().map_err(|_| bad("truncated keystore"))?;
        r.finish().map_err(|_| bad("trailing bytes in keystore"))?;

        let key = kdf.derive(pass, &salt)?;
        let cipher = XChaCha20Poly1305::new_from_slice(key.as_ref())
            .map_err(|_| io::Error::new(io::ErrorKind::Other, "AEAD key length"))?;
        let plain = Zeroizing::new(
            cipher
                .decrypt(
                    XNonce::from_slice(&nonce),
                    Payload {
                        msg: &sealed,
                        aad: header,
                    },
                )
                .map_err(|_| {
                    // One message for a wrong passphrase and for a tampered
                    // file: the tag cannot tell them apart, and pretending it
                    // can is how an oracle starts.
                    io::Error::new(
                        io::ErrorKind::InvalidData,
                        "cannot open validator.key: wrong passphrase, or the keystore has been \
                         modified",
                    )
                })?,
        );

        let mut pr = crate::codec::Reader::new(&plain);
        let secret = pr.bytes().map_err(|_| bad("corrupt keystore body"))?;
        let randao_seed = pr.h32().map_err(|_| bad("corrupt keystore body"))?;
        pr.finish().map_err(|_| bad("corrupt keystore body"))?;
        Ok(Keystore {
            index,
            pubkey,
            secret: Zeroizing::new(secret),
            randao_seed,
        })
    }

    /// Sign a 32-byte consensus signing root with both halves of the hybrid
    /// suite. The domain tag is already inside the root (DS_PROPOSE /
    /// DS_ATTEST), per the pure crate's derivations.
    pub fn sign(&self, signing_root: &[u8; 32]) -> Vec<u8> {
        bloch_crypto::crypto::sign(&self.secret, signing_root)
            .expect("hybrid signing over a well-formed keystore key cannot fail")
    }
}

/// The real `SignatureVerifier`: bloch-crypto verify over a key the CALLER
/// resolved (both halves of the hybrid suite must pass).
///
/// ## This type used to hold a key table, and that table was the defect
///
/// It carried `pubkeys: Arc<Vec<Vec<u8>>>`, built once at boot from the
/// genesis manifest and never rebuilt — not after sync, not after replay — and
/// served `verify(index, ..)` out of it with `pubkeys.get(index)`. A validator
/// added by an on-chain deposit registered, activated, entered the roster and
/// got drawn for committees, and then every signature it made was rejected as
/// `BadSignature`, because its index was past the end of a vector frozen at
/// genesis. It could not attest, could not propose, and could not even be
/// slashed. Its committee seats were dead weight subtracted from finality.
///
/// The table is now **gone**, not merely unused: this struct holds no state at
/// all. The keys live where they were always committed — in the validator
/// registry inside consensus state, whose `ValidatorRecord::pubkey` doc has
/// said all along that "the registry *is* the authoritative key store". Every
/// consensus call site now resolves the key from a registry it names and
/// passes it to `verify_with_key`; see `attestation::KeyLookup` for which
/// state answers where.
///
/// Deleting the field rather than leaving it unread is deliberate. An unused
/// table is a table someone re-wires later.
#[derive(Clone)]
pub struct HybridVerifier;

impl HybridVerifier {
    pub fn new() -> Self {
        HybridVerifier
    }
}

impl Default for HybridVerifier {
    fn default() -> Self {
        Self::new()
    }
}

impl bloch_pos_committee::attestation::SignatureVerifier for HybridVerifier {
    /// The suite check itself. Robust to arbitrary key bytes by contract:
    /// `bloch_crypto::crypto::verify` documents "any body parse failure ⇒
    /// false, never a panic (consensus rule)" and guards every length before
    /// slicing. That matters more now than it did, because the bytes handed in
    /// here can come from the registry, and the live `Deposit` handler does
    /// **not** validate the suite or check a proof of possession before
    /// inserting a pubkey (`staking::validate_deposit`, which does both, has
    /// no production caller). So a registry key may be arbitrary bytes, and
    /// this must fail closed on them rather than panic. It does.
    fn verify_with_key(&self, pubkey: &[u8], signing_root: &[u8; 32], signature: &[u8]) -> bool {
        bloch_crypto::crypto::verify(pubkey, signing_root, signature)
    }
}

/// Accept-everything verifier for the producer's own `compute_post_state`
/// probe: the state a block commits does not depend on the verifier, and the
/// producer needs the post-state root *before* it can sign the header the
/// real verifier would check. Every block still passes through the real
/// [`HybridVerifier`] in `apply_block` before it is accepted or broadcast.
pub struct ProbeVerifier;

impl bloch_pos_committee::attestation::SignatureVerifier for ProbeVerifier {
    fn verify_with_key(&self, _pk: &[u8], _root: &[u8; 32], _sig: &[u8]) -> bool {
        true
    }
}

/// Fill `buf` from the OS entropy pool (`/dev/urandom`). Devnet-grade.
fn os_random(buf: &mut [u8]) -> io::Result<()> {
    use std::io::Read;
    let mut f = fs::File::open("/dev/urandom")?;
    f.read_exact(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use bloch_pos_committee::attestation::SignatureVerifier;

    /// The real suite, end to end, through the only entry point the trait now
    /// has. Disposable keypair generated in-process — no production or
    /// treasury key material is involved anywhere in this file.
    #[test]
    fn real_hybrid_signature_verifies_through_the_key_form() {
        let (pk, sk) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        assert!(HybridVerifier::new().verify_with_key(&pk, &root, &sig));
    }

    #[test]
    fn a_tampered_signature_fails() {
        let (pk, sk) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let mut sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        let last = sig.len() - 1;
        sig[last] ^= 0x01;
        assert!(!HybridVerifier::new().verify_with_key(&pk, &root, &sig));
    }

    #[test]
    fn a_signature_under_another_key_fails() {
        let (_pk_a, sk_a) = bloch_crypto::crypto::generate_keypair();
        let (pk_b, _sk_b) = bloch_crypto::crypto::generate_keypair();
        let root = [0x5Au8; 32];
        let sig = bloch_crypto::crypto::sign(&sk_a, &root).expect("sign");
        assert!(
            !HybridVerifier::new().verify_with_key(&pk_b, &root, &sig),
            "A's signature must not verify under B's key"
        );
    }

    /// The registry can hold arbitrary bytes as a pubkey, because the live
    /// `Deposit` handler checks neither the suite nor a proof of possession
    /// before inserting one (`staking::validate_deposit`, which does both, has
    /// no production caller). Now that those bytes reach the verifier, it must
    /// fail closed on every shape rather than panic — a panic in a consensus
    /// check is a remote halt.
    #[test]
    fn malformed_registry_keys_fail_closed_and_never_panic() {
        let v = HybridVerifier::new();
        let root = [0x11u8; 32];
        let (_pk, sk) = bloch_crypto::crypto::generate_keypair();
        let good_sig = bloch_crypto::crypto::sign(&sk, &root).expect("sign");
        for bad in [
            Vec::new(),
            vec![0u8; 1],
            vec![0u8; 3],
            vec![0xFFu8; 32],
            vec![0u8; 1951],       // ML-DSA half only, nothing after it
            vec![0xB1, 0x0C, 0, 0], // envelope magic, empty body
            vec![7u8; 100_000],
        ] {
            assert!(!v.verify_with_key(&bad, &root, &good_sig));
            assert!(!v.verify_with_key(&bad, &root, &[]));
        }
    }

    // ── Encryption at rest (audit I-H1) ─────────────────────────────────

    /// A fresh, unshared directory per test. Nothing here ever touches a
    /// fleet path: every key below is generated in-process and thrown away.
    fn tmp_dir(tag: &str) -> std::path::PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let d = std::env::temp_dir().join(format!(
            "bloch-pos-keys-{}-{}-{}-{}",
            tag,
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).expect("create the test keystore dir");
        d
    }

    /// Argon2id at the format's minimum cost. The parameters travel in the
    /// file, so this exercises the exact same code path as production —
    /// only cheaper, which keeps an unoptimized test binary usable.
    const CHEAP: KdfParams = KdfParams {
        m_cost: 8,
        t_cost: 1,
        p_cost: 1,
    };

    /// `Result::expect_err` needs `T: Debug`, and `Keystore` deliberately
    /// implements no `Debug` — that is the property keeping secret bytes out
    /// of every format string in this crate. So the error comes out by hand.
    fn err_of<T>(r: io::Result<T>, what: &str) -> io::Error {
        match r {
            Ok(_) => panic!("expected an error: {what}"),
            Err(e) => e,
        }
    }

    fn contains(hay: &[u8], needle: &[u8]) -> bool {
        !needle.is_empty() && hay.windows(needle.len()).any(|w| w == needle)
    }

    /// THE regression test for I-H1. Seal a keystore, then read the file back
    /// as bytes and look for the secret in it.
    ///
    /// Against the old code this fails on the first assert: `save` wrote
    /// `BPOSKEY1 ‖ index ‖ pubkey ‖ secret ‖ randao_seed`, so both the hybrid
    /// secret key and the RANDAO seed appear verbatim in the file.
    #[test]
    fn the_sealed_file_contains_neither_the_secret_key_nor_the_randao_seed() {
        let dir = tmp_dir("sealed");
        let ks = Keystore::generate_with(&dir, 7, &Unlock::passphrase_with("correct horse", CHEAP))
            .expect("generate + seal");
        let raw = fs::read(dir.join("validator.key")).expect("read the keystore back");

        // The secret assertions come FIRST on purpose: they are the finding.
        // A regression that reverts the format would trip the magic check too,
        // and the failure an operator reads should name what leaked.
        assert!(
            !contains(&raw, &ks.secret),
            "the hybrid SECRET KEY is present verbatim in validator.key"
        );
        assert!(
            !contains(&raw, &ks.randao_seed),
            "the RANDAO SEED is present verbatim in validator.key"
        );
        assert_eq!(&raw[..8], KEYSTORE_MAGIC_V2, "the file must be the sealed format");
        // The public halves are, correctly, still readable: they are the AAD.
        assert!(contains(&raw, &ks.pubkey), "the public key is public");
        let _ = fs::remove_dir_all(&dir);
    }

    /// A sealed keystore round-trips, and the reloaded key really is the same
    /// key — proved by a signature that verifies under the public half.
    #[test]
    fn a_sealed_keystore_round_trips_and_still_signs() {
        let dir = tmp_dir("roundtrip");
        let unlock = Unlock::passphrase_with("a passphrase", CHEAP);
        let a = Keystore::generate_with(&dir, 3, &unlock).expect("generate");
        let b = Keystore::load_with(&dir, &unlock).expect("re-open the sealed keystore");

        assert_eq!(a.index, b.index);
        assert_eq!(a.pubkey, b.pubkey);
        assert_eq!(a.randao_seed, b.randao_seed);
        let root = [0x2Cu8; 32];
        assert!(HybridVerifier::new().verify_with_key(&b.pubkey, &root, &b.sign(&root)));
        let _ = fs::remove_dir_all(&dir);
    }

    /// The wrong passphrase is a refusal, not a garbage key. Poly1305 decides
    /// this before a single byte of the secret is handed back.
    #[test]
    fn the_wrong_passphrase_fails_closed() {
        let dir = tmp_dir("wrongpass");
        Keystore::generate_with(&dir, 1, &Unlock::passphrase_with("right", CHEAP)).expect("gen");
        let e = err_of(
            Keystore::load_with(&dir, &Unlock::passphrase_with("wrong", CHEAP)),
            "a wrong passphrase must not open the keystore",
        );
        assert_eq!(e.kind(), io::ErrorKind::InvalidData);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The public header is the AEAD's AAD, so re-pointing a sealed secret at
    /// a different validator index is detected. Without the AAD binding this
    /// passes silently and a stolen file becomes validator N's key.
    #[test]
    fn rewriting_the_validator_index_breaks_the_tag() {
        let dir = tmp_dir("aad");
        let unlock = Unlock::passphrase_with("pp", CHEAP);
        Keystore::generate_with(&dir, 4, &unlock).expect("gen");
        let path = dir.join("validator.key");
        let mut raw = fs::read(&path).expect("read");
        // index sits right after magic(8) + kdf_id(1) + costs(12) + salt(32) + nonce(24).
        let at = 8 + 1 + 12 + 32 + 24;
        assert_eq!(u32::from_le_bytes(raw[at..at + 4].try_into().unwrap()), 4);
        raw[at..at + 4].copy_from_slice(&9u32.to_le_bytes());
        fs::write(&path, &raw).expect("write the tampered keystore");

        let e = err_of(
            Keystore::load_with(&dir, &unlock),
            "a re-indexed keystore must not open",
        );
        assert_eq!(e.kind(), io::ErrorKind::InvalidData);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The second half of I-H1: a plaintext keystore on disk is not loadable
    /// by accident. Against the old code this fails — `load` read `BPOSKEY1`
    /// unconditionally, which is what made every fleet host's key readable to
    /// anything that could read the file.
    #[test]
    fn a_plaintext_keystore_is_refused_without_the_explicit_opt_in() {
        let dir = tmp_dir("plainrefuse");
        // Written only because the caller asked for plaintext, out loud.
        Keystore::generate_with(&dir, 0, &Unlock::PlaintextOptIn).expect("gen plaintext");
        let raw = fs::read(dir.join("validator.key")).expect("read");
        assert_eq!(&raw[..8], KEYSTORE_MAGIC_V1);

        let e = err_of(
            Keystore::load_with(&dir, &Unlock::passphrase_with("pp", CHEAP)),
            "a plaintext keystore must not load under a passphrase policy",
        );
        assert_eq!(
            e.kind(),
            io::ErrorKind::PermissionDenied,
            "loading plaintext must be refused, not attempted"
        );

        // ...and it still opens for an operator who opted in, so an existing
        // fleet host is migrated on its own schedule rather than bricked.
        let ks = Keystore::load_with(&dir, &Unlock::PlaintextOptIn).expect("opt-in load");
        assert_eq!(ks.index, 0);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The mirror image: a sealed keystore does not open just because someone
    /// passed `--allow-plaintext-keystore`. The opt-in is permission to read
    /// plaintext, never permission to skip a passphrase.
    #[test]
    fn the_plaintext_opt_in_does_not_open_a_sealed_keystore() {
        let dir = tmp_dir("sealedoptin");
        Keystore::generate_with(&dir, 2, &Unlock::passphrase_with("pp", CHEAP)).expect("gen");
        let e = err_of(
            Keystore::load_with(&dir, &Unlock::PlaintextOptIn),
            "the plaintext opt-in is not a passphrase",
        );
        assert_eq!(e.kind(), io::ErrorKind::PermissionDenied);
        let _ = fs::remove_dir_all(&dir);
    }

    /// A missing keystore must still be `NotFound` and nothing else: the
    /// engine reads that error, and only that error, as "observer mode". If
    /// the unconfigured-passphrase refusal fired first, a node with no key at
    /// all would refuse to boot.
    #[test]
    fn a_missing_keystore_is_still_not_found_not_a_policy_refusal() {
        let dir = tmp_dir("absent");
        let e = err_of(
            Keystore::load_with(&dir, &Unlock::passphrase_with("pp", CHEAP)),
            "there is no keystore in this dir",
        );
        assert_eq!(e.kind(), io::ErrorKind::NotFound);
        let _ = fs::remove_dir_all(&dir);
    }

    /// A hostile keystore cannot turn its own header into an allocation: the
    /// memory cost is bounded before Argon2 is built.
    #[test]
    fn an_absurd_kdf_memory_cost_is_refused_before_it_allocates() {
        let e = err_of(
            KdfParams {
                m_cost: u32::MAX,
                t_cost: 1,
                p_cost: 1,
            }
            .to_argon2(),
            "u32::MAX KiB is 4 TiB",
        );
        assert_eq!(e.kind(), io::ErrorKind::InvalidData);
    }

    // ── Fail loud, never silently keyless (the loader contract) ─────────
    //
    // These four cover the second half of I-H1: sealing the file is worth
    // nothing if the loader answers "no keystore" when it means "I could not
    // open the keystore". `Ok(None)` is the engine's instruction to run as an
    // observer — no proposals, no attestations — and it must be reachable
    // from exactly one fact.

    /// `Result::expect_err`/`unwrap` need `T: Debug`, which `Keystore` does
    /// not implement on purpose. So `Option<Keystore>` comes apart by hand.
    fn expect_absent(r: io::Result<Option<Keystore>>, what: &str) {
        match r {
            Ok(None) => {}
            Ok(Some(_)) => panic!("expected no keystore: {what}"),
            Err(e) => panic!("expected Ok(None), got an error: {what}: {e}"),
        }
    }

    fn expect_loaded(r: io::Result<Option<Keystore>>, what: &str) -> Keystore {
        match r {
            Ok(Some(k)) => k,
            Ok(None) => panic!("SILENT: the keystore was there and the loader said None: {what}"),
            Err(e) => panic!("expected a loaded keystore: {what}: {e}"),
        }
    }

    fn expect_loud(r: io::Result<Option<Keystore>>, what: &str) -> io::Error {
        match r {
            Err(e) => e,
            Ok(None) => panic!("SILENT LIVENESS BUG: {what} — the loader answered \"no keystore\" \
                                over a keystore that exists. The engine reads that as observer \
                                mode and this validator would stop attesting without an error"),
            Ok(Some(_)) => panic!("expected a refusal, the keystore opened: {what}"),
        }
    }

    /// THE test the finding asks for, both directions.
    ///
    /// A plaintext keystore with no opt-in must be a LOUD error — not
    /// `Ok(None)`, which is how a restart turns a validator into an observer
    /// while the log says everything is fine — and the same file must still
    /// open for an operator who did opt in, so a fleet host is migrated on
    /// its own schedule instead of being bricked by this fix.
    #[test]
    fn plaintext_without_the_flag_is_loud_and_with_the_flag_still_loads() {
        let dir = tmp_dir("loudplain");
        Keystore::generate_with(&dir, 11, &Unlock::PlaintextOptIn).expect("gen plaintext");

        let e = expect_loud(
            Keystore::load_optional_with(&dir, &Unlock::passphrase_with("pp", CHEAP)),
            "a plaintext keystore under a passphrase policy",
        );
        assert_eq!(e.kind(), io::ErrorKind::PermissionDenied);
        assert_ne!(
            e.kind(),
            io::ErrorKind::NotFound,
            "a refusal must never be able to pass for a missing keystore"
        );

        let ks = expect_loaded(
            Keystore::load_optional_with(&dir, &Unlock::PlaintextOptIn),
            "the explicit opt-in must still load a legacy plaintext keystore",
        );
        assert_eq!(ks.index, 11);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The other two ways a present keystore fails to open: no passphrase,
    /// and the wrong one. Both must be loud. Only an absent file is `None`.
    #[test]
    fn a_present_keystore_that_will_not_open_is_never_reported_as_absent() {
        let dir = tmp_dir("loudsealed");
        Keystore::generate_with(&dir, 5, &Unlock::passphrase_with("right", CHEAP)).expect("gen");

        expect_loud(
            Keystore::load_optional_with(&dir, &Unlock::PlaintextOptIn),
            "a sealed keystore and no passphrase",
        );
        expect_loud(
            Keystore::load_optional_with(&dir, &Unlock::passphrase_with("wrong", CHEAP)),
            "a sealed keystore and the wrong passphrase",
        );
        let ks = expect_loaded(
            Keystore::load_optional_with(&dir, &Unlock::passphrase_with("right", CHEAP)),
            "the right passphrase",
        );
        assert_eq!(ks.index, 5);
        let _ = fs::remove_dir_all(&dir);
    }

    /// And the liveness half of the contract, which is just as load-bearing:
    /// a node with genuinely no key must still boot as an observer rather
    /// than fail on an unconfigured passphrase.
    #[test]
    fn only_an_absent_file_selects_observer_mode() {
        let dir = tmp_dir("observer");
        expect_absent(
            Keystore::load_optional_with(&dir, &Unlock::passphrase_with("pp", CHEAP)),
            "no validator.key in this dir",
        );
        expect_absent(
            Keystore::load_optional_with(&dir, &Unlock::PlaintextOptIn),
            "no validator.key in this dir, plaintext policy",
        );
        let _ = fs::remove_dir_all(&dir);
    }

    /// The exact leak the engine's old `e.kind() == NotFound` match caught by
    /// accident: an unprovisioned `BLOCH_KEYSTORE_PASSPHRASE_FILE`.
    ///
    /// Before the fix this returned the raw `fs::read` error, kind
    /// `NotFound`, indistinguishable from "there is no keystore" — so a
    /// validator whose credential path had not been mounted yet came back
    /// from a restart as a silent observer. Read through the pure
    /// `from_sources` so no global environment is touched.
    #[test]
    fn a_missing_passphrase_file_cannot_impersonate_a_missing_keystore() {
        let missing = tmp_dir("nopassfile").join("credential-that-was-never-mounted");
        assert!(!missing.exists());
        let e = err_of(
            Unlock::from_sources(Some(missing.clone().into_os_string()), None, false),
            "the passphrase file does not exist",
        );
        assert_ne!(
            e.kind(),
            io::ErrorKind::NotFound,
            "a missing passphrase file must not be kinded like a missing keystore"
        );
        assert_eq!(e.kind(), io::ErrorKind::PermissionDenied);

        // No configuration at all is also a refusal, and also not NotFound.
        let e = err_of(
            Unlock::from_sources(None, None, false),
            "nothing configured",
        );
        assert_ne!(e.kind(), io::ErrorKind::NotFound);

        // ...while the configurations that ARE valid still resolve.
        assert!(matches!(
            Unlock::from_sources(None, Some("pp".into()), false),
            Ok(Unlock::Passphrase { .. })
        ));
        assert!(matches!(
            Unlock::from_sources(None, None, true),
            Ok(Unlock::PlaintextOptIn)
        ));
        // An empty BLOCH_KEYSTORE_PASSPHRASE is not a passphrase.
        assert!(Unlock::from_sources(None, Some(String::new()), false).is_err());
        let _ = fs::remove_dir_all(missing.parent().unwrap());
    }

    /// Junk is junk under every policy — no panic, no partial key.
    #[test]
    fn a_file_that_is_not_a_keystore_is_refused_under_both_policies() {
        for policy in [Unlock::PlaintextOptIn, Unlock::passphrase_with("pp", CHEAP)] {
            for bad in [
                Vec::new(),
                b"BPOS".to_vec(),
                b"BPOSKEY9garbage".to_vec(),
                vec![0u8; 200],
            ] {
                assert!(Keystore::decode(&bad, &policy).is_err());
            }
        }
    }
}
