// SPDX-License-Identifier: AGPL-3.0-or-later

//! # bloch-pos — the Genesis-4 node binary
//!
//! This binary runs the live proof-of-stake mainnet. It called itself a
//! devnet-stage build until 2026-08-14 — which was true when written and
//! false the moment Genesis-4 launched, and it was the first line anyone
//! evaluating the software read.
//!
//! From the skeleton this grew into a node that actually runs: a devnet of N
//! validator processes produces blocks, attests, justifies and finalizes over
//! a local TCP mesh, with real ML-DSA-65 ‖ Falcon-1024 hybrid signatures and
//! append-only block-log persistence (restart = deterministic replay).
//!
//! Since 2026-08-13 it also has a production network layer (`p2p`): libp2p +
//! gossipsub on Genesis-4-only protocol ids, carrying the Genesis-3 mesh
//! fixes, with `gossip.rs` wired as attestation admission control and a
//! directed, paginated block-sync path. A node started with an **empty data
//! dir** syncs from genesis and validates every block itself — no datadir is
//! ever donated. `--transport devnet` keeps the original TCP mesh, and is
//! still the default.
//!
//! What it is NOT yet — honestly, per the integration plan
//! (`docs/specs/BLOCH-POS-NODE-INTEGRATION.md`): no RocksDB store, no
//! post-quantum transport handshake (the p2p layer uses Noise; consensus
//! signatures are hybrid PQ regardless), no peer persistence or peer
//! exchange, no deposits/exits, no slashing-evidence pipeline, no
//! checkpoint-sync **state download** (the weak-subjectivity boot gate itself
//! IS wired — `ws_boot`), no RPC, no mainnet genesis manifest. See the module
//! docs of `engine`, `net`, `p2p`, `store`, `ws_boot` for each limitation at
//! its site.
//!
//! ## Key hygiene
//!
//! `keygen` produces **throwaway devnet keys only** (never printed, 0600
//! files). Production keys are generated by a human on an air-gapped machine
//! per BLOCH-GENESIS-KEYS.md rule zero — never by this tool in an observable
//! session.
//!
//! ## Ownership
//!
//! `main.rs` is the composition root (PMO change-controlled; §9.4 two-reviewer
//! rule once integration review starts).

mod codec;
mod engine;
mod genesis;
mod keys;
mod net;
mod p2p;
mod rpc;
mod signing_history;
mod store;
mod ws_boot;

use std::path::PathBuf;
use std::process::exit;

use bloch_pos_committee::genesis_cohort::{
    cohort_cap_bps, COHORT_CAP_FLOOR_BPS, COHORT_CAP_START_BPS, COHORT_TAPER_EPOCHS,
};
use bloch_pos_committee::params::{
    DS_ATTEST, DS_BLOCK, DS_BODY, DS_DEPOSIT, DS_EXIT, DS_PROPOSE, DS_RANDAO, DS_SLASH,
    DS_SORTITION, DS_STATE, SLOTS_PER_EPOCH, SLOT_DURATION_SECS,
};
use bloch_pos_committee::tokenomics_v4::{
    FOUNDER_BLOCH, SAT_PER_BLOCH, TEAM_BLOCH, TOTAL_SUPPLY_SAT, VALIDATOR_EMISSION_BLOCH, VC_BLOCH,
};

const NAME: &str = env!("CARGO_PKG_NAME");

/// Default JSON-RPC port. Deliberately NOT the Genesis-3 node's 16210: the
/// migration plan keeps a G3 archive node serving the frozen V3 surface, and
/// the two are expected to run on the same host during the changeover. Sharing
/// a port would mean whichever bound first silently answered for the other
/// chain — a client asking a V4 node for `getblockcount` and getting a PoW
/// height is the kind of confusion that ends in a miscredited deposit.
const DEFAULT_RPC_PORT: u16 = 16310;
/// `pkg-version (git-commit[+dirty])`, stamped by build.rs. The commit is the
/// load-bearing part: the G8 release-integrity gate compares fleet, release
/// and source through it (deploy/RELEASE-INTEGRITY.md). Never fall back to
/// bare CARGO_PKG_VERSION — three identical "0.3.0-genesis2" strings on three
/// different binaries is the exact failure this replaces.
const VERSION: &str = env!("BLOCH_BUILD_VERSION");

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("--version") | Some("-V") => {
            println!(
                "{NAME} {VERSION} (Genesis-4, block version {:#010x})",
                bloch_pos_committee::header::VERSION_G4
            );
        }
        Some("--help") | Some("-h") | None => print_help(),
        Some("selfcheck") => {
            self_check();
            println!("self-check passed");
        }
        Some("keygen") => keygen(&args[1..]),
        Some("keygen-public") => keygen_public(&args[1..]),
        Some("genesis") => genesis_cmd(&args[1..]),
        Some("genesis-mainnet") => genesis_mainnet(&args[1..]),
        Some("submit-tx") => submit_tx(&args[1..]),
        Some("protection-export") => protection_export(&args[1..]),
        Some("protection-import") => protection_import(&args[1..]),
        Some("run") => run_cmd(&args[1..]),
        Some(other) => {
            eprintln!("{NAME}: unknown command `{other}` (see --help)");
            exit(2);
        }
    }
}

fn print_help() {
    println!(
        "{NAME} {VERSION} — Bloch Genesis-4 Proof-of-Stake node\n\
         \n\
         USAGE:\n\
           bloch-pos selfcheck\n\
               Verify the frozen consensus parameters this binary links.\n\
           bloch-pos keygen --dir <dir> --index <i>\n\
               Generate a THROWAWAY devnet validator keystore (hybrid\n\
               ML-DSA-65‖Falcon-1024 + RANDAO seed) at <dir>/validator.key.\n\
               Devnet only; production keys follow BLOCH-GENESIS-KEYS.md.\n\
           bloch-pos keygen-public --dir <dir>\n\
               Print one TSV row of a keystore's PUBLIC halves — the only
               thing that leaves the air-gapped ceremony machine. Secret
               material is unreachable from this command.\n\
           bloch-pos submit-tx --to <host:port> --pubkey <hex>\n\
                               --spend <txid-hex>:<vout> [--spend ...]\n\
                               --pay <script-hash-hex>:<sat> [--pay ...]\n\
                               [--signature <hex>] [--tx-bytes n]\n\
                               [--tip millisat-per-gas]\n\
               Send one Transfer to a running node, which gossips it on.\n\
               --pay order IS the output order (position = vout).\n\
               WITHOUT --signature it prints the signing root and sends\n\
               nothing: sign that digest elsewhere, then re-run with the\n\
               SAME flags plus --signature. This tool never holds a\n\
               spending key. No acknowledgement: confirmation is seeing\n\
               it in a block.\n\
           bloch-pos genesis --keys <dir1,dir2,...> --out <file>\n\
                             [--slot-ms <ms>] [--start-in <secs>]\n\
               Build a devnet genesis manifest from the keystores' public\n\
               parts. Slot 0 starts <secs> from now (default 5).\n\
           bloch-pos run --data-dir <dir> --genesis <file>\n\
                         [--transport devnet|libp2p]\n\
               devnet (default) is the TCP full mesh: no authentication, no\n\
               admission control, no relay logic. It is what the 64-validator\n\
               devnet finalized on and it stays reproducible.\n\
               libp2p is the production stack: gossipsub on Genesis-4-only\n\
               protocol ids, gossip.rs admission control, directed paginated\n\
               sync. Anything reachable from outside a firewall wants this.\n\
         \n\
             devnet transport:\n\
                         --listen <port> [--listen-addr <ip>]\n\
                         --peers <host:port,...>\n\
               --listen-addr binds the mesh listener somewhere other than\n\
               127.0.0.1, which is what a devnet spread across hosts needs.\n\
               This transport has no authentication and no admission\n\
               control, so a routable bind MUST be firewalled to the known\n\
               peer addresses.\n\
         \n\
             libp2p transport:\n\
                         [--p2p-listen <multiaddr>[,...]] (default\n\
                          /ip4/0.0.0.0/tcp/16400)\n\
                         [--p2p-peer <multiaddr>[,...]]\n\
                         [--max-peers <n>] [--behind-proxy]\n\
               Peers are dialled as /ip4/<host>/tcp/<port>/p2p/<peer-id>.\n\
               The node prints its own peer id at startup. --behind-proxy\n\
               zeroes the IP-colocation score penalty, which otherwise\n\
               graylists a whole mesh that shares one proxy address.\n\
         \n\
                         [--stop-at-slot <n>]\n\
                         [--ws-checkpoint <file>] [--ws-signer-set <file>]\n\
                         [--carryover <snapshot.tsv>]\n\
               Run a validator node. <dir> must hold validator.key; chain\n\
               data persists in <dir> and is replayed on restart.\n\
               --carryover is the Genesis-3 balance snapshot\n\
               (bloch-snapshot-utxo's TSV). Required exactly when the\n\
               manifest carries a carryover commitment, and checked against\n\
               all four of its fields — file digest, set root, count and\n\
               total — before a single balance is admitted. A devnet\n\
               manifest commits to none and the flag is then refused.\n\
                         [--rpc-bind <ip>] [--rpc-port <n>|off]\n\
               Run a validator node. <dir> must hold validator.key; chain\n\
               data persists in <dir> and is replayed on restart.\n\
               \n\
               JSON-RPC 2.0 over HTTP is served on --rpc-bind:--rpc-port,\n\
               default 127.0.0.1:16310 (`--rpc-port off` disables it). It\n\
               answers for THIS node's own validated state — run your own\n\
               node and query it rather than trusting someone else's.\n\
                 Methods: getchaininfo, getblockcount, getblockbyslot,\n\
                 getblockbyid, getvalidator, getvalidatorcount, getbalance,\n\
                 getutxos (alias listunspent), sendrawtransaction,\n\
                 getmempoolinfo. gettransaction and getnewaddress answer\n\
                 with a permanent, explained refusal — there is no txid at\n\
                 this layer and this node holds no wallet.\n\
                 Finality: block responses carry `finalized: true|false`.\n\
                 That boolean, not a confirmation count, is the settlement\n\
                 guarantee — PoS has no depth-as-security.\n\
               \n\
               *** The RPC has NO AUTHENTICATION. *** No API key, no rate\n\
               limit, no per-method authorisation, and sendrawtransaction is\n\
               a write. The 127.0.0.1 default is what keeps that safe. If you\n\
               bind a routable address with --rpc-bind, YOU MUST firewall the\n\
               port to the clients that are meant to reach it; anything that\n\
               can open a socket to it can read the node's entire state and\n\
               submit transactions.\n\
               A node started with an EMPTY data dir syncs from genesis: it\n\
               downloads every block from peers and validates each one\n\
               itself. No datadir is ever donated. While the chain is\n\
               younger than the weak-subjectivity period that needs no\n\
               checkpoint at all; past it, a fresh node requires\n\
               --ws-checkpoint and says so rather than syncing blindly.\n\
               --ws-checkpoint supplies a signed weak-subjectivity\n\
               checkpoint envelope (BLOCH-WEAK-SUBJECTIVITY.md §4.1). A node\n\
               with neither a fresh checkpoint nor fresh finality of its own\n\
               REFUSES to sync — that is the mechanism, not a fault. This\n\
               devnet build bakes no signer arrangement, so --ws-signer-set\n\
               must accompany --ws-checkpoint. With neither flag the genesis\n\
               anchor is the first checkpoint, which is why a fresh devnet\n\
               boots with no ceremony.\n\
                         [--accept-new-signing-history]\n\
               Slashing protection: <dir>/signing_history.bin records the\n\
               highest slot this key ever proposed and the highest\n\
               source/target epochs it ever attested, fsynced BEFORE each\n\
               signature is released, and the node refuses to sign anything\n\
               at or below those watermarks. A validator whose keystore has\n\
               no history file REFUSES TO START rather than signing blind.\n\
               --accept-new-signing-history creates a fresh, empty history —\n\
               pass it ONLY when this key has genuinely never signed on this\n\
               network, anywhere. If the key has signed before, carry its\n\
               history over with protection-export / protection-import\n\
               instead; an empty history on a used key is how validators get\n\
               slashed. See docs/specs/BLOCH-SLASHING-PROTECTION.md.\n\
           bloch-pos protection-export --data-dir <dir> [--out <file>]\n\
               Write the key's signing history in the documented text\n\
               interchange format (stdout by default). Run this BEFORE\n\
               moving a validator key to another machine, and carry the\n\
               file WITH the key.\n\
           bloch-pos protection-import --data-dir <dir> --from <file>\n\
               Install (or merge into) <dir>/signing_history.bin from an\n\
               exported file. Merging only ever RAISES watermarks. Run this\n\
               on the destination machine BEFORE the first `run` with a\n\
               migrated key.\n\
         \n\
         The integration plan is docs/specs/BLOCH-POS-NODE-INTEGRATION.md."
    );
}

/// `submit-tx --to <host:port> --spend <txid-hex>:<vout> --pubkey <hex>
///  --pay <script-hash-hex>:<sat> [--signature <hex>] [--tx-bytes n] [--tip n]`
///
/// Builds one `Transfer` and hands it to a node, which gossips it onward.
/// Transfer is the only variant this emits on purpose: `Deposit` and
/// `Delegate` describe validator-set changes that a devnet's genesis set does
/// not need and that would want key material to be meaningful, and evidence
/// cannot travel this way at all — its canonical encoding is one-way (see
/// `PosTransaction::from_canonical_bytes`).
///
/// # Why the flags changed shape
///
/// This used to read `--inputs n --tx-bytes n --tip n`: three numbers that
/// described a transfer's *cost* and named no coin, no recipient and no
/// amount, because that was all the variant carried. A transfer now moves
/// value, so it needs the outpoints it spends, the key that unlocks them, and
/// the outputs it creates.
///
/// # This tool does not hold keys and does not sign
///
/// With no `--signature` it prints the transfer's signing root and stops:
/// that digest is what an external signer — the wallet, an HSM, an air-gapped
/// machine — takes, and the resulting signature comes back in on
/// `--signature`. A devnet convenience that generated a keypair here would be
/// a keypair on an operator's shell history, and this crate has no business
/// creating spending keys at all.
fn submit_tx(args: &[String]) {
    let Some(to) = arg_value(args, "--to") else {
        eprintln!("submit-tx: --to <host:port> is required");
        exit(2);
    };
    let num = |name: &str, default: u128| -> u128 {
        arg_value(args, name)
            .and_then(|s| s.parse().ok())
            .unwrap_or(default)
    };
    let bail = |m: String| -> ! {
        eprintln!("submit-tx: {m}");
        exit(2)
    };

    // --spend <txid-hex>:<vout>, repeatable.
    let mut inputs = Vec::new();
    let pubkey = match arg_value(args, "--pubkey").as_deref().map(codec::unhex) {
        Some(Ok(k)) => k,
        Some(Err(e)) => bail(format!("--pubkey: {e}")),
        None => bail("--pubkey <hex> is required".into()),
    };
    for (i, a) in args.iter().enumerate() {
        if a != "--spend" {
            continue;
        }
        let Some(spec) = args.get(i + 1) else {
            bail("--spend needs <txid-hex>:<vout>".into())
        };
        let Some((txid_hex, vout)) = spec.rsplit_once(':') else {
            bail(format!("--spend {spec}: expected <txid-hex>:<vout>"))
        };
        let txid = match codec::unhex(txid_hex) {
            Ok(b) if b.len() == 32 => {
                let mut a = [0u8; 32];
                a.copy_from_slice(&b);
                a
            }
            Ok(b) => bail(format!("--spend: txid is {} bytes, expected 32", b.len())),
            Err(e) => bail(format!("--spend: {e}")),
        };
        let Ok(vout) = vout.parse::<u32>() else {
            bail(format!("--spend: bad vout {vout}"))
        };
        inputs.push(bloch_pos_committee::transition::TransferInput {
            txid,
            vout,
            pubkey: pubkey.clone(),
            // Filled in below once the signing root is known; a signature can
            // never cover itself.
            signature: Vec::new(),
        });
    }
    if inputs.is_empty() {
        bail("at least one --spend <txid-hex>:<vout> is required".into());
    }

    // --pay <script-hash-hex>:<sat>, repeatable and ordered: the position IS
    // the vout, so the order the flags are given in is consensus-visible.
    let mut outputs = Vec::new();
    for (i, a) in args.iter().enumerate() {
        if a != "--pay" {
            continue;
        }
        let Some(spec) = args.get(i + 1) else {
            bail("--pay needs <script-hash-hex>:<sat>".into())
        };
        let Some((sh_hex, value)) = spec.rsplit_once(':') else {
            bail(format!("--pay {spec}: expected <script-hash-hex>:<sat>"))
        };
        let script_hash = match codec::unhex(sh_hex) {
            Ok(b) if b.len() == 32 => {
                let mut a = [0u8; 32];
                a.copy_from_slice(&b);
                a
            }
            Ok(b) => bail(format!(
                "--pay: script hash is {} bytes, expected 32",
                b.len()
            )),
            Err(e) => bail(format!("--pay: {e}")),
        };
        let Ok(value) = value.parse::<u64>() else {
            bail(format!("--pay: bad value {value}"))
        };
        outputs.push(bloch_pos_committee::transition::TransferOutput { value, script_hash });
    }

    // `tx_bytes` is INSIDE the signing root, so it has to be fixed before the
    // root is printed and must not move afterwards — raising it to fit the
    // encoding after signing would silently invalidate the signature that was
    // produced over the smaller value. The default assumes one hybrid
    // signature per input (`HYBRID_SIG_BYTES`) plus a generous envelope; an
    // exact figure is what `--tx-bytes` is for.
    let n_inputs = inputs.len() as u64;
    let default_bytes = 1_024
        + n_inputs * (bloch_pos_committee::fee_market::HYBRID_SIG_BYTES + pubkey.len() as u64 + 64);
    let mut tx = bloch_pos_committee::transition::PosTransaction::Transfer {
        inputs,
        outputs,
        tx_bytes: num("--tx-bytes", default_bytes as u128) as u64,
        tip_millisat_per_gas: num("--tip", 1_000),
    };

    let Some(sig_hex) = arg_value(args, "--signature") else {
        // No signature: print what has to be signed and stop. The root does
        // not depend on the signatures — which is exactly why it can be shown
        // before they exist — but it DOES depend on every other field, so the
        // same flags must be repeated verbatim on the signed run.
        println!("{}", codec::hex(&tx.spend_signing_root()));
        eprintln!(
            "submit-tx: no --signature given; the line above is the signing root.\n\
             Sign it with the key whose SHA3-256 the spent outputs commit to, then\n\
             re-run with the SAME flags plus --signature <hex>. Changing any flag\n\
             (including --tx-bytes and --tip) changes the root and voids the\n\
             signature. Nothing was sent."
        );
        exit(0);
    };
    let signature = match codec::unhex(&sig_hex) {
        Ok(s) => s,
        Err(e) => bail(format!("--signature: {e}")),
    };
    if let bloch_pos_committee::transition::PosTransaction::Transfer { inputs, .. } = &mut tx {
        for i in inputs.iter_mut() {
            i.signature = signature.clone();
        }
    }
    // Consensus refuses a declared size below the encoding
    // (`TransferReject::UnderdeclaredSize`). Report it instead of "fixing" it:
    // the fix is to re-sign at a larger --tx-bytes, and only the key holder
    // can do that.
    let encoded = tx.canonical_bytes().len() as u64;
    if let bloch_pos_committee::transition::PosTransaction::Transfer { tx_bytes, .. } = &tx {
        if *tx_bytes < encoded {
            bail(format!(
                "--tx-bytes {tx_bytes} is below this transaction's {encoded}-byte encoding; \
                 a node would refuse it. Re-run the unsigned step with \
                 --tx-bytes {encoded} (or more) and sign that root instead."
            ));
        }
    }
    let bytes = tx.canonical_bytes();
    match bloch_pos_node_net_send(&to, &bytes) {
        Ok(()) => println!(
            "submitted {} bytes to {to} — it lands in a block or it does not; \
             this transport does not acknowledge",
            bytes.len()
        ),
        Err(e) => {
            eprintln!("submit-tx: {e}");
            exit(1);
        }
    }
}

fn bloch_pos_node_net_send(addr: &str, bytes: &[u8]) -> std::io::Result<()> {
    net::send_transaction(addr, bytes)
}

fn arg_value(args: &[String], name: &str) -> Option<String> {
    args.iter()
        .position(|a| a == name)
        .and_then(|i| args.get(i + 1))
        .cloned()
}

/// `keygen-public --dir <dir>` — one TSV row of a keystore's PUBLIC halves.
///
/// The carry-out half of the ceremony. An air-gapped machine holds the
/// keystores forever; what leaves it is this row per validator, and nothing
/// else. Reads the keystore and prints index, hybrid public key, and the
/// RANDAO commitment — the head of the reveal chain, which is a commitment
/// precisely so the seed behind it can stay on the machine.
///
/// The three columns it cannot know are left empty rather than defaulted:
/// `stake_sat`, `withdrawal_credentials` and `commission_bps` are decisions,
/// not derivations, and a genesis where nobody chose them is a genesis
/// somebody will have to explain later.
///
/// Nothing here can print a secret: `Keystore`'s secret field is private and
/// implements no `Debug`, so there is no path from this function to the key.
fn keygen_public(args: &[String]) {
    let Some(dir) = arg_value(args, "--dir") else {
        eprintln!("keygen-public: --dir is required");
        exit(2);
    };
    match keys::Keystore::load(&PathBuf::from(&dir)) {
        Ok(ks) => {
            let commitment =
                bloch_pos_committee::beacon::RandaoChain::generate(ks.randao_seed).commitment();
            println!(
                "{}\t{}\t{}\t\t\t",
                ks.index,
                hex_lower(&ks.pubkey),
                hex_lower(&commitment)
            );
        }
        Err(e) => {
            eprintln!("keygen-public: cannot read {dir}: {e}");
            exit(1);
        }
    }
}

fn hex_lower(b: &[u8]) -> String {
    let mut s = String::with_capacity(b.len() * 2);
    for byte in b {
        s.push_str(&format!("{byte:02x}"));
    }
    s
}

fn keygen(args: &[String]) {
    let Some(dir) = arg_value(args, "--dir") else {
        eprintln!("keygen: --dir is required");
        exit(2);
    };
    let Some(index) = arg_value(args, "--index").and_then(|s| s.parse::<u32>().ok()) else {
        eprintln!("keygen: --index <u32> is required");
        exit(2);
    };
    match keys::Keystore::generate(&PathBuf::from(&dir), index) {
        Ok(ks) => {
            use sha3::{Digest, Sha3_256};
            let pkh: [u8; 32] = Sha3_256::digest(&ks.pubkey).into();
            // The key is born WITH its slashing-protection store, so a key
            // never exists without the record of what it has signed (which,
            // right now, is nothing). It is network-unbound because keygen
            // cannot know the genesis digest; the first `run` binds it.
            if let Err(e) =
                signing_history::SigningHistory::create_unbound(&PathBuf::from(&dir), &ks.pubkey)
            {
                eprintln!("keygen: could not create the signing-history store: {e}");
                exit(1);
            }
            // Public information only — never a secret byte.
            println!(
                "wrote {dir}/validator.key (devnet, throwaway): validator {index}, \
                 pubkey sha3 {}, randao commitment {}\n\
                 wrote {dir}/{} (empty slashing-protection history — travels WITH the key)",
                codec::hex8(&pkh),
                codec::hex8(
                    &bloch_pos_committee::beacon::RandaoChain::generate(ks.randao_seed)
                        .commitment()
                ),
                signing_history::HISTORY_FILE,
            );
        }
        Err(e) => {
            eprintln!("keygen failed: {e}");
            exit(1);
        }
    }
}

/// `protection-export --data-dir <dir> [--out <file>]` — the signing history
/// in the interchange text format (BLOCH-SLASHING-PROTECTION.md §3).
///
/// This is the first half of the only safe key migration: export here, carry
/// the file WITH the key, `protection-import` on the destination before the
/// first `run`. Migrating a validator key without its history is exactly how
/// double-signing happens.
fn protection_export(args: &[String]) {
    let Some(dir) = arg_value(args, "--data-dir") else {
        eprintln!("protection-export: --data-dir is required");
        exit(2);
    };
    let h = match signing_history::SigningHistory::open(&PathBuf::from(&dir)) {
        Ok(h) => h,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!(
                "protection-export: {dir} holds no {}. Nothing to export — and if \
                 validator.key in that dir HAS signed, its history is lost and the only \
                 safe course is to treat the key as unsafe to run until the chain has \
                 moved past everything it could have signed.",
                signing_history::HISTORY_FILE
            );
            exit(1);
        }
        Err(e) => {
            eprintln!("protection-export: cannot read the signing history: {e}");
            exit(1);
        }
    };
    let text = h.export_text();
    match arg_value(args, "--out") {
        None => print!("{text}"),
        Some(out) => {
            if let Err(e) = std::fs::write(&out, &text) {
                eprintln!("protection-export: cannot write {out}: {e}");
                exit(1);
            }
            println!(
                "wrote {out} — carry this file WITH the key; import it on the destination \
                 with `bloch-pos protection-import` BEFORE the first run"
            );
        }
    }
}

/// `protection-import --data-dir <dir> --from <file>` — install or merge a
/// signing history exported by `protection-export`.
///
/// Merging only ever RAISES watermarks (the node ends up refusing more,
/// never less), refuses a record for a different validator key, and refuses
/// a record from a different network. If the data dir holds a keystore, the
/// record must match it.
fn protection_import(args: &[String]) {
    let (Some(dir), Some(from)) = (arg_value(args, "--data-dir"), arg_value(args, "--from"))
    else {
        eprintln!("protection-import: --data-dir and --from are required");
        exit(2);
    };
    let text = match std::fs::read_to_string(&from) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("protection-import: cannot read {from}: {e}");
            exit(1);
        }
    };
    let rec = match signing_history::SigningHistory::parse_interchange(&text) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("protection-import: {from} is not a valid interchange file: {e}");
            exit(1);
        }
    };
    let dir = PathBuf::from(dir);
    // If the destination already holds the key, the record must be FOR that
    // key — importing someone else's history protects nothing.
    match keys::Keystore::load(&dir) {
        Ok(ks) if ks.pubkey != rec.pubkey => {
            eprintln!(
                "protection-import: {from} records the history of a DIFFERENT validator \
                 key than {}/validator.key; refusing",
                dir.display()
            );
            exit(1);
        }
        _ => {} // matching key, or no keystore yet (import-before-key is fine)
    }
    match signing_history::SigningHistory::open(&dir) {
        Ok(mut h) => match h.merge_interchange(&rec) {
            Ok(summary) => println!(
                "merged {from} into {}/{}: {summary}",
                dir.display(),
                signing_history::HISTORY_FILE
            ),
            Err(e) => {
                eprintln!("protection-import: {e}");
                exit(1);
            }
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            match signing_history::SigningHistory::create_from_interchange(&dir, &rec) {
                Ok(h) => println!(
                    "installed {}/{} (proposal watermark {}, attestation watermark {})",
                    dir.display(),
                    signing_history::HISTORY_FILE,
                    h.highest_proposed_slot()
                        .map_or("none".to_string(), |n| n.to_string()),
                    h.attestation_watermark()
                        .map_or("none".to_string(), |(s, t)| format!("({s}, {t})")),
                ),
                Err(e) => {
                    eprintln!("protection-import: cannot install the history: {e}");
                    exit(1);
                }
            }
        }
        Err(e) => {
            eprintln!("protection-import: cannot read the existing history: {e}");
            exit(1);
        }
    }
}

/// `genesis-mainnet --cohort <cohort.tsv> --out <file> [--start-in <secs>]`
///
/// Assemble the mainnet manifest from the ceremony's **public halves only**.
///
/// The devnet `genesis` command reads keystores, which is exactly what must
/// never leave the air-gapped machine. This reads the one file the ceremony is
/// designed to carry out: index, public key, RANDAO commitment, and the three
/// columns a human decided. No secret can reach this path because none is in
/// its input.
///
/// The carryover commitment is built from the constants the terminal snapshot
/// pinned, not from the snapshot file: assembling a manifest is a statement
/// about which balance set this chain opens with, and the file itself is
/// checked later, at node start, against exactly these four fields.
fn genesis_mainnet(args: &[String]) {
    use bloch_pos_committee::tokenomics_v4 as t;

    let Some(cohort_path) = arg_value(args, "--cohort") else {
        eprintln!("genesis-mainnet: --cohort <cohort.tsv> is required");
        exit(2);
    };
    let Some(out) = arg_value(args, "--out") else {
        eprintln!("genesis-mainnet: --out <file> is required");
        exit(2);
    };
    let start_in: u64 = arg_value(args, "--start-in")
        .and_then(|s| s.parse().ok())
        .unwrap_or(900);

    let text = match std::fs::read_to_string(&cohort_path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("genesis-mainnet: cannot read {cohort_path}: {e}");
            exit(1);
        }
    };

    let hex = |s: &str, what: &str, row: usize| -> Vec<u8> {
        if s.len() % 2 != 0 || !s.bytes().all(|b| b.is_ascii_hexdigit()) {
            eprintln!("genesis-mainnet: row {row}: {what} is not hex");
            exit(1);
        }
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    };

    let mut validators = Vec::new();
    for (n, line) in text.lines().enumerate().skip(1) {
        if line.trim().is_empty() {
            continue;
        }
        let c: Vec<&str> = line.split('\t').collect();
        if c.len() < 6 {
            eprintln!(
                "genesis-mainnet: row {n}: expected 6 columns, found {}",
                c.len()
            );
            exit(1);
        }
        // Every field is refused rather than defaulted. A validator set is the
        // one artifact nobody can correct later — once a chain runs from it,
        // whatever it said is what happened.
        let bad = |what: &str| -> ! {
            eprintln!("genesis-mainnet: row {n}: {what}");
            exit(1)
        };
        let index: u32 = c[0]
            .trim()
            .parse()
            .unwrap_or_else(|_| bad("index is not a number"));
        let pubkey = hex(c[1].trim(), "pubkey", n);
        let randao = hex(c[2].trim(), "randao_commitment", n);
        if randao.len() != 32 {
            bad("randao_commitment is not 32 bytes");
        }
        let stake_sat: u128 = c[3].trim().parse().unwrap_or_else(|_| bad("stake_sat is empty or not a number — it is a decision, and the ceremony leaves it blank on purpose"));
        if stake_sat < t::SAT_PER_BLOCH * 25_000 {
            bad("stake_sat is below the 25,000 BLOCH minimum deposit");
        }
        let wc = hex(c[4].trim(), "withdrawal_credentials", n);
        if wc.len() != 32 {
            bad("withdrawal_credentials is not 32 bytes");
        }
        let commission_bps: u128 = c[5]
            .trim()
            .parse()
            .unwrap_or_else(|_| bad("commission_bps is empty or not a number"));

        let mut rc = [0u8; 32];
        rc.copy_from_slice(&randao);
        validators.push(genesis::ManifestValidator {
            index,
            stake_sat,
            randao_commitment: rc,
            pubkey,
            withdrawal_credentials: wc,
            commission_bps,
        });
    }
    if validators.is_empty() {
        eprintln!("genesis-mainnet: cohort has no validators");
        exit(1);
    }

    // The five vested buckets, from the constants. Script hashes are the
    // founder's carryover address under the same zero-extension rule the
    // carryover uses — one ownership convention on the chain, not two.
    let alloc = |purpose: u8, bloch: u128, unlock_epoch: u64| genesis::GenesisAllocation {
        purpose,
        script_hash: {
            let mut h = [0u8; 32];
            h[..20].copy_from_slice(&t::FOUNDER_WITHDRAWAL_H160);
            h
        },
        amount_sat: bloch * t::SAT_PER_BLOCH,
        unlock_epoch,
    };
    use genesis::alloc_purpose as ap;
    let allocations = vec![
        alloc(ap::FOUNDER, t::FOUNDER_BLOCH, 0),
        alloc(ap::VC, t::VC_BLOCH, 0),
        alloc(ap::TEAM, t::TEAM_BLOCH, 0),
        alloc(ap::MARKETING, t::MARKETING_BLOCH, 0),
        alloc(ap::LIQUIDITY, t::LIQUIDITY_BLOCH, 0),
    ];

    let cohort: Vec<u32> = validators.iter().map(|v| v.index).collect();
    let manifest = genesis::Manifest {
        genesis_time_ms: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64
            + start_in * 1000,
        slot_ms: 30_000,
        validators,
        cohort,
        // The entries are NOT here, and that is the design: they are ingested
        // at node start from the snapshot file and checked against the four
        // fields below. A manifest is the artifact every node hashes to decide
        // which network it joined; a 54 MB balance set does not belong in it.
        carryover_entries: Vec::new(),
        carryover: Some(genesis::CarryoverCommitment {
            digest: t::CARRYOVER_MEASURED_FILE_SHA3_256,
            set_root: t::CARRYOVER_MEASURED_ROOT,
            entry_count: t::CARRYOVER_MEASURED_UTXOS,
            total_sat: t::CARRYOVER_TOTAL_BLOCH * t::SAT_PER_BLOCH,
        }),
        allocations,
    };

    // The check that makes this a claim rather than an assertion.
    if let Err(e) = manifest.check_supply() {
        eprintln!("genesis-mainnet: {e}");
        exit(1);
    }

    let bytes = manifest.encode();
    if let Err(e) = std::fs::write(&out, &bytes) {
        eprintln!("genesis-mainnet: cannot write {out}: {e}");
        exit(1);
    }
    use sha3::{Digest, Sha3_256};
    let digest: [u8; 32] = Sha3_256::digest(&bytes).into();
    println!(
        "wrote {out}\n  validators : {}\n  carryover  : {} BLOCH ({} outputs)\n  allocations: {} buckets\n  issues     : {} BLOCH at genesis\n  digest     : {}",
        manifest.validators.len(),
        t::CARRYOVER_TOTAL_BLOCH,
        t::CARRYOVER_MEASURED_UTXOS,
        manifest.allocations.len(),
        manifest.genesis_issued_sat() / t::SAT_PER_BLOCH,
        hex_lower(&digest),
    );
}

fn genesis_cmd(args: &[String]) {
    let Some(keys_csv) = arg_value(args, "--keys") else {
        eprintln!("genesis: --keys <dir1,dir2,...> is required");
        exit(2);
    };
    let Some(out) = arg_value(args, "--out") else {
        eprintln!("genesis: --out <file> is required");
        exit(2);
    };
    let slot_ms: u64 = arg_value(args, "--slot-ms")
        .and_then(|s| s.parse().ok())
        .unwrap_or(SLOT_DURATION_SECS * 1000);
    let start_in: u64 = arg_value(args, "--start-in")
        .and_then(|s| s.parse().ok())
        .unwrap_or(5);

    let mut validators = Vec::new();
    for (i, dir) in keys_csv.split(',').enumerate() {
        let ks = match keys::Keystore::load(&PathBuf::from(dir)) {
            Ok(k) => k,
            Err(e) => {
                eprintln!("genesis: cannot load keystore {dir}: {e}");
                exit(1);
            }
        };
        if ks.index != i as u32 {
            eprintln!(
                "genesis: keystore {dir} carries index {} but sits at position {i}; \
                 indexes must be dense from 0 in --keys order",
                ks.index
            );
            exit(1);
        }
        // Uneven stakes (1x/2x/3x of 200k BLCH) so stake weighting is
        // load-bearing in every devnet run — same pattern the e2e test uses.
        let stake_sat: u128 = (i as u128 % 3 + 1) * 200_000 * SAT_PER_BLOCH;
        validators.push(genesis::ManifestValidator {
            index: ks.index,
            stake_sat,
            randao_commitment: bloch_pos_committee::beacon::RandaoChain::generate(ks.randao_seed)
                .commitment(),
            pubkey: ks.pubkey.clone(),
            withdrawal_credentials: Vec::new(),
            // Devnet: no delegation, so the rate is committed as zero. It is
            // written here rather than defaulted, because the day a devnet
            // grows delegators this line is where someone must choose.
            commission_bps: 0,
        });
    }
    let manifest = genesis::Manifest {
        genesis_time_ms: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64
            + start_in * 1000,
        slot_ms,
        validators,
        cohort: Vec::new(),
        // `genesis` builds devnet manifests: no carried balances, no vested
        // allocations. The mainnet manifest is assembled by a separate path
        // that takes the signed Genesis-3 snapshot as input, because its
        // inputs come from a ceremony and not from a command line.
        carryover: None,
        allocations: Vec::new(),
        carryover_entries: Vec::new(),
    };
    if let Err(e) = manifest.check_supply() {
        eprintln!("genesis: {e}");
        exit(1);
    }
    let bytes = manifest.encode();
    if let Err(e) = std::fs::write(&out, &bytes) {
        eprintln!("genesis: cannot write {out}: {e}");
        exit(1);
    }
    use sha3::{Digest, Sha3_256};
    let digest: [u8; 32] = Sha3_256::digest(&bytes).into();
    println!(
        "wrote {out}: {} validators, slot {} ms, genesis block {}, digest {}",
        manifest.validators.len(),
        slot_ms,
        codec::hex8(manifest.genesis_id().as_bytes()),
        codec::hex32(&digest)
    );
}

fn run_cmd(args: &[String]) {
    self_check();
    let (Some(data_dir), Some(genesis_path)) =
        (arg_value(args, "--data-dir"), arg_value(args, "--genesis"))
    else {
        eprintln!("run: --data-dir and --genesis are required");
        exit(2);
    };
    // Devnet stays the default. The 64-validator devnet finalized on that
    // transport, and the same command must keep producing the same run;
    // opting into the production stack is an explicit act.
    let transport = match arg_value(args, "--transport").as_deref() {
        None | Some("devnet") => engine::Transport::Devnet,
        Some("libp2p") => engine::Transport::Libp2p,
        Some(other) => {
            eprintln!("run: --transport must be `devnet` or `libp2p`, not `{other}`");
            exit(2);
        }
    };
    let listen = arg_value(args, "--listen").and_then(|s| s.parse::<u16>().ok());
    if transport == engine::Transport::Devnet && listen.is_none() {
        eprintln!("run: --listen <port> is required for the devnet transport");
        exit(2);
    }
    let csv = |name: &str| -> Vec<String> {
        arg_value(args, name)
            .map(|s| {
                s.split(',')
                    .filter(|p| !p.is_empty())
                    .map(String::from)
                    .collect()
            })
            .unwrap_or_default()
    };
    let mut p2p_listen = csv("--p2p-listen");
    if transport == engine::Transport::Libp2p && p2p_listen.is_empty() {
        p2p_listen.push("/ip4/0.0.0.0/tcp/16400".to_string());
    }
    let stop_at_slot = arg_value(args, "--stop-at-slot").and_then(|s| s.parse::<u64>().ok());

    let ws = ws_boot::WsConfig {
        checkpoint: arg_value(args, "--ws-checkpoint").map(PathBuf::from),
        signer_set: arg_value(args, "--ws-signer-set").map(PathBuf::from),
    };

    // RPC. A malformed --rpc-port is refused rather than silently falling back
    // to the default: an operator who typed a port meant that port, and a node
    // listening somewhere else is worse than one that did not start.
    let rpc_port = match arg_value(args, "--rpc-port") {
        None => Some(DEFAULT_RPC_PORT),
        Some(s) if s == "off" || s == "0" => None,
        Some(s) => match s.parse::<u16>() {
            Ok(p) => Some(p),
            Err(_) => {
                eprintln!("run: --rpc-port must be a port number 1-65535, or `off` (got `{s}`)");
                exit(2);
            }
        },
    };

    let cfg = engine::Config {
        data_dir: PathBuf::from(data_dir),
        genesis_path: PathBuf::from(genesis_path),
        transport,
        listen: listen.unwrap_or(0),
        // Loopback unless asked otherwise: the devnet transport authenticates
        // nothing, so a routable bind is a deliberate act plus a firewall.
        listen_addr: arg_value(args, "--listen-addr").unwrap_or_else(|| "127.0.0.1".to_string()),
        peers: csv("--peers"),
        p2p_listen,
        p2p_peers: csv("--p2p-peer"),
        max_peers: arg_value(args, "--max-peers")
            .and_then(|s| s.parse().ok())
            .unwrap_or(64),
        behind_proxy: args.iter().any(|a| a == "--behind-proxy"),
        stop_at_slot,
        ws,
        // Required exactly when the manifest commits to a carryover; `run`
        // refuses both mismatches rather than defaulting either way.
        carryover_path: arg_value(args, "--carryover").map(PathBuf::from),
        // Loopback unless asked otherwise, for the same reason as the mesh
        // listener and one more: the RPC accepts `sendrawtransaction`, so an
        // exposed port is a write surface, not only a read one.
        rpc_bind: arg_value(args, "--rpc-bind").unwrap_or_else(|| "127.0.0.1".to_string()),
        rpc_port,
        accept_new_signing_history: args.iter().any(|a| a == "--accept-new-signing-history"),
    };
    if let Err(e) = engine::run(cfg) {
        eprintln!("bloch-pos: {e}");
        exit(1);
    }
}

/// Sanity over the constants this binary stakes consensus on. Each assert
/// names the document that makes it an invariant.
fn self_check() {
    // §6.1 of the migration design: every hash use tagged, no two tags equal.
    let tags: [(&str, [u8; 16]); 10] = [
        ("DS_BLOCK", DS_BLOCK),
        ("DS_BODY", DS_BODY),
        ("DS_STATE", DS_STATE),
        ("DS_ATTEST", DS_ATTEST),
        ("DS_RANDAO", DS_RANDAO),
        ("DS_SORTITION", DS_SORTITION),
        ("DS_DEPOSIT", DS_DEPOSIT),
        ("DS_SLASH", DS_SLASH),
        ("DS_PROPOSE", DS_PROPOSE),
        ("DS_EXIT", DS_EXIT),
    ];
    for (i, (na, ta)) in tags.iter().enumerate() {
        assert!(
            ta.starts_with(b"BLCH4:"),
            "{na}: domain tag outside the BLCH4 namespace"
        );
        for (nb, tb) in tags.iter().skip(i + 1) {
            assert_ne!(ta, tb, "domain tags {na} and {nb} collide");
        }
    }

    // BLOCH-TOKENOMICS-V4 §8.1, both directions, as the crate pins them.
    //
    // This check used to read `TOTAL_SUPPLY_SAT < u64::MAX / 4` with the
    // comment "21 B at 8 decimals sits far below u64 wrap". That was a
    // restated number, and the 2026-08-12 pure ×100/21 split moved the supply
    // to 100 B — deliberately past u64's halfway point, with the headroom
    // loss accepted and pinned in `tokenomics_v4.rs`. The stale bound then
    // panicked on every `bloch-pos run` and `selfcheck`. Assert the invariant
    // the authority states, never a threshold chosen here: a single balance
    // must still fit the committed u64 columns, and the supply being past the
    // halfway point is what forces every satoshi *sum* to be u128.
    assert!(
        TOTAL_SUPPLY_SAT <= u64::MAX as u128,
        "a single balance no longer fits the u64 columns the state root commits"
    );
    assert!(
        TOTAL_SUPPLY_SAT * 2 > u64::MAX as u128,
        "supply left the u64 wrap zone — re-decide the accumulator widths on purpose"
    );
    // §1: validators get more than any single insider bucket. Compared
    // against the buckets themselves, so a re-split cannot make this pass by
    // arithmetic drift.
    assert!(
        VALIDATOR_EMISSION_BLOCH > FOUNDER_BLOCH
            && VALIDATOR_EMISSION_BLOCH > VC_BLOCH
            && VALIDATOR_EMISSION_BLOCH > TEAM_BLOCH,
        "validator allocation fell below an insider bucket"
    );

    // BLOCH-TOKENOMICS-V4 §3.3.1: cohort cap 100% → 33.33%, held after.
    assert_eq!(cohort_cap_bps(0), COHORT_CAP_START_BPS);
    assert_eq!(cohort_cap_bps(COHORT_TAPER_EPOCHS), COHORT_CAP_FLOOR_BPS);
    assert_eq!(
        cohort_cap_bps(10 * COHORT_TAPER_EPOCHS),
        COHORT_CAP_FLOOR_BPS
    );

    // Migration design §5.1: the slot cadence everything descends from.
    assert_eq!(SLOT_DURATION_SECS, 30);
    assert_eq!(SLOTS_PER_EPOCH, 32);
}
