// SPDX-License-Identifier: AGPL-3.0-or-later

//! # bloch-pos — the Genesis-4 node binary (devnet stage, M1/M2)
//!
//! From the skeleton this grew into a node that actually runs: a devnet of N
//! validator processes produces blocks, attests, justifies and finalizes over
//! a local TCP mesh, with real ML-DSA-65 ‖ Falcon-1024 hybrid signatures and
//! append-only block-log persistence (restart = deterministic replay).
//!
//! What it is NOT yet — honestly, per the integration plan
//! (`docs/specs/BLOCH-POS-NODE-INTEGRATION.md`): no RocksDB store, no libp2p
//! gossip, no transactions (deposits/exits/transfers), no slashing-evidence
//! pipeline, no weak-subjectivity sync, no RPC, no fork choice beyond a
//! linear chain, no mainnet genesis manifest. See the module docs of
//! `engine`, `net`, `store` for each limitation at its site.
//!
//! ## Key hygiene
//!
//! `keygen` produces **throwaway devnet keys only** (never printed, 0600
//! files). Production keys are generated by a human on an air-gapped machine
//! per BLOCH-GENESIS-KEYS.md rule zero — never by this tool in an observable
//! session.
//!
//! ## Ownership
//!
//! `main.rs` is the composition root (PMO change-controlled; §9.4 two-reviewer
//! rule once integration review starts).

mod codec;
mod engine;
mod genesis;
mod keys;
mod net;
mod store;

use std::path::PathBuf;
use std::process::exit;

use bloch_pos_committee::genesis_cohort::{
    cohort_cap_bps, COHORT_CAP_FLOOR_BPS, COHORT_CAP_START_BPS, COHORT_TAPER_EPOCHS,
};
use bloch_pos_committee::params::{
    DS_ATTEST, DS_BLOCK, DS_BODY, DS_DEPOSIT, DS_EXIT, DS_PROPOSE, DS_RANDAO, DS_SLASH,
    DS_SORTITION, DS_STATE, SLOTS_PER_EPOCH, SLOT_DURATION_SECS,
};
use bloch_pos_committee::tokenomics_v4::{SAT_PER_BLOCH, TOTAL_SUPPLY_SAT, VALIDATOR_EMISSION_BLOCH};

const NAME: &str = env!("CARGO_PKG_NAME");
/// `pkg-version (git-commit[+dirty])`, stamped by build.rs. The commit is the
/// load-bearing part: the G8 release-integrity gate compares fleet, release
/// and source through it (deploy/RELEASE-INTEGRITY.md). Never fall back to
/// bare CARGO_PKG_VERSION — three identical "0.3.0-genesis2" strings on three
/// different binaries is the exact failure this replaces.
const VERSION: &str = env!("BLOCH_BUILD_VERSION");

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("--version") | Some("-V") => {
            println!(
                "{NAME} {VERSION} (Genesis-4, block version {:#010x})",
                bloch_pos_committee::header::VERSION_G4
            );
        }
        Some("--help") | Some("-h") | None => print_help(),
        Some("selfcheck") => {
            self_check();
            println!("self-check passed");
        }
        Some("keygen") => keygen(&args[1..]),
        Some("genesis") => genesis_cmd(&args[1..]),
        Some("run") => run_cmd(&args[1..]),
        Some(other) => {
            eprintln!("{NAME}: unknown command `{other}` (see --help)");
            exit(2);
        }
    }
}

fn print_help() {
    println!(
        "{NAME} {VERSION} — Bloch Genesis-4 Proof-of-Stake node (devnet stage)\n\
         \n\
         USAGE:\n\
           bloch-pos selfcheck\n\
               Verify the frozen consensus parameters this binary links.\n\
           bloch-pos keygen --dir <dir> --index <i>\n\
               Generate a THROWAWAY devnet validator keystore (hybrid\n\
               ML-DSA-65‖Falcon-1024 + RANDAO seed) at <dir>/validator.key.\n\
               Devnet only; production keys follow BLOCH-GENESIS-KEYS.md.\n\
           bloch-pos genesis --keys <dir1,dir2,...> --out <file>\n\
                             [--slot-ms <ms>] [--start-in <secs>]\n\
               Build a devnet genesis manifest from the keystores' public\n\
               parts. Slot 0 starts <secs> from now (default 5).\n\
           bloch-pos run --data-dir <dir> --genesis <file> --listen <port>\n\
                         --peers <host:port,...> [--stop-at-slot <n>]\n\
               Run a validator node. <dir> must hold validator.key; chain\n\
               data persists in <dir> and is replayed on restart.\n\
         \n\
         The integration plan is docs/specs/BLOCH-POS-NODE-INTEGRATION.md."
    );
}

fn arg_value(args: &[String], name: &str) -> Option<String> {
    args.iter().position(|a| a == name).and_then(|i| args.get(i + 1)).cloned()
}

fn keygen(args: &[String]) {
    let Some(dir) = arg_value(args, "--dir") else {
        eprintln!("keygen: --dir is required");
        exit(2);
    };
    let Some(index) = arg_value(args, "--index").and_then(|s| s.parse::<u32>().ok()) else {
        eprintln!("keygen: --index <u32> is required");
        exit(2);
    };
    match keys::Keystore::generate(&PathBuf::from(&dir), index) {
        Ok(ks) => {
            use sha3::{Digest, Sha3_256};
            let pkh: [u8; 32] = Sha3_256::digest(&ks.pubkey).into();
            // Public information only — never a secret byte.
            println!(
                "wrote {dir}/validator.key (devnet, throwaway): validator {index}, \
                 pubkey sha3 {}, randao commitment {}",
                codec::hex8(&pkh),
                codec::hex8(&bloch_pos_committee::beacon::RandaoChain::generate(ks.randao_seed)
                    .commitment())
            );
        }
        Err(e) => {
            eprintln!("keygen failed: {e}");
            exit(1);
        }
    }
}

fn genesis_cmd(args: &[String]) {
    let Some(keys_csv) = arg_value(args, "--keys") else {
        eprintln!("genesis: --keys <dir1,dir2,...> is required");
        exit(2);
    };
    let Some(out) = arg_value(args, "--out") else {
        eprintln!("genesis: --out <file> is required");
        exit(2);
    };
    let slot_ms: u64 =
        arg_value(args, "--slot-ms").and_then(|s| s.parse().ok()).unwrap_or(SLOT_DURATION_SECS * 1000);
    let start_in: u64 = arg_value(args, "--start-in").and_then(|s| s.parse().ok()).unwrap_or(5);

    let mut validators = Vec::new();
    for (i, dir) in keys_csv.split(',').enumerate() {
        let ks = match keys::Keystore::load(&PathBuf::from(dir)) {
            Ok(k) => k,
            Err(e) => {
                eprintln!("genesis: cannot load keystore {dir}: {e}");
                exit(1);
            }
        };
        if ks.index != i as u32 {
            eprintln!(
                "genesis: keystore {dir} carries index {} but sits at position {i}; \
                 indexes must be dense from 0 in --keys order",
                ks.index
            );
            exit(1);
        }
        // Uneven stakes (1x/2x/3x of 200k BLCH) so stake weighting is
        // load-bearing in every devnet run — same pattern the e2e test uses.
        let stake_sat: u128 = (i as u128 % 3 + 1) * 200_000 * SAT_PER_BLOCH;
        validators.push(genesis::ManifestValidator {
            index: ks.index,
            stake_sat,
            randao_commitment: bloch_pos_committee::beacon::RandaoChain::generate(ks.randao_seed)
                .commitment(),
            pubkey: ks.pubkey.clone(),
            withdrawal_credentials: Vec::new(),
        });
    }
    let manifest = genesis::Manifest {
        genesis_time_ms: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_millis() as u64
            + start_in * 1000,
        slot_ms,
        validators,
        cohort: Vec::new(),
    };
    let bytes = manifest.encode();
    if let Err(e) = std::fs::write(&out, &bytes) {
        eprintln!("genesis: cannot write {out}: {e}");
        exit(1);
    }
    use sha3::{Digest, Sha3_256};
    let digest: [u8; 32] = Sha3_256::digest(&bytes).into();
    println!(
        "wrote {out}: {} validators, slot {} ms, genesis block {}, digest {}",
        manifest.validators.len(),
        slot_ms,
        codec::hex8(manifest.genesis_id().as_bytes()),
        codec::hex32(&digest)
    );
}

fn run_cmd(args: &[String]) {
    self_check();
    let (Some(data_dir), Some(genesis_path), Some(listen)) = (
        arg_value(args, "--data-dir"),
        arg_value(args, "--genesis"),
        arg_value(args, "--listen").and_then(|s| s.parse::<u16>().ok()),
    ) else {
        eprintln!("run: --data-dir, --genesis and --listen <port> are required");
        exit(2);
    };
    let peers: Vec<String> = arg_value(args, "--peers")
        .map(|s| s.split(',').filter(|p| !p.is_empty()).map(String::from).collect())
        .unwrap_or_default();
    let stop_at_slot = arg_value(args, "--stop-at-slot").and_then(|s| s.parse::<u64>().ok());

    let cfg = engine::Config {
        data_dir: PathBuf::from(data_dir),
        genesis_path: PathBuf::from(genesis_path),
        listen,
        peers,
        stop_at_slot,
    };
    if let Err(e) = engine::run(cfg) {
        eprintln!("bloch-pos: {e}");
        exit(1);
    }
}

/// Sanity over the constants this binary stakes consensus on. Each assert
/// names the document that makes it an invariant.
fn self_check() {
    // §6.1 of the migration design: every hash use tagged, no two tags equal.
    let tags: [(&str, [u8; 16]); 10] = [
        ("DS_BLOCK", DS_BLOCK),
        ("DS_BODY", DS_BODY),
        ("DS_STATE", DS_STATE),
        ("DS_ATTEST", DS_ATTEST),
        ("DS_RANDAO", DS_RANDAO),
        ("DS_SORTITION", DS_SORTITION),
        ("DS_DEPOSIT", DS_DEPOSIT),
        ("DS_SLASH", DS_SLASH),
        ("DS_PROPOSE", DS_PROPOSE),
        ("DS_EXIT", DS_EXIT),
    ];
    for (i, (na, ta)) in tags.iter().enumerate() {
        assert!(ta.starts_with(b"BLCH4:"), "{na}: domain tag outside the BLCH4 namespace");
        for (nb, tb) in tags.iter().skip(i + 1) {
            assert_ne!(ta, tb, "domain tags {na} and {nb} collide");
        }
    }

    // BLOCH-TOKENOMICS-V4 §8.1: 21 B at 8 decimals sits far below u64 wrap.
    assert!(
        TOTAL_SUPPLY_SAT < (u64::MAX as u128) / 4,
        "total supply left the u64 headroom the V4 decision bought"
    );
    // §1: validators get more than any single insider bucket.
    assert!(VALIDATOR_EMISSION_BLOCH > 9_000_000_000, "validator allocation shrank");

    // BLOCH-TOKENOMICS-V4 §3.3.1: cohort cap 100% → 33.33%, held after.
    assert_eq!(cohort_cap_bps(0), COHORT_CAP_START_BPS);
    assert_eq!(cohort_cap_bps(COHORT_TAPER_EPOCHS), COHORT_CAP_FLOOR_BPS);
    assert_eq!(cohort_cap_bps(10 * COHORT_TAPER_EPOCHS), COHORT_CAP_FLOOR_BPS);

    // Migration design §5.1: the slot cadence everything descends from.
    assert_eq!(SLOT_DURATION_SECS, 30);
    assert_eq!(SLOTS_PER_EPOCH, 32);
}
