// SPDX-License-Identifier: AGPL-3.0-or-later

//! Exact non-source environment inputs to the build identity.

/// Build knobs whose values can change generated machine code without changing
/// the source tree. Values are hashed, never published verbatim. Prefixes cover
/// Cargo's target/profile-specific forms and the C toolchain used by PQClean.
pub(crate) const FIXED_BUILD_ENV: &[&str] = &[
    "AR",
    "ARFLAGS",
    "BINDGEN_EXTRA_CLANG_ARGS",
    "CARGO",
    "CARGO_BUILD_RUSTC",
    "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER",
    "CARGO_BUILD_RUSTC_WRAPPER",
    "CARGO_BUILD_RUSTFLAGS",
    "CARGO_BUILD_TARGET",
    "CARGO_ENCODED_RUSTFLAGS",
    "CARGO_INCREMENTAL",
    "CC",
    "CC_FORCE_DISABLE",
    "CC_KNOWN_WRAPPER_CUSTOM",
    "CC_SHELL_ESCAPED_FLAGS",
    "CFLAGS",
    "COMPILER_PATH",
    "CPATH",
    "CPLUS_INCLUDE_PATH",
    "CPPFLAGS",
    "CRATE_CC_NO_DEFAULTS",
    "CXXSTDLIB",
    "C_INCLUDE_PATH",
    "DEBUG",
    "DEP_WASM32_UNKNOWN_UNKNOWN_OPENBSD_LIBC_INCLUDE",
    "DYLD_FALLBACK_FRAMEWORK_PATH",
    "DYLD_FALLBACK_LIBRARY_PATH",
    "DYLD_FRAMEWORK_PATH",
    "DYLD_IMAGE_SUFFIX",
    "DYLD_INSERT_LIBRARIES",
    "DYLD_LIBRARY_PATH",
    "DYLD_ROOT_PATH",
    "DYLD_VERSIONED_FRAMEWORK_PATH",
    "DYLD_VERSIONED_LIBRARY_PATH",
    "GCC_EXEC_PREFIX",
    "HOST_AR",
    "HOST_ARFLAGS",
    "HOST_CC",
    "HOST_CFLAGS",
    "HOST_CPPFLAGS",
    "HOST_CXX",
    "HOST_CXXFLAGS",
    "HOST_CXXSTDLIB",
    "HOST_RANLIB",
    "HOST_RANLIBFLAGS",
    "LD_AUDIT",
    "LD_LIBRARY_PATH",
    "LD_PRELOAD",
    "LIBRARY_PATH",
    "MACOSX_DEPLOYMENT_TARGET",
    "OBJC_INCLUDE_PATH",
    "OPT_LEVEL",
    "RANLIB",
    "RANLIBFLAGS",
    "RUSTC",
    "RUSTC_BOOTSTRAP",
    "RUSTC_LINKER",
    "RUSTC_WORKSPACE_WRAPPER",
    "RUSTC_WRAPPER",
    "RUSTFLAGS",
    "SDKROOT",
    "SOURCE_DATE_EPOCH",
    "TARGET_AR",
    "TARGET_ARFLAGS",
    "TARGET_CC",
    "TARGET_CFLAGS",
    "TARGET_CPPFLAGS",
    "TARGET_CXX",
    "TARGET_CXXFLAGS",
    "TARGET_CXXSTDLIB",
    "TARGET_RANLIB",
    "TARGET_RANLIBFLAGS",
    "WASI_SDK_DIR",
    "ZERO_AR_DATE",
];
