[package]
name = "rv32-hybrid-verify"
version = "0.1.0"
edition = "2021"
[workspace]
[dependencies]
fips204 = { version = "0.4", default-features = false, features = ["ml-dsa-65"] }
tide-fn-dsa-vrfy = { version = "0.4", features = ["no_avx2"] }
[profile.release]
opt-level = 3
panic = "abort"
lto = true
