import {capacityCheck} from './evidence-model.mjs';
export const EVIDENCE_DB='bloch-pay-evidence-v1';
export async function openEvidenceStore(indexed=indexedDB){
  const db=await new Promise((resolve,reject)=>{const request=indexed.open(EVIDENCE_DB,1);request.onupgradeneeded=()=>{request.result.createObjectStore('records',{keyPath:'id'});request.result.createObjectStore('meta');};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Close other Bloch Pay tabs before opening the evidence store.'));});
  db.onversionchange=()=>db.close();
  function snapshot(){return new Promise((resolve,reject)=>{const tx=db.transaction(['records','meta'],'readonly');let records,generation;const a=tx.objectStore('records').getAll(),b=tx.objectStore('meta').get('generation');a.onsuccess=()=>{records=a.result;};b.onsuccess=()=>{generation=b.result??0;};tx.oncomplete=()=>resolve({records,generation});tx.onabort=tx.onerror=()=>reject(tx.error||new Error('Cannot read evidence storage.'));});}
  // All validation/digest work happens before this transaction. The generation
  // check, capacity decision and record mutation commit together across tabs.
  function mutate(expected,transform){return new Promise((resolve,reject)=>{const tx=db.transaction(['records','meta'],'readwrite');let failure,nextGeneration;const store=tx.objectStore('records'),meta=tx.objectStore('meta'),generation=meta.get('generation'),all=store.getAll();let ready=0;const apply=()=>{if(++ready!==2)return;try{const actual=generation.result??0;if(actual!==expected)throw new Error('Evidence changed in another tab. Reload the saved reviews before writing.');if(!Number.isSafeInteger(actual)||actual<0||actual>=Number.MAX_SAFE_INTEGER)throw new Error('Invalid evidence storage generation.');const next=transform(all.result);capacityCheck(next);store.clear();for(const record of next)store.put(record);nextGeneration=actual+1;meta.put(nextGeneration,'generation');}catch(error){failure=error;tx.abort();}};generation.onsuccess=all.onsuccess=apply;tx.oncomplete=()=>resolve(nextGeneration);tx.onabort=tx.onerror=()=>reject(failure||tx.error||new Error('Evidence storage could not be saved.'));});}
  return {snapshot,close:()=>db.close(),
    save:(expected,record,isNew)=>mutate(expected,rows=>{const old=rows.find(r=>r.id===record.id);if(isNew&&old||!isNew&&!old)throw new Error('Evidence record changed. Reload before saving.');if(old&&(record.revision!==old.revision+1||record.packet.dataset_sha256!==old.packet.dataset_sha256||JSON.stringify(record.context)!==JSON.stringify(old.context)))throw new Error('A saved source packet or association cannot be replaced. Start a new review.');return old?rows.map(r=>r.id===record.id?record:r):[...rows,record];}),
    replace:(expected,records)=>mutate(expected,()=>records),
    remove:(expected,id)=>mutate(expected,rows=>{if(!rows.some(r=>r.id===id))throw new Error('This review is no longer saved.');return rows.filter(r=>r.id!==id);})};
}
