import {RAILS,ROLES,buildRoute,applySampleEvent} from './integrations.mjs';
const form=document.querySelector('#route-form'),result=document.querySelector('#route-result');
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let draft=null,sample=null;
const currencies=['BRL','EUR','USD','GBP','CHF','CAD','AUD','MXN','JPY'];
for(const side of ['source','destination']){
  form.elements[side+'Role'].innerHTML=Object.entries(ROLES).map(([key,label])=>`<option value="${key}">${label}</option>`).join('');
  form.elements[side+'Rail'].innerHTML=Object.entries(RAILS).map(([key,rail])=>`<option value="${key}">${rail.name}</option>`).join('');
  form.elements[side+'Currency'].innerHTML=[...currencies,'BLCH'].map(value=>`<option>${value}</option>`).join('');
  form.elements[side+'Rail'].addEventListener('change',()=>sync(side));
}
form.elements.destinationRail.value='sepa';
function sync(side){const rail=RAILS[form.elements[side+'Rail'].value];form.elements[side+'Currency'].disabled=!!rail.currency;if(rail.currency)form.elements[side+'Currency'].value=rail.currency;else if(form.elements[side+'Currency'].value==='BLCH')form.elements[side+'Currency'].value='USD';form.querySelector('.'+side+'-custom').hidden=!!rail.currency;form.elements[side+'Custom'].required=!rail.currency;}
sync('source');sync('destination');
function displayMinor(value,decimals){if(value===null)return 'Awaiting partner terms';const padded=value.padStart(decimals+1,'0');return decimals?padded.slice(0,-decimals)+'.'+padded.slice(-decimals):padded;}
function renderSample(){document.querySelector('#sample-status').textContent=sample.sample_state||'draft';document.querySelector('#sample-events').innerHTML=(sample.events||[]).map(event=>`<li>${e(event.type)} · ${e(event.id)} · sample only</li>`).join('');document.querySelector('#sample-json').textContent=JSON.stringify(sample,null,2);}
function render(){
  result.hidden=false;
  result.innerHTML=`<div class="route-title"><h3>${e(RAILS[draft.source.rail].name)} → ${e(RAILS[draft.destination.rail].name)}</h3><span class="tag">DRAFT · NOT CONNECTED</span></div><p class="small">${e(draft.payment_reference)} · ${e(draft.id)}</p><div class="route-summary">${['source','destination'].map(side=>{const leg=draft[side];return `<div><span class="eyebrow">${side==='source'?'ORIGIN / DEBIT':'DESTINATION / EXPECTED CREDIT'}</span><strong>${e(displayMinor(side==='source'?leg.amount_minor:leg.expected_amount_minor,leg.decimals))} ${leg.currency}</strong><p>${e(leg.partner_reference)} · ${e(ROLES[leg.partner_role])}</p><small>${e(RAILS[leg.rail].settlement)}</small></div>`;}).join('')}</div><p class="route-note">Conversion: ${e(draft.conversion.status.replaceAll('_',' '))}. Settlement: not observed. Beneficiary credit: not observed.</p><div class="button-row"><button id="download-route" class="primary">Export integration draft ↓</button></div><details><summary>Inspect the draft contract</summary><pre id="draft-json"></pre></details><div class="simulation"><h3>Try the event lifecycle <span class="badge" id="sample-status">draft</span></h3><p>Local sample events only. No provider is contacted and no payment is executed. Settlement and credit can be followed by a return.</p><div class="button-row">${['accepted','submitted','settled','credited','returned','failed'].map(type=>`<button data-event="${type}">${type[0].toUpperCase()+type.slice(1)}</button>`).join('')}<button id="reset-sample">Reset scenario</button></div><p class="sample-error" id="sample-error" role="alert"></p><ol id="sample-events" class="sample-events"></ol><details><summary>Inspect sample events</summary><pre id="sample-json"></pre></details></div>`;
  document.querySelector('#draft-json').textContent=JSON.stringify(draft,null,2);sample=structuredClone(draft);renderSample();
}
form.addEventListener('submit',event=>{event.preventDefault();try{const fields=Object.fromEntries(new FormData(form));for(const side of ['source','destination'])fields[side+'Currency']=form.elements[side+'Currency'].value;draft=buildRoute(fields);document.querySelector('#route-error').textContent='';render();result.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}catch(error){document.querySelector('#route-error').textContent=error.message;}});
form.addEventListener('input',()=>{if(!result.hidden){result.hidden=true;draft=null;sample=null;}});
form.addEventListener('reset',()=>setTimeout(()=>{form.elements.destinationRail.value='sepa';sync('source');sync('destination');result.hidden=true;draft=null;sample=null;document.querySelector('#route-error').textContent='';},0));
result.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||!draft)return;if(button.dataset.event){try{sample=applySampleEvent(sample,{id:crypto.randomUUID(),type:button.dataset.event});document.querySelector('#sample-error').textContent='';renderSample();}catch(error){document.querySelector('#sample-error').textContent=error.message;}}if(button.id==='reset-sample'){sample=structuredClone(draft);renderSample();document.querySelector('#sample-error').textContent='';}if(button.id==='download-route'){const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`bloch-pay-integration-${draft.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{});
