import {MODULES,ASSETS,PRIVATE_PROFILES,emptyModules,moduleLinks,integrationManifest,fetchRegistry} from './participant-modules.mjs';
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
export function mountParticipantModules(){
  let partners=[],registry=null,checkedAt=null;
  $('partner-module-fields').innerHTML=`<div class="review-intro"><h3>Participant modules</h3><p>Configure tools and requested access. This record does not create a portal account or grant permissions.</p></div><fieldset><legend>Tools to configure</legend><div class="module-checkboxes">${Object.entries(MODULES).map(([key,m])=>`<label class="rail-checkbox"><input type="checkbox" name="module_enabled" value="${key}">${m.name}</label>`).join('')}</div></fieldset><fieldset><legend>Asset scope</legend><div class="module-checkboxes">${ASSETS.map(asset=>`<label class="rail-checkbox"><input type="checkbox" name="module_asset" value="${asset}">${asset}</label>`).join('')}</div></fieldset><label>Purpose<input name="module_purpose" maxlength="240" placeholder="Why this participant needs these tools"></label><label>Private access plan<select name="module_private_profile">${Object.entries(PRIVATE_PROFILES).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label><label>Organization reference · for private access planning<input name="module_organization" maxlength="80" placeholder="Internal reference, never an API key"></label><p class="small">Private keys and membership are managed in BI-PoRB. Do not paste credentials here. Private API integration requires the participant's server and authorized organization principal.</p>`;
  $('participant-modules').innerHTML=`<div class="section-heading"><div><p class="eyebrow">TOOLS / PARTICIPANT SCOPE</p><h2>Connected module workspace</h2></div><button id="refresh-module-registry">Check public capabilities ↻</button></div><p class="section-description">Configure Graphus, Constellation, AML / BI-PoRB and System Map for each participant. Public launchers send the selected asset only. Private access is verified by BI-PoRB after login.</p><p class="small" id="module-registry-status" role="status">Public registry not checked in this session. No background data queries.</p><div class="directory-filters"><label>Participant<select id="module-participant"></select></label><label>Configured asset<select id="module-asset"></select></label></div><div id="module-plan-summary"></div><div class="participant-module-grid" id="participant-module-cards"></div><div class="button-row"><button id="export-module-plan">Export integration manifest ↓</button><button id="configure-participant-modules">Configure participant</button></div><p class="small">These settings express intended use. They do not certify a participant, connect a payment rail, perform sanctions screening or activate a private API.</p>`;
  function renderCards(){
    const partner=partners.find(p=>p.id===$('module-participant').value),plan=partner?.modules||emptyModules(),prior=$('module-asset').value;
    $('module-asset').innerHTML=plan.assets.map(asset=>`<option>${asset}</option>`).join('');if(plan.assets.includes(prior))$('module-asset').value=prior;
    $('export-module-plan').disabled=!partner;$('configure-participant-modules').disabled=!partner;
    $('configure-participant-modules').dataset.editPartner=partner?.id||'';
    $('module-plan-summary').innerHTML=partner?`<p class="module-purpose"><strong>${e(partner.name)}</strong> · ${plan.enabled.length} tools configured<br>${e(plan.purpose||'No module purpose recorded yet.')}<br><small>${e(PRIVATE_PROFILES[plan.private_profile])} · authorization not verified by Bloch Pay</small></p>`:'<div class="empty"><h3>Add a participant to configure modules</h3><p>The public capability registry can be checked without participant data.</p></div>';
    const asset=$('module-asset').value;
    $('participant-module-cards').innerHTML=Object.entries(MODULES).map(([key,m])=>{
      const enabled=plan.enabled.includes(key),nodes=registry?.modules.filter(n=>(!m.ids.length||m.ids.includes(n.id))&&n.assets.includes(asset))||[];
      const states={available:0,prototype:0,design:0};for(const node of nodes)states[node.status]++;
      return `<article class="panel"><div class="panel-heading"><h3>${m.name}</h3><span class="tag">${enabled?'CONFIGURED':'NOT SELECTED'}</span></div><p>${m.description}</p><p class="small">${registry?`${nodes.length} registry modules for ${asset}: ${states.available} available, ${states.prototype} prototypes, ${states.design} planned. Implementation descriptions; current uptime and access are not tested.`:'Implementation status has not been checked in this session.'}</p>${registry&&nodes.length?`<details><summary>Inspect capability states</summary><ul class="module-capabilities">${nodes.map(n=>`<li><strong>${e(n.title)}</strong> · ${e(n.status)} / ${e(n.access)}<p>${e(n.limits)}</p></li>`).join('')}</ul></details>`:''}<div class="module-links">${enabled?moduleLinks(key,asset,plan.private_profile).map(link=>`<a class="inline-link" href="${e(link.href)}" target="_blank" rel="noopener noreferrer">${e(link.label)} ↗</a>`).join(''):'<span class="small">Select this tool in the participant configuration.</span>'}</div></article>`;
    }).join('');
  }
  $('module-participant').addEventListener('change',renderCards);$('module-asset').addEventListener('change',renderCards);
  $('refresh-module-registry').addEventListener('click',async()=>{
    const button=$('refresh-module-registry'),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);button.disabled=true;
    $('module-registry-status').textContent='Reading the public Graphus capability registry…';
    try{registry=await fetchRegistry({signal:controller.signal});checkedAt=new Date().toISOString();$('module-registry-status').textContent=`Graphus registry ${registry.version} · ${registry.modules.length} modules · retrieved ${checkedAt}. Public descriptions only; private access not checked.`;renderCards();}
    catch(error){$('module-registry-status').textContent=`Registry check failed: ${error.name==='AbortError'?'request timed out':error.message}${registry?` Last successful registry retained from ${checkedAt}; it may be out of date.`:' No capabilities were inferred.'}`;}
    finally{clearTimeout(timer);button.disabled=false;}
  });
  $('export-module-plan').addEventListener('click',()=>{const partner=partners.find(p=>p.id===$('module-participant').value);if(!partner)return;const url=URL.createObjectURL(new Blob([JSON.stringify(integrationManifest(partner),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`bloch-pay-modules-${partner.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);});
  return {
    render(items){partners=items;const selected=$('module-participant').value;$('module-participant').innerHTML=partners.length?partners.map(p=>`<option value="${p.id}">${e(p.name)} · ${p.id}</option>`).join(''):'<option value="">No participants</option>';if(partners.some(p=>p.id===selected))$('module-participant').value=selected;renderCards();},
    fillForm(plan=emptyModules()){const f=$('partner-form');for(const input of f.querySelectorAll('[name=module_enabled]'))input.checked=plan.enabled.includes(input.value);for(const input of f.querySelectorAll('[name=module_asset]'))input.checked=plan.assets.includes(input.value);f.elements.module_purpose.value=plan.purpose;f.elements.module_private_profile.value=plan.private_profile;f.elements.module_organization.value=plan.organization_reference;},
    readForm(){const data=new FormData($('partner-form'));return {enabled:data.getAll('module_enabled'),assets:data.getAll('module_asset'),purpose:data.get('module_purpose'),private_profile:data.get('module_private_profile'),organization_reference:data.get('module_organization')};}
  };
}
