import {planningGaps} from './studio-model.mjs';
import {RAILS} from './integrations.mjs';
import {routeRows,actionQueue,networkView,corridorRows,formatMinor,operationsCsv,PRIORITIES} from './operations.mjs';
const $=id=>document.getElementById(id);
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=()=>'<option value="">All rails</option>'+Object.entries(RAILS).map(([key,rail])=>`<option value="${key}">${rail.name}</option>`).join('');
export function mountOperations(){
  let state={partners:[],routes:[]},rows=[],selected=new Set(),focus='',direction='both',zoom=1;
  $('operations').innerHTML=`<div class="section-heading"><div><p class="eyebrow">OPERATIONS / LOCAL PLANNING</p><h2>Review the next connection</h2></div><button id="export-planning-csv">Export filtered routes ↓</button></div><p class="section-description">Find shared documentation gaps and compare saved plans. Filters apply to this review and the connection map. Counts describe active drafts, not executed payments or transaction volume.</p><div class="ops-filters"><label>Participant<select id="ops-participant"></select></label><label>Origin rail<select id="ops-source">${options()}</select></label><label>Destination rail<select id="ops-destination">${options()}</select></label><label>Planning state<select id="ops-review"><option value="">All active drafts</option><option value="gaps">With gaps</option><option value="blocked">Blocked planning items</option><option value="documented">Items documented</option></select></label></div><div class="button-row"><button id="reset-ops">Reset filters</button></div><p class="small" id="ops-count" role="status"></p><div class="ops-grid"><article class="panel"><h3>Shared action queue</h3><p class="small">One item per participant and requirement; route impact counts distinct drafts. Priority reflects recorded planning state, not financial risk.</p><div id="ops-actions"></div></article><article class="panel"><h3>Corridors in scope</h3><div id="ops-corridors"></div></article></div><article class="panel comparison-panel"><div class="panel-heading"><h3>Compare route drafts</h3><button id="clear-comparison">Clear selection</button></div><p class="small">Choose up to three drafts. Selection survives filters. Amounts and gaps do not establish the best route, fees or executable pricing.</p><div id="compare-choices"></div><p class="small" id="compare-notice" role="status"></p><div id="route-comparison"></div></article>`;
  $('corridor-map').innerHTML=`<div class="graph-controls"><label>Find participant<input id="graph-search" type="search" maxlength="120" placeholder="Name or reference"></label><label>Focus participant<select id="graph-focus"></select></label><label>Connections<select id="graph-direction"><option value="both">Incoming + outgoing</option><option value="incoming">Incoming</option><option value="outgoing">Outgoing</option></select></label><label>Zoom<input type="range" id="graph-zoom" min="1" max="4" step="0.25" value="1"></label><button id="graph-reset">Fit / clear focus</button></div><div id="graph-viewport" tabindex="0" aria-label="Scrollable participant graph"><div id="graph-drawing"></div></div><p class="small" id="graph-count" role="status"></p><p class="small">Select a point or use Focus participant to inspect direct connections. Arrows are draft directions. Dashed points have no directory entry. Scroll the enlarged map to pan.</p><div id="graph-inspector"></div>`;
  function filters(){return {participant:$('ops-participant').value,sourceRail:$('ops-source').value,destinationRail:$('ops-destination').value,review:$('ops-review').value};}
  function drawGraph(){
    const all=networkView(state,rows);if(!all.nodes.some(n=>n.id===focus))focus='';
    $('graph-focus').innerHTML='<option value="">All participants</option>'+all.nodes.filter(n=>n.id===focus||`${n.name} ${n.id}`.toLowerCase().includes($('graph-search').value.trim().toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)).map(n=>`<option value="${n.id}">${e(n.name)} · ${n.id}</option>`).join('');$('graph-focus').value=focus;
    const view=networkView(state,rows,focus,direction),n=view.nodes.length;
    const ordered=[...view.nodes].sort((a,b)=>a.id.localeCompare(b.id));
    const positions=new Map(ordered.map((node,index)=>{const angle=n<=24?index*2*Math.PI/Math.max(n,1)-Math.PI/2:index*2.399963229728653;const radius=n<=1?0:n<=24?1:Math.sqrt((index+.5)/n);return[node.id,{...node,x:360+radius*245*Math.cos(angle),y:215+radius*157*Math.sin(angle)}];}));
    const radius=n<=24?16:n<=200?8:4;
    $('graph-drawing').innerHTML=n?`<svg class="participant-network" viewBox="0 0 720 440" role="group" aria-label="${n} participants and ${view.edges.length} directed draft connections"><defs><marker id="ops-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z"/></marker></defs>${view.edges.map(edge=>{const a=positions.get(edge.source),b=positions.get(edge.destination),angle=Math.atan2(b.y-a.y,b.x-a.x);const path=edge.source===edge.destination?`M${a.x-10},${a.y-8}C${a.x-60},${a.y-70} ${a.x+60},${a.y-70} ${a.x+10},${a.y-8}`:`M${a.x+radius*Math.cos(angle)},${a.y+radius*Math.sin(angle)}L${b.x-(radius+5)*Math.cos(angle)},${b.y-(radius+5)*Math.sin(angle)}`;return `<path class="network-edge" d="${path}" marker-end="url(#ops-arrow)"><title>${e(edge.source)} → ${e(edge.destination)}: ${edge.count} drafts</title></path>`;}).join('')}${[...positions.values()].map(node=>`<g role="button" tabindex="0" data-focus-node="${node.id}" aria-label="Focus ${e(node.name)}: ${node.incoming} incoming and ${node.outgoing} outgoing connections"><circle cx="${node.x}" cy="${node.y}" r="${radius}" class="${node.registered?'registered':'unregistered'} ${node.id===focus?'focused':''}"/>${n<=24?`<text x="${node.x}" y="${node.y+33}" text-anchor="middle">${e(node.name.length>19?node.name.slice(0,16)+'…':node.name)}</text>`:''}<title>${e(node.name)} · ${node.id}</title></g>`).join('')}</svg>`:'<p class="small">No active drafts match these filters.</p>';
    $('graph-drawing').style.width=`${zoom*100}%`;
    $('graph-count').textContent=`${n} of ${all.nodes.length} matching participants · ${view.edges.length} connections · ${view.active} drafts · ${Math.round(zoom*100)}% zoom`;
    const node=all.nodes.find(node=>node.id===focus),partner=state.partners.find(p=>p.id===focus);
    $('graph-inspector').innerHTML=node?`<strong>${e(node.name)}</strong><p class="small">${e(node.id)} · ${node.incoming} incoming / ${node.outgoing} outgoing distinct connections in the filtered view.</p>${partner?`<button data-edit-partner="${partner.id}">Review participant</button>`:'<p class="small">No directory entry. Add this reference in the partner directory.</p>'}`:'';
    $('corridor-table').innerHTML=view.edges.length?`<div class="table-wrap"><table><thead><tr><th>Origin reference</th><th>Destination reference</th><th>Drafts</th></tr></thead><tbody>${view.edges.map(edge=>`<tr><td>${e(edge.source)}</td><td>${e(edge.destination)}</td><td>${edge.count}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">No matching connections.</p>';
    const scales={BLCH:8,JPY:0};$('draft-currency-totals').innerHTML=view.currencies.length?`<p class="small">Planned source amounts for the map scope; draft variants count separately.</p><div class="currency-totals">${view.currencies.map(row=>`<div><span>${row.currency}</span><strong>${formatMinor(row.minor,scales[row.currency]??2)}</strong></div>`).join('')}</div>`:'';
  }
  function comparison(){
    const chosen=state.routes.filter(r=>selected.has(r.draft.id));
    $('compare-notice').textContent=`${chosen.length} / 3 selected. ${chosen.filter(r=>!rows.some(row=>row.route.draft.id===r.draft.id)).length} selected drafts outside the current filters.`;
    $('compare-choices').innerHTML=rows.length?`<div class="comparison-choices">${rows.map(({route:r})=>`<label class="rail-checkbox"><input type="checkbox" data-compare="${r.draft.id}" ${selected.has(r.draft.id)?'checked':''}>${e(r.draft.payment_reference)}<small>${e(r.draft.source.partner_reference)} → ${e(r.draft.destination.partner_reference)}</small></label>`).join('')}</div>`:'<p class="small">No active drafts in this scope.</p>';
    const field=(title,fn)=>`<tr><th>${title}</th>${chosen.map(r=>`<td>${e(fn(r))}</td>`).join('')}</tr>`;
    $('route-comparison').innerHTML=chosen.length?`<div class="table-wrap"><table><thead><tr><th>Recorded field</th>${chosen.map(r=>`<th>${e(r.draft.payment_reference)}</th>`).join('')}</tr></thead><tbody>${field('Origin',r=>r.draft.source.partner_reference+' / '+RAILS[r.draft.source.rail].name)}${field('Destination',r=>r.draft.destination.partner_reference+' / '+RAILS[r.draft.destination.rail].name)}${field('Planned debit',r=>formatMinor(r.draft.source.amount_minor,r.draft.source.decimals)+' '+r.draft.source.currency)}${field('Expected credit',r=>(r.draft.destination.expected_amount_minor===null?'Not specified':formatMinor(r.draft.destination.expected_amount_minor,r.draft.destination.decimals)+' '+r.draft.destination.currency))}${field('Quote reference',r=>r.draft.conversion.partner_quote_reference||'Not supplied')}${field('Planning gaps',r=>planningGaps(r.draft,state.partners).length)}${field('Sample scenario',r=>r.events.at(-1)?.type||'draft')}${field('Actual settlement',()=>'Not observed')}${field('Execution',()=>'Disabled')}<tr><th>Open</th>${chosen.map(r=>`<td><button data-open-route="${r.draft.id}">Open draft</button></td>`).join('')}</tr></tbody></table></div>`:'';
  }
  function render(){
    rows=routeRows(state,filters());const actions=actionQueue(state,rows),corridors=corridorRows(rows);
    $('ops-count').textContent=`${rows.length} of ${state.routes.filter(r=>!r.archived).length} active drafts · ${actions.length} shared action items · ${rows.filter(r=>r.blocked).length} drafts with blocked planning items`;
    $('ops-actions').innerHTML=actions.length?`<div class="ops-action-list">${actions.map(a=>`<article><span class="tag ${a.priority==='blocked'?'blocked-tag':''}">${PRIORITIES[a.priority]}</span><h4>${e(a.participant||'Conversion quote')}</h4><p>${e(a.message)}</p><small>Owner: ${e(a.owner)} · ${a.routes.length} affected drafts</small>${a.known?`<button data-edit-partner="${a.participant}">Review participant</button>`:a.code==='quote'?`<button data-open-route="${a.routes[0]}">Review route</button>`:''}</article>`).join('')}</div>`:'<p class="small">No planning gaps in the matching drafts. This does not verify connectivity or eligibility.</p>';
    $('ops-corridors').innerHTML=corridors.length?corridors.map(c=>`<div class="corridor-review"><strong>${e(c.source)} → ${e(c.destination)}</strong><p>${c.currency} → ${c.destinationCurrency} · ${c.count} drafts · ${c.withGaps} with gaps</p><span>${formatMinor(c.amount,c.decimals)} ${c.currency} planned debit</span></div>`).join(''):'<p class="small">Save a route to review a corridor.</p>';
    selected=new Set([...selected].filter(id=>state.routes.some(r=>r.draft.id===id&&!r.archived)));comparison();drawGraph();
  }
  for(const id of ['ops-participant','ops-source','ops-destination','ops-review'])$(id).addEventListener('change',render);
  $('reset-ops').addEventListener('click',()=>{for(const id of ['ops-participant','ops-source','ops-destination','ops-review'])$(id).value='';focus='';render();});
  $('clear-comparison').addEventListener('click',()=>{selected.clear();comparison();});
  $('compare-choices').addEventListener('change',event=>{const input=event.target;if(!input.dataset.compare)return;if(input.checked&&selected.size>=3){input.checked=false;$('compare-notice').textContent='Select at most three drafts. Clear one selection first.';return;}input.checked?selected.add(input.dataset.compare):selected.delete(input.dataset.compare);comparison();});
  $('graph-search').addEventListener('input',drawGraph);
  $('graph-focus').addEventListener('change',event=>{focus=event.target.value;drawGraph();});$('graph-direction').addEventListener('change',event=>{direction=event.target.value;drawGraph();});$('graph-zoom').addEventListener('input',event=>{zoom=Number(event.target.value);drawGraph();});
  $('graph-reset').addEventListener('click',()=>{focus='';direction='both';zoom=1;$('graph-search').value='';$('graph-direction').value='both';$('graph-zoom').value='1';drawGraph();$('graph-viewport').scrollTo(0,0);});
  function selectNode(event){const target=event.target.closest('[data-focus-node]');if(!target)return;if(event.type==='keydown'&&!['Enter',' '].includes(event.key))return;event.preventDefault();focus=target.dataset.focusNode;drawGraph();$('graph-focus').focus();}
  $('graph-drawing').addEventListener('click',selectNode);$('graph-drawing').addEventListener('keydown',selectNode);
  $('export-planning-csv').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([operationsCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='bloch-pay-planning-routes.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);});
  return {render(next){state=next;const prior=$('ops-participant').value,refs=new Map();for(const route of state.routes.filter(r=>!r.archived))for(const leg of [route.draft.source,route.draft.destination]){const id=leg.partner_reference.toLowerCase();refs.set(id,state.partners.find(p=>p.id===id)?.name||id);}$('ops-participant').innerHTML='<option value="">All participants</option>'+[...refs].sort().map(([id,name])=>`<option value="${id}">${e(name)} · ${id}</option>`).join('');if(refs.has(prior))$('ops-participant').value=prior;render();}};
}
