import {mountOperations} from './operations-ui.mjs';
import {mountParticipantModules} from './modules-ui.mjs';
import {RAILS,ROLES} from './integrations.mjs';
import {STUDIO_KEY,STAGES,CHECKS,REVIEW_STATES,emptyStudio,emptyReview,readStudio,saveStudio,validatePartner,planningGaps,studioSummary} from './studio-model.mjs';
const $=selector=>document.querySelector(selector);
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels=map=>Object.entries(map).map(([value,label])=>`<option value="${value}">${e(label)}</option>`).join('');
function download(name,value){const url=URL.createObjectURL(new Blob([value],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export function mountStudio({getDraft,getSample,loadRoute,onReplace=()=>{}}){
  const participantModules=mountParticipantModules(),operations=mountOperations();
  let state=emptyStudio(),serialized=null,corrupt=false,unavailable=false,editing=null,pending=null,toastTimer;
  const notice=message=>{$('#studio-notice').hidden=false;$('#studio-notice').textContent=message;};
  const toast=message=>{clearTimeout(toastTimer);$('#route-toast').textContent=message;$('#route-toast').hidden=false;toastTimer=setTimeout(()=>$('#route-toast').hidden=true,6000);};
  try{serialized=localStorage.getItem(STUDIO_KEY);if(serialized)state=readStudio(serialized);}catch{corrupt=serialized!==null;unavailable=!corrupt;notice(corrupt?'The saved studio could not be read. Export the original backup, then import a valid integration backup to recover. Invoice records are separate.':'Browser storage is unavailable. Enable site storage and reload to save partners or routes.');}
  const blocked=()=>corrupt||unavailable;
  function persist(next){if(unavailable)throw new Error('Browser storage is unavailable.');const saved=saveStudio(localStorage,serialized,next);state=saved.data;serialized=saved.serialized;corrupt=false;$('#studio-notice').hidden=true;render();}
  function confirm(title,message,action){$('#studio-confirm-title').textContent=title;$('#studio-confirm-copy').textContent=message;$('#studio-confirm .form-error').textContent='';pending=action;$('#studio-confirm').showModal();}
  function renderPartners(){
    const query=$('#partner-search').value.trim().toLowerCase(),stage=$('#partner-stage-filter').value;
    const partners=state.partners.filter(p=>(!query||`${p.name} ${p.id} ${p.jurisdiction}`.toLowerCase().includes(query))&&(stage==='all'||p.stage===stage));
    $('#partner-list').innerHTML=partners.length?`<div class="partner-directory-grid">${partners.map(p=>{const count=Object.values(p.review).filter(r=>r.state==='documented').length;return `<article class="panel"><div class="panel-heading"><span class="tag">${e(STAGES[p.stage])}</span><button data-edit-partner="${p.id}" aria-label="Edit ${e(p.name)}">Edit</button></div><h3>${e(p.name)}</h3><p>${e(ROLES[p.role])} · ${e(p.jurisdiction)}<br><span class="partner-id">${e(p.id)}</span></p><div class="rail-chips">${p.rails.map(rail=>`<span>${e(RAILS[rail].name)}</span>`).join('')}</div><p class="review-count">${count} / ${Object.keys(CHECKS).length} planning items documented</p>${p.owner?`<p class="small">Owner: ${e(p.owner)}</p>`:''}</article>`;}).join('')}</div>`:'<div class="empty"><h3>No participants to show</h3><p>Add a bank, VASP/PSAV, PSP or service provider to organize your integration work. Entries describe your planning records.</p></div>';
    $('#partner-count').textContent=`${partners.length} of ${state.partners.length} participants`;
    $('#partner-options').innerHTML=state.partners.map(p=>`<option value="${p.id}">${e(p.name)} · ${e(ROLES[p.role])}</option>`).join('');
  }
  function renderRoutes(){
    const query=$('#route-search').value.toLowerCase().trim(),status=$('#route-status-filter').value;
    const routes=state.routes.filter(r=>(status==='all'||(status==='archived')===r.archived)&&(!query||`${r.draft.payment_reference} ${r.draft.source.partner_reference} ${r.draft.destination.partner_reference}`.toLowerCase().includes(query))).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
    $('#saved-route-list').innerHTML=routes.length?`<div class="table-wrap"><table><thead><tr><th>Draft / participants</th><th>Rails</th><th>Planning</th><th>Saved scenario</th><th>Actions</th></tr></thead><tbody>${routes.map(r=>{const d=r.draft,gaps=planningGaps(d,state.partners);return `<tr><td><strong>${e(d.payment_reference)}</strong><small>${e(d.source.partner_reference)} → ${e(d.destination.partner_reference)}</small><small>${e(r.updated_at.slice(0,16).replace('T',' '))} UTC</small></td><td>${e(RAILS[d.source.rail].name)}<small>→ ${e(RAILS[d.destination.rail].name)}</small></td><td><span class="badge ${gaps.length?'overdue':''}">${r.archived?'Archived':gaps.length?`${gaps.length} gaps`:'Items documented'}</span></td><td>${e(r.events.at(-1)?.type||'draft')}<small>Sample only</small></td><td><div class="row-actions"><button data-open-route="${d.id}">Open</button><a class="inline-link" href="evidence?route=${d.id}&amp;participant=${d.source.partner_reference.toLowerCase()}">Evidence ↗</a><button data-archive-route="${d.id}">${r.archived?'Restore':'Archive'}</button></div></td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty"><h3>No saved routes to show</h3><p>Build an integration draft below, then save it with its local event scenario.</p><a class="inline-link" href="#planner">Go to route planner ↓</a></div>';
    $('#saved-route-count').textContent=`${routes.length} of ${state.routes.length} saved drafts. Editing and rebuilding a loaded draft creates another draft.`;
  }
  function refreshDraft(){
    const draft=getDraft(),target=$('#route-planning-gaps');if(!draft||!target)return;
    const gaps=planningGaps(draft,state.partners),saved=state.routes.find(r=>r.draft.id===draft.id);
    target.innerHTML=`<div class="panel-heading"><h3>Planning review</h3><span class="tag">${gaps.length} ${gaps.length===1?'GAP':'GAPS'}</span></div>${gaps.length?`<ul>${gaps.map(gap=>`<li>${e(gap.message)}</li>`).join('')}</ul>`:'<p>Directory coverage and documentation references are present for the selected legs.</p>'}<p class="small">These checks use your local declarations. They do not verify authorization, connectivity, funding or execution readiness.</p>`;
    const button=$('#save-route');if(button){button.textContent=saved?'Save scenario changes':'Save route + scenario';button.disabled=blocked();}
    const note=$('#saved-route-state');if(note){const changed=saved&&JSON.stringify(saved.events)!==JSON.stringify(getSample()?.events||[]);note.textContent=saved?(changed?'Scenario changes have not been saved.':`Saved locally${saved.archived?' · archived':''} · ${saved.updated_at.slice(0,16).replace('T',' ')} UTC`):'This draft has not been saved.';}
  }
  function render(){
    const summary=studioSummary(state);
    $('#studio-metrics').innerHTML=[['PARTICIPANTS',summary.partners,'Directory entries'],['ACTIVE DRAFTS',summary.active,'Saved route plans'],['WITH PLANNING GAPS',summary.withGaps,'Based on local declarations'],['ARCHIVED',summary.archived,'Retained for reference']].map(([label,value,note])=>`<article class="metric"><span class="metric-label">${label}</span><strong>${value}</strong><small>${note}</small></article>`).join('');
    $('#studio-storage-status').textContent=`Revision ${state.revision} · local browser data`;$('#new-partner').disabled=blocked();renderPartners();renderRoutes();refreshDraft();participantModules.render(state.partners);operations.render(state);
  }
  function partnerEditor(id){
    if(blocked())return toast('Recover browser storage before editing participants.');editing=id||null;const old=state.partners.find(p=>p.id===id),f=$('#partner-form');f.reset();f.querySelector('.form-error').textContent='';$('#partner-dialog-title').textContent=old?'Edit participant':'Add participant';
    const p=old||{id:'',name:'',role:'bank',jurisdiction:'',owner:'',stage:'exploring',rails:[],review:emptyReview(),note:''};
    for(const key of ['id','name','role','jurisdiction','owner','stage','note'])f.elements[key].value=p[key];f.elements.id.readOnly=!!old;
    for(const input of f.querySelectorAll('[name=rails]'))input.checked=p.rails.includes(input.value);
    for(const key of Object.keys(CHECKS)){f.elements[`${key}_state`].value=p.review[key].state;f.elements[`${key}_reference`].value=p.review[key].reference;}
    participantModules.fillForm(p.modules);$('#partner-dialog').showModal();
  }
  $('#partner-form').elements.role.innerHTML=labels(ROLES);$('#partner-form').elements.stage.innerHTML=labels(STAGES);$('#partner-stage-filter').innerHTML='<option value="all">All stages</option>'+labels(STAGES);
  $('#partner-rail-fields').innerHTML=Object.entries(RAILS).map(([key,rail])=>`<label class="rail-checkbox"><input type="checkbox" name="rails" value="${key}">${e(rail.name)}</label>`).join('');
  $('#partner-review-fields').innerHTML=Object.entries(CHECKS).map(([key,label])=>`<fieldset class="review-field"><legend>${e(label)}</legend><label>Planning state<select name="${key}_state">${labels(REVIEW_STATES)}</select></label><label>Evidence reference<input name="${key}_reference" maxlength="180" placeholder="Internal document or review reference"></label></fieldset>`).join('');
  $('#new-partner').addEventListener('click',()=>partnerEditor());
  $('#partner-form').addEventListener('submit',event=>{event.preventDefault();const f=event.currentTarget;try{const data=Object.fromEntries(new FormData(f)),old=state.partners.find(p=>p.id===editing),now=new Date().toISOString();if(!editing&&state.partners.some(p=>p.id===data.id.toLowerCase()))throw new Error('This partner reference already exists. Edit its directory entry.');if(editing&&data.id!==editing)throw new Error('The partner reference cannot be changed.');const review=Object.fromEntries(Object.keys(CHECKS).map(key=>[key,{state:data[`${key}_state`],reference:data[`${key}_reference`]}]));const partner=validatePartner({...data,modules:participantModules.readForm(),rails:new FormData(f).getAll('rails'),review,created_at:old?.created_at||now,updated_at:now});persist({...state,partners:editing?state.partners.map(p=>p.id===editing?partner:p):[...state.partners,partner]});$('#partner-dialog').close();toast('Participant saved locally.');}catch(error){f.querySelector('.form-error').textContent=error.message;}});
  $('#partner-search').addEventListener('input',renderPartners);$('#partner-stage-filter').addEventListener('change',renderPartners);$('#route-search').addEventListener('input',renderRoutes);$('#route-status-filter').addEventListener('change',renderRoutes);
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.hasAttribute('data-studio-close'))button.closest('dialog').close();if(button.dataset.editPartner)partnerEditor(button.dataset.editPartner);if(button.dataset.openRoute){const route=state.routes.find(r=>r.draft.id===button.dataset.openRoute);loadRoute(route);refreshDraft();}if(button.dataset.archiveRoute){const route=state.routes.find(r=>r.draft.id===button.dataset.archiveRoute);confirm(route.archived?'Restore draft?':'Archive draft?',route.archived?'Restore this draft to active planning totals and the connection map?':'Keep this draft and its scenario in the library, excluding it from active planning totals and the connection map.',()=>{persist({...state,routes:state.routes.map(r=>r.draft.id===route.draft.id?{...r,archived:!r.archived,updated_at:new Date().toISOString()}:r)});toast(route.archived?'Draft restored.':'Draft archived.');});}if(button.id==='save-route'){try{if(blocked())throw new Error('Recover browser storage before saving.');const draft=getDraft();if(!draft)return;const old=state.routes.find(r=>r.draft.id===draft.id);const route={draft,events:getSample()?.events||[],archived:old?.archived||false,updated_at:new Date().toISOString()};persist({...state,routes:old?state.routes.map(r=>r.draft.id===draft.id?route:r):[...state.routes,route]});toast('Route and sample scenario saved locally.');}catch(error){toast(error.message);}}});
  $('#studio-confirm-action').addEventListener('click',()=>{try{pending?.();$('#studio-confirm').close();pending=null;}catch(error){$('#studio-confirm .form-error').textContent=error.message;}});
  $('#export-studio').addEventListener('click',()=>{download('bloch-pay-integration-workspace.json',corrupt?serialized:JSON.stringify(state,null,2));toast('Integration workspace exported.');});
  $('#import-studio').addEventListener('click',()=>$('#studio-backup-file').click());
  $('#studio-backup-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>2_000_000)throw new Error('Integration backup must be smaller than 2 MB.');const candidate=readStudio(await file.text());confirm('Replace the integration workspace?',`Import ${candidate.partners.length} participants and ${candidate.routes.length} routes, replacing this browser's current studio data? Export a backup first to keep a copy. Your invoice workspace is unchanged.`,()=>{persist(candidate);onReplace();toast('Integration backup imported.');});}catch(error){toast(`Import refused: ${error.message}`);}});
  window.addEventListener('storage',event=>{if(event.key===STUDIO_KEY||event.key===null)notice('The studio changed in another tab. Reload before saving.');});
  for(const side of ['source','destination']){$('#route-form').elements[side+'Partner'].setAttribute('list','partner-options');$('#route-form').elements[side+'Partner'].addEventListener('change',event=>{const partner=state.partners.find(p=>p.id===event.target.value.toLowerCase());if(partner){event.target.value=partner.id;$('#route-form').elements[side+'Role'].value=partner.role;}});}
  render();return {refreshDraft,hasUnsavedDraft:()=>{const draft=getDraft();if(!draft)return false;const saved=state.routes.find(r=>r.draft.id===draft.id);return !saved||JSON.stringify(saved.events)!==JSON.stringify(getSample()?.events||[]);}};
}
