import {emptyWorkspace,readBackup,validateWorkspace,parseAmount,formatAmount,localDate,invoiceSummary,analytics,chartPercent,invoicesCSV,receiptsCSV,storeWorkspace,STORAGE_KEY} from './model.mjs';
const $=selector=>document.querySelector(selector);
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=value=>escape(formatAmount(value));
let state=emptyWorkspace(), serialized=null, storageUnavailable=false, corrupt=false, selectedId=null, confirmAction=null, toastTimer;
try { serialized=localStorage.getItem(STORAGE_KEY); if(serialized) state=readBackup(serialized); }
catch(error) { corrupt=serialized!==null; storageUnavailable=!corrupt; $('#storage-notice').hidden=false; $('#storage-notice').textContent=corrupt?'Saved data could not be read. Export the original backup below, then import a valid backup to recover. No records have been overwritten.':'Browser storage is unavailable. Enable site storage and reload to save invoices.'; }
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function save(next){
  if(storageUnavailable) throw new Error('Browser storage is unavailable. Reload after enabling site storage.');
  const saved=storeWorkspace(localStorage,serialized,next);state=saved.data;serialized=saved.serialized;corrupt=false;$('#storage-notice').hidden=true;render();
}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
const statusLabel=s=>({'open':'Open','partial':'Partial','matched':'Matched records','over-recorded':'Over-recorded','void':'Void'}[s]);
const badge=s=>`<span class="badge ${s}">${statusLabel(s)}</span>`;
function matchingInvoices(){const query=$('#search').value.toLowerCase().trim(),direction=$('#direction').value,status=$('#status').value;return state.invoices.filter(i=>{const s=invoiceSummary(i,state.receipts);return (!query||`${i.reference} ${i.counterparty}`.toLowerCase().includes(query))&&(direction==='all'||i.direction===direction)&&(status==='all'||(status==='overdue'?s.overdue:s.status===status));}).sort((a,b)=>a.due.localeCompare(b.due)||a.reference.localeCompare(b.reference));}
function empty(title,copy,action=''){return `<div class="empty"><h3>${title}</h3><p>${copy}</p>${action}</div>`;}
function renderLedger(){
  const rows=matchingInvoices();
  $('#filter-summary').textContent=`Showing ${rows.length} of ${state.invoices.length} invoices. Overview and analytics include all active invoices.`;
  if(!rows.length){$('#ledger').innerHTML=empty(state.invoices.length?'No matching invoices':'Your ledger starts here',state.invoices.length?'Change the filters to see more records.':'Create a receivable or payable, record amounts against it, and track what remains outstanding.',state.invoices.length?'':'<button data-new-invoice class="primary">Create your first invoice</button>');return;}
  $('#ledger').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Reference / counterparty</th><th>Direction</th><th>Expected · BLCH</th><th>Outstanding · BLCH</th><th>Due date</th><th>Record status</th><th>Actions</th></tr></thead><tbody>${rows.map(i=>{const s=invoiceSummary(i,state.receipts);return `<tr><td><strong>${escape(i.reference)}</strong><small>${escape(i.counterparty)}</small></td><td>${i.direction==='receivable'?'↙ Receivable':'↗ Payable'}</td><td class="amount">${amount(i.amount)}</td><td class="amount">${amount(s.remaining)}${s.excess?`<small>Excess ${amount(s.excess)}</small>`:''}</td><td>${i.due}${s.overdue?'<small class="badge overdue">Overdue</small>':''}</td><td>${badge(s.status)}</td><td><div class="row-actions"><button data-detail="${i.id}" aria-label="View invoice ${escape(i.reference)}">View</button>${i.state==='active'?`<button data-record="${i.id}" aria-label="Record payment for ${escape(i.reference)}">Record</button>`:''}</div></td></tr>`;}).join('')}</tbody></table></div>`;
}
function bars(rows,max){return rows.map(r=>`<div class="chart-row"><div class="chart-label"><span>${escape(r.label)}</span><span>${amount(r.receivable)} in / ${amount(r.payable)} out</span></div><svg viewBox="0 0 100 20" preserveAspectRatio="none" role="img" aria-label="${escape(r.label)}: ${amount(r.receivable)} BLCH receivable; ${amount(r.payable)} BLCH payable"><rect class="track" width="100" height="7" rx="1"/><rect width="${chartPercent(r.receivable,max)}" height="7" rx="1"/><rect class="track" width="100" height="7" y="12" rx="1"/><rect class="payable" width="${chartPercent(r.payable,max)}" height="7" y="12" rx="1"/></svg></div>`).join('');}
function render(){
  const today=localDate(), stats=analytics(state.invoices,state.receipts,today);
  $('#invoice-count').textContent=`${state.invoices.length} invoice${state.invoices.length===1?'':'s'}`;
  $('#metrics').innerHTML=[['TO RECEIVE',stats.receivable,'Outstanding BLCH'],['TO PAY',stats.payable,'Outstanding BLCH'],['OVERDUE',stats.overdue,'Both directions · outstanding BLCH'],['RECORDED NET',stats.inflow-stats.outflow,'Manual inflows minus outflows · BLCH']].map(([label,value,description])=>`<article class="metric"><span class="metric-label">${label}</span><strong>${amount(value)}</strong><small>${description}</small></article>`).join('');
  $('#summary-line').textContent=`${stats.active} active invoices · ${stats.matched} matched by recorded amounts · ${formatAmount(stats.excess)} BLCH over-recorded`;
  $('#as-of').textContent=`As of ${today} · local date`;
  $('#schedule').innerHTML=bars(stats.schedule,stats.schedule.reduce((max,r)=>[max,r.receivable,r.payable].reduce((a,b)=>a>b?a:b),0n));
  const max=stats.aging.reduce((a,b)=>a>b?a:b,0n);
  $('#aging').innerHTML=stats.aging.map((value,index)=>`<div class="chart-row aging-row"><div class="chart-label"><span>${['Not overdue','1–7 days','8–30 days','31+ days'][index]}</span><span>${amount(value)} BLCH</span></div><svg viewBox="0 0 100 9" preserveAspectRatio="none" role="img" aria-label="${['Not overdue','1–7 days','8–30 days','31+ days'][index]}: ${amount(value)} BLCH"><rect class="track" width="100" height="9" rx="1"/><rect width="${chartPercent(value,max)}" height="9" rx="1"/></svg></div>`).join('');
  $('#counterparties').innerHTML=stats.counterparties.length?`<div class="table-wrap"><table><thead><tr><th>Counterparty</th><th>Receivable · BLCH</th><th>Payable · BLCH</th></tr></thead><tbody>${stats.counterparties.map(r=>`<tr><td>${escape(r.name)}</td><td class="amount">${amount(r.receivable)}</td><td class="amount">${amount(r.payable)}</td></tr>`).join('')}</tbody></table></div>`:'<p>No outstanding counterparty balances yet.</p>';
  $('#receipts').innerHTML=state.receipts.length?`<div class="table-wrap"><table><thead><tr><th>Record / invoice</th><th>Date</th><th>Recorded · BLCH</th><th>Evidence</th><th>Actions</th></tr></thead><tbody>${[...state.receipts].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>{const i=state.invoices.find(i=>i.id===r.invoiceId);return `<tr><td><strong>${escape(r.reference)}</strong><small>${escape(i.reference)} · ${i.direction}</small></td><td>${r.date}</td><td class="amount">${amount(r.amount)}</td><td>${r.txid?`<a class="inline-link" href="https://blochl1.com/tx/${r.txid}?block=${r.blockId}" target="_blank" rel="noopener noreferrer">Explorer reference ↗</a><small>Output ${r.output} · entered manually</small>`:'Manual record<small>No transaction reference</small>'}</td><td><button data-remove="${r.id}" aria-label="Remove payment record ${escape(r.reference)}">Remove</button></td></tr>`;}).join('')}</tbody></table></div>`:empty('Keep the evidence connected','Saved payment records will appear here, with their invoice reference, amount and optional transaction output.');
  $('#new-invoice').disabled=storageUnavailable||corrupt;$('#new-receipt').disabled=storageUnavailable||corrupt||!state.invoices.some(i=>i.state==='active');
  $('#storage-status').textContent=corrupt?'RECOVERY NEEDED':storageUnavailable?'STORAGE UNAVAILABLE':`REVISION ${state.revision} · LOCAL`;
  renderLedger();
}
function resetForm(id){const form=$(id);form.reset();form.querySelector('.form-error').textContent='';return form;}
function newInvoice(){if(corrupt||storageUnavailable)return notify('Recover browser storage before creating invoices.');const f=resetForm('#invoice-form');f.elements.issued.value=localDate();f.elements.due.value=localDate();$('#invoice-dialog').showModal();}
function newReceipt(id){const invoices=state.invoices.filter(i=>i.state==='active');if(!invoices.length)return notify('Create an active invoice first.');const f=resetForm('#receipt-form');f.elements.invoiceId.innerHTML=invoices.map(i=>`<option value="${i.id}">${escape(i.reference)} · ${escape(i.counterparty)} · ${i.direction}</option>`).join('');if(id)f.elements.invoiceId.value=id;f.elements.date.value=localDate();const invoice=invoices.find(i=>i.id===f.elements.invoiceId.value);f.elements.amount.value=formatAmount(invoiceSummary(invoice,state.receipts).remaining,false);$('#receipt-dialog').showModal();}
function confirmChange(title,copy,action){$('#confirm-title').textContent=title;$('#confirm-copy').textContent=copy;$('#confirm-dialog .form-error').textContent='';confirmAction=action;$('#confirm-dialog').showModal();}
function showDetail(id){
  selectedId=id;const i=state.invoices.find(i=>i.id===id),s=invoiceSummary(i,state.receipts),rows=state.receipts.filter(r=>r.invoiceId===id);
  $('#invoice-detail').innerHTML=`${badge(s.status)}<dl class="detail-grid">${[['Reference',i.reference],['Counterparty',i.counterparty],['Direction',i.direction],['Expected BLCH',formatAmount(i.amount)],['Recorded BLCH',formatAmount(s.recorded)],['Outstanding BLCH',formatAmount(s.remaining)],['Issue date',i.issued],['Due date',i.due],['Recipient reference',i.recipient||'Not specified']].map(([k,v])=>`<div><dt>${k}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl>${i.note?`<p class="detail-note">${escape(i.note)}</p>`:''}<p class="form-note">This is a local invoice record. Recorded amounts and transaction references are entered manually.</p><div class="button-row"><button id="export-invoice">Export invoice JSON ↓</button>${i.state==='active'&&!rows.length?'<button id="void-invoice" class="danger">Void invoice</button>':''}</div>${rows.map(r=>`<div class="detail-record"><strong>${escape(r.reference)}</strong> · ${amount(r.amount)} BLCH · ${r.date}${r.note?`<p class="detail-note">${escape(r.note)}</p>`:''}</div>`).join('')}`;
  $('#detail-dialog').showModal();
}
document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button)return;
  if(button.hasAttribute('data-close')){button.closest('dialog').close();return;}
  if(button.hasAttribute('data-new-invoice'))newInvoice();
  if(button.dataset.detail)showDetail(button.dataset.detail);
  if(button.dataset.record)newReceipt(button.dataset.record);
  if(button.dataset.remove){const r=state.receipts.find(r=>r.id===button.dataset.remove);confirmChange('Remove payment record?',`Remove ${r.reference} (${formatAmount(r.amount)} BLCH)? This changes the invoice balance. Export a backup first if you need to retain the original record.`,()=>{save({...state,receipts:state.receipts.filter(row=>row.id!==r.id)});notify('Payment record removed.');});}
  if(button.id==='export-invoice'){const invoice=state.invoices.find(i=>i.id===selectedId);download(`bloch-pay-invoice-${invoice.id}.json`,JSON.stringify({schema:'bloch-pay-invoice',version:1,network:state.network,asset:state.asset,decimals:8,invoice,receipts:state.receipts.filter(r=>r.invoiceId===invoice.id),evidence:'Manual records; not chain-verified'},null,2),'application/json');}
  if(button.id==='void-invoice'){const invoice=state.invoices.find(i=>i.id===selectedId);$('#detail-dialog').close();confirmChange('Void invoice?',`${invoice.reference} will remain in your records but will no longer count toward outstanding balances.`,()=>{save({...state,invoices:state.invoices.map(i=>i.id===invoice.id?{...i,state:'void'}:i)});notify('Invoice voided.');});}
});
$('#new-invoice').addEventListener('click',newInvoice);$('#new-receipt').addEventListener('click',()=>newReceipt());
$('#confirm-action').addEventListener('click',()=>{try{confirmAction?.();$('#confirm-dialog').close();confirmAction=null;}catch(error){$('#confirm-dialog .form-error').textContent=error.message;}});
$('#invoice-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;try{const f=Object.fromEntries(new FormData(form));const invoice={...f,id:crypto.randomUUID(),amount:parseAmount(f.amount),createdAt:new Date().toISOString(),state:'active'};save({...state,invoices:[...state.invoices,invoice]});$('#invoice-dialog').close();notify('Invoice saved in this browser.');}catch(error){form.querySelector('.form-error').textContent=error.message;}});
$('#receipt-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;try{const f=Object.fromEntries(new FormData(form));if(f.date>localDate())throw new Error('A payment record cannot be dated in the future.');const receipt={...f,id:crypto.randomUUID(),amount:parseAmount(f.amount),output:f.output===''?null:Number(f.output),createdAt:new Date().toISOString()};save({...state,receipts:[...state.receipts,receipt]});$('#receipt-dialog').close();notify('Manual payment record saved.');}catch(error){form.querySelector('.form-error').textContent=error.message;}});
$('#receipt-form').elements.invoiceId.addEventListener('change',event=>{const i=state.invoices.find(i=>i.id===event.target.value);$('#receipt-form').elements.amount.value=formatAmount(invoiceSummary(i,state.receipts).remaining,false);});
$('#filters').addEventListener('submit',event=>event.preventDefault());$('#filters').addEventListener('input',renderLedger);$('#filters').addEventListener('reset',()=>setTimeout(renderLedger,0));
$('#export-backup').addEventListener('click',()=>{download(`bloch-pay-backup-${localDate()}.json`,corrupt?serialized:JSON.stringify(state,null,2),'application/json');notify(corrupt?'Original saved data exported for recovery.':'Workspace backup exported.');});
$('#export-invoices').addEventListener('click',()=>download(`bloch-pay-invoices-${localDate()}.csv`,invoicesCSV(state),'text/csv;charset=utf-8'));
$('#export-receipts').addEventListener('click',()=>download(`bloch-pay-records-${localDate()}.csv`,receiptsCSV(state),'text/csv;charset=utf-8'));
$('#import-backup').addEventListener('click',()=>$('#backup-file').click());
$('#backup-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>2_000_000)throw new Error('Backup must be smaller than 2 MB.');const candidate=readBackup(await file.text());confirmChange('Replace this workspace?',`This backup contains ${candidate.invoices.length} invoices and ${candidate.receipts.length} payment records. Importing replaces this browser's current records. Export a backup first to keep them.`,()=>{save(candidate);notify('Backup imported.');});}catch(error){notify(`Import refused: ${error.message}`);}});
window.addEventListener('storage',event=>{if(event.key===STORAGE_KEY||event.key===null){$('#storage-notice').hidden=false;$('#storage-notice').textContent='This workspace changed in another tab. Reload this page before making changes.';}});
function connection(){ $('#connection').textContent=navigator.onLine?'Online':'Offline · local mode'; }
window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();render();
let deferredInstall;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#install').hidden=false;});
$('#install').addEventListener('click',async()=>{if(!deferredInstall)return;await deferredInstall.prompt();deferredInstall=null;$('#install').hidden=true;});
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(reg=>{const show=()=>{if(reg.waiting&&navigator.serviceWorker.controller){$('#update-notice').hidden=false;$('#update-app').onclick=()=>{if(document.querySelector('dialog[open]'))return notify('Close the open form before updating.');reg.waiting.postMessage({type:'ACTIVATE'});};}};show();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',show));}).catch(()=>notify('Offline installation is unavailable in this browser.'));let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading){reloading=true;location.reload();}});}
setInterval(()=>{if($('#as-of').textContent.split(' · ')[0]!==`As of ${localDate()}`)render();},60000);
