// All participant records and intercepted public observations here are fixtures.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {configuredStudio,sourcePage,packet} from './evidence-fixture.mjs';
import {validatePacket,validateVault} from '../app/evidence-model.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');let base=process.argv[2],server;
if(!base){server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(path.endsWith('/'))path+='index.html';else if(!extname(path))path+='.html';const file=resolve(root,'.'+path);assert(file.startsWith(root+'/'));res.setHeader('Content-Type',({'.html':'text/html','.mjs':'application/javascript','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]||'application/octet-stream');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://bloch-graphus.xyz; img-src 'self' data:; worker-src 'self'");res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
const out=process.env.PAY_ARTIFACTS||'/private/tmp/bloch-pay-evidence';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});
await context.addInitScript(studio=>{if(!localStorage.getItem('evidence-fixture-seeded')){localStorage.setItem('bloch-pay-integration-workspace-v1',JSON.stringify(studio));localStorage.setItem('bloch-pay-workspace-v1','invoice-isolation-sentinel');localStorage.setItem('evidence-fixture-seeded','1');}},configuredStudio());
let mode='ok',release,calls=[];const errors=[];
await context.route('https://bloch-graphus.xyz/api/chain/network?*',async route=>{const url=new URL(route.request().url());assert.deepEqual([...url.searchParams.keys()],['asset']);assert.equal(route.request().headers().authorization,undefined);assert.equal(route.request().headers().cookie,undefined);calls.push(url.searchParams.get('asset'));const response={headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:JSON.stringify(sourcePage(url.searchParams.get('asset'),25))};if(mode==='error')return route.fulfill({...response,status:502,body:'{}'});if(mode==='defer')await new Promise(done=>{release=done;});await route.fulfill(response).catch(()=>{});});
const page=await context.newPage();page.on('dialog',dialog=>dialog.accept());page.on('pageerror',error=>errors.push(error.message));
const readStore=target=>target.evaluate(async()=>{const {openEvidenceStore}=await import('./evidence-store.mjs');const db=await openEvidenceStore();const value=await db.snapshot();db.close();return value;});
async function exported(button,file){const event=page.waitForEvent('download');await page.locator(button).click();await(await event).saveAs(out+'/'+file);return JSON.parse(await readFile(out+'/'+file,'utf8'));}
try{
  await page.goto(base+'/app/evidence?participant=origin-psav&route=route-fixture&asset=BLCH',{waitUntil:'networkidle'});await page.waitForFunction(()=>!document.querySelector('#export-evidence-vault').disabled);assert.equal(calls.length,0);assert.equal(await page.locator('#capture-route').inputValue(),'route-fixture');const studioBefore=await page.evaluate(()=>localStorage.getItem('bloch-pay-integration-workspace-v1'));
  await page.locator('#capture-public').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.startsWith('Captured 25'));assert.equal(calls.length,1);assert.equal((await readStore(page)).records.length,0);assert.equal(await page.locator('#evidence-ledger tr').count(),20);await page.locator('#evidence-next').click();assert.equal(await page.locator('#evidence-ledger tr').count(),5);
  await page.locator('#evidence-minimum').fill('2700000000000000001');assert.equal(await page.locator('#evidence-ledger tr').count(),1);assert((await page.locator('#evidence-totals').innerText()).includes('2700000000000000001'));await page.locator('#evidence-maximum').fill('1');assert((await page.locator('#evidence-filter-status').innerText()).includes('Minimum'));assert.equal(await page.locator('#evidence-ledger tr').count(),0);await page.locator('#evidence-reset-filters').click();
  await page.locator('#evidence-review-stage').selectOption('reviewed');await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-review-error').textContent.includes('owner'));await page.locator('[name=owner]').fill('Fixture review team');await page.locator('[name=note]').fill('<img src=x onerror=alert(1)> Source timestamps remain absent.');await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent.includes('REVISION 1'));assert.equal(await page.locator('#evidence-history img').count(),0);
  const graphus=await exported('#export-evidence-packet','graphus-packet.json');await validatePacket(graphus);assert.equal(graphus.dataset.edges[0].amount_base_units,'2700000000000000001');assert(!JSON.stringify(graphus).includes('Fixture review team'));assert(!JSON.stringify(graphus).includes('origin-psav'));assert.equal((await readStore(page)).records[0].context.association,'local_context_only');
  await page.locator('[name=note]').fill('Follow up missing source timestamps.');await page.locator('#evidence-review-stage').selectOption('follow_up');await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent.includes('REVISION 2'));await page.locator('#archive-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent.includes('ARCHIVED'));assert.equal(await page.locator('[data-open-evidence]').count(),0);await page.locator('#archive-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent==='REVISION 4');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload({waitUntil:'networkidle'});await context.setOffline(true);await page.reload({waitUntil:'networkidle'});await page.locator('[data-open-evidence]').first().click();assert.equal(await page.locator('#evidence-saved-state').innerText(),'REVISION 4');assert.equal(calls.length,1);await context.setOffline(false);
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});for(const id of ['evidence-source','evidence-review-form','evidence-library']){await page.locator('#'+id).scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/${id}-${width}.png`});}}
  const other=await context.newPage();other.on('dialog',dialog=>dialog.accept());await other.goto(base+'/app/evidence',{waitUntil:'networkidle'});await other.locator('[data-open-evidence]').first().click();await page.locator('[name=note]').fill('First tab revision retained.');await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent==='REVISION 5');await other.locator('[name=note]').fill('Stale tab must not overwrite.');await other.locator('#save-evidence').click();await other.waitForFunction(()=>document.querySelector('#evidence-review-error').textContent.includes('another tab'));assert.equal((await readStore(page)).records[0].review.note,'First tab revision retained.');await other.close();
  const vault=await exported('#export-evidence-vault','evidence-backup.json');await validateVault(vault);const bad=structuredClone(vault);bad.records[0].packet.dataset.edges[0].amount_base_units='7';await page.locator('#evidence-vault-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.waitForFunction(()=>document.querySelector('#evidence-toast').textContent.startsWith('Import refused'));assert.equal((await readStore(page)).records[0].revision,5);
  await page.locator('#evidence-vault-file').setInputFiles(out+'/evidence-backup.json');await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.startsWith('Evidence backup imported'));assert.equal(await page.evaluate(()=>localStorage.getItem('bloch-pay-integration-workspace-v1')),studioBefore);assert.equal(await page.evaluate(()=>localStorage.getItem('bloch-pay-workspace-v1')),'invoice-isolation-sentinel');
  mode='defer';await page.locator('#capture-public').click();for(let attempt=0;!release&&attempt<1000;attempt++)await new Promise(done=>setTimeout(done,10));assert(release,'Deferred capture request was not issued');await page.locator('#capture-asset').selectOption('ETH');release();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('context changed'));assert.equal(await page.locator('#evidence-result').isHidden(),true);mode='ok';await page.locator('#capture-public').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.startsWith('Captured 25'));assert((await page.locator('#evidence-source').innerText()).includes('ETH / ethereum-mainnet'));
  const beforeFailure=await page.locator('#evidence-provenance').innerText();mode='error';await page.locator('#capture-public').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('502'));assert.equal(await page.locator('#evidence-provenance').innerText(),beforeFailure);mode='ok';const blochPacket=await packet();await page.locator('#evidence-packet-file').setInputFiles({name:'wrong-asset.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(blochPacket))});await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('asset differs'));assert.equal(await page.locator('#evidence-provenance').innerText(),beforeFailure);
  await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent==='REVISION 1');assert.equal((await readStore(page)).records.length,2);
  const rollback=await page.evaluate(async()=>{const {openEvidenceStore}=await import('./evidence-store.mjs');const db=await openEvidenceStore(),before=await db.snapshot();let rejected=false;try{await db.replace(before.generation,Array(51).fill(before.records[0]));}catch{rejected=true;}const after=await db.snapshot();db.close();return {rejected,unchanged:JSON.stringify(before)===JSON.stringify(after)};});assert.deepEqual(rollback,{rejected:true,unchanged:true});
  await page.locator('#delete-evidence').click();await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('removed'));assert.equal((await readStore(page)).records.length,1);
  await page.locator('#capture-asset').selectOption('BLCH');await page.locator('#evidence-packet-file').setInputFiles(out+'/graphus-packet.json');await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.startsWith('Imported packet validated'));assert((await page.locator('#evidence-source').innerText()).includes('IMPORTED PACKET'));await page.locator('#save-evidence').click();await page.waitForFunction(()=>document.querySelector('#evidence-saved-state').textContent==='REVISION 1');assert((await readStore(page)).records.some(record=>record.acquisition==='imported_packet'&&record.packet.dataset_sha256===graphus.dataset_sha256));
  assert.deepEqual(errors,[]);const report={result:'PASS',url:base,fixture:'Synthetic participants and intercepted public source records',checks:['No automatic source requests','Fixed credential-free public capture','Exact records, filters and separate UTXO totals','Review owner and note validation','Graphus export excludes local review metadata','Revision, archive and restore','IndexedDB persistence offline','Three responsive widths','Cross-tab writes fail without replacing evidence','Atomic capacity rollback','Invalid backup leaves data untouched','Evidence backup preserves invoice and studio bytes','Asset-switch cancellation ignores late results','Failed source and mismatched import retain previous sample','Delete and imported-packet labeling'],source_calls:calls.length,errors};await writeFile(out+'/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}}
