// Synthetic participant records exercise configuration, not actual authorization.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildRoute} from '../app/integrations.mjs';
import {emptyReview} from '../app/studio-model.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
let base=process.argv[2],server;
if(!base){server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(path.endsWith('/'))path+='index.html';else if(!extname(path))path+='.html';const file=resolve(root,'.'+path);assert(file.startsWith(root+'/'));const data=await readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'application/javascript','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]||'application/octet-stream');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://bloch-graphus.xyz; img-src 'self' data:; worker-src 'self'");res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
const out=process.env.PAY_ARTIFACTS||'/private/tmp/bloch-pay-modules';await mkdir(out,{recursive:true});
const date='2026-09-24T12:00:00.000Z';const source={id:'origin-psav',name:'Example origin PSAV',role:'psav',jurisdiction:'Brazil',owner:'Integration team',stage:'discovery',rails:['pix','blch'],review:emptyReview(),note:'',created_at:date,updated_at:date};source.review.access.state='blocked';
const backup={schema:'bloch-pay-integration-workspace',version:1,environment:'design',execution_enabled:false,revision:7,partners:[source],routes:Array.from({length:24},(_,i)=>({draft:buildRoute({reference:'example-'+i,sourcePartner:source.id,sourceRole:'psav',sourceRail:i===0?'blch':'pix',sourceCurrency:i===0?'BLCH':'BRL',sourceCustom:'',destinationPartner:'destination-'+i,destinationRole:'bank',destinationRail:'sepa',destinationCurrency:'EUR',destinationCustom:'',amount:i===0?'27000000000.00000001':'1000.01',destinationAmount:'',quote:''},'draft-'+i,date),events:[],archived:false,updated_at:date}))};
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true}),page=await context.newPage();
let calls=0;const errors=[];page.on('pageerror',error=>errors.push(error.message));
await context.route('https://bloch-graphus.xyz/api/system/map',async route=>{calls++;assert(!route.request().headers().authorization);assert(!route.request().headers().cookie);if(calls>1)return route.fulfill({status:503,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:'{}'});await route.fulfill({headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:JSON.stringify({schema_version:1,registry_version:'synthetic-browser-test',source:'https://bloch-graphus.xyz/map',modules:[{id:'scores',title:'Private observations',description:'Synthetic test capability metadata',limits:'Not an AML verdict',status:'available',access:'private',assets:['BLCH','ETH']},{id:'aml-monitoring',title:'Monitoring rules',description:'Synthetic planned capability',limits:'Not deployed',status:'design',access:'private',assets:['BLCH','ETH']}]})});});
try{
  await page.goto(base+'/app/integrations',{waitUntil:'networkidle'});await page.locator('#studio-backup-file').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#studio-confirm-action').click();await page.locator('#studio-confirm').waitFor({state:'hidden'});
  assert.equal(calls,0);assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),25);assert((await page.locator('#ops-actions').innerText()).includes('24 affected drafts'));
  await page.locator('#configure-participant-modules').click();const form=page.locator('#partner-form');for(const key of ['graphus','constellation','aml','system_map'])await form.locator(`[name=module_enabled][value=${key}]`).check();await form.locator('[name=module_asset][value=ETH]').check();await form.locator('[name=module_private_profile]').selectOption('read');await form.locator('[name=module_organization]').fill('participant-org');await form.getByRole('button',{name:'Save participant',exact:true}).click();assert((await form.locator('.form-error').innerText()).includes('purpose'));
  await form.locator('[name=module_purpose]').fill('<img src=x onerror=alert(1)> evidence review');await form.getByRole('button',{name:'Save participant',exact:true}).click();await page.locator('#partner-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#module-plan-summary img').count(),0);assert((await page.locator('#module-plan-summary').innerText()).includes('authorization not verified'));
  await page.locator('#module-asset').selectOption('ETH');assert.equal(await page.locator('#participant-module-cards a[href="https://bloch-graphus.xyz/constellation?asset=eth"]').count(),1);assert.equal(await page.locator('#participant-module-cards a[href="https://rednblue.space/portal/?view=analyses"]').count(),1);
  await page.locator('#refresh-module-registry').click();await page.waitForFunction(()=>document.querySelector('#module-registry-status').textContent.includes('synthetic-browser-test'));assert.equal(calls,1);assert((await page.locator('#participant-module-cards').innerText()).includes('1 available, 0 prototypes, 1 planned'));await page.locator('#refresh-module-registry').click();await page.waitForFunction(()=>document.querySelector('#module-registry-status').textContent.includes('503'));assert((await page.locator('#module-registry-status').innerText()).includes('Last successful registry retained'));
  const download=page.waitForEvent('download');await page.locator('#export-module-plan').click();await(await download).saveAs(out+'/participant-manifest.json');const manifest=JSON.parse(await readFile(out+'/participant-manifest.json','utf8'));assert.equal(manifest.execution_enabled,false);assert.deepEqual(manifest.private_access.requested_scopes,['analyses:read','scores:read']);assert.equal(manifest.private_access.authorization_status,'not_verified');assert.equal(manifest.launchers.length,4);
  await page.locator('#graph-search').fill('destination-20');assert.equal(await page.locator('#graph-focus option').count(),2);await page.locator('#graph-focus').selectOption('destination-20');assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),2);await page.locator('#graph-direction').selectOption('outgoing');assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),0);await page.locator('#graph-reset').click();assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),25);
  await page.locator('[data-focus-node="destination-10"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#graph-focus').inputValue(),'destination-10');await page.locator('#graph-reset').click();
  for(let i=0;i<3;i++)await page.locator(`[data-compare="draft-${i}"]`).check();await page.locator('[data-compare="draft-3"]').click();assert.equal(await page.locator('[data-compare="draft-3"]').isChecked(),false);assert((await page.locator('#compare-notice').innerText()).includes('at most three'));
  await page.locator('#ops-source').selectOption('blch');assert((await page.locator('#ops-count').innerText()).includes('1 of 24'));assert((await page.locator('#route-comparison').innerText()).includes('27000000000.00000001 BLCH'));assert((await page.locator('#compare-notice').innerText()).includes('2 selected drafts outside'));assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),2);
  const csvWait=page.waitForEvent('download');await page.locator('#export-planning-csv').click();await(await csvWait).saveAs(out+'/filtered-routes.csv');const csv=await readFile(out+'/filtered-routes.csv','utf8');assert.equal(csv.split('\r\n').length,2);assert(csv.includes('27000000000.00000001'));await page.locator('#reset-ops').click();
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});for(const section of ['participant-modules','operations','saved-routes']){await page.locator('#'+section).scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/${section}-${width}.png`});}}
  await page.setViewportSize({width:1440,height:1000});await page.locator('#graph-viewport').screenshot({path:out+'/graph-desktop.png'});await page.setViewportSize({width:390,height:1000});await page.locator('#graph-viewport').screenshot({path:out+'/graph-mobile.png'});
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bloch-pay-integration-workspace-v1')));assert.equal(saved.version,2);assert.equal(saved.partners[0].modules.enabled.length,4);assert.equal(saved.routes.length,24);
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload({waitUntil:'networkidle'});await context.setOffline(true);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#graph-drawing [data-focus-node]').count(),25);assert((await page.locator('#module-plan-summary').innerText()).includes('4 tools configured'));assert((await page.locator('#module-registry-status').innerText()).includes('not checked'));assert.equal(calls,2);assert.deepEqual(errors,[]);
  const report={result:'PASS',url:base,fixture:'Synthetic participant routes and intercepted capability metadata',checks:['Legacy import preserves 24 routes','Four module configuration and purpose validation','Private access remains unverified','Asset-only product links','Explicit credential-free registry fetch','Failed refresh retains dated metadata','Manifest export scopes match portal contract','All 25 references rendered','Search and directional neighborhood','Keyboard point focus','Comparison limit and selection across filters','Exact filtered CSV','Three responsive widths','Offline module configuration and graph','No background registry calls'],errors};await writeFile(out+'/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}}
