// Synthetic invoices and CSV records; browser storage is isolated, including on production.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {emptyWorkspace,csvCell,STORAGE_KEY} from '../app/model.mjs';
import {CSV_COLUMNS} from '../app/reconciliation.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');let base=process.argv[2],server;
if(!base){server=createServer(async(req,res)=>{try{let path=new URL(req.url,'http://localhost').pathname;if(path.endsWith('/'))path+='index.html';else if(!extname(path))path+='.html';const file=resolve(root,'.'+path);assert(file.startsWith(root+'/'));res.setHeader('Content-Type',({'.html':'text/html','.mjs':'application/javascript','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]||'application/octet-stream');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://bloch-graphus.xyz; img-src 'self' data:; worker-src 'self'");res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));base=`http://127.0.0.1:${server.address().port}`;}
const out=process.env.PAY_ARTIFACTS||'/private/tmp/bloch-pay-reconciliation-v5';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,reducedMotion:'reduce'});
const now='2026-09-24T12:00:00.000Z',seed={...emptyWorkspace(),invoices:[{id:'fixture-in',reference:'INV-IN',counterparty:'Fixture receivable',direction:'receivable',amount:'1000000001',issued:'2026-09-01',due:'2026-09-20',recipient:'',note:'',state:'active',createdAt:now},{id:'fixture-out',reference:'INV-OUT',counterparty:'Fixture payable',direction:'payable',amount:'700000001',issued:'2026-09-01',due:'2026-09-20',recipient:'',note:'',state:'active',createdAt:now}]};
await context.addInitScript(({seed,key})=>{if(!localStorage.getItem('batch-fixture-seeded')){localStorage.setItem(key,JSON.stringify(seed));localStorage.setItem('bloch-pay-integration-workspace-v1','integration-isolation-sentinel');localStorage.setItem('batch-fixture-seeded','yes');}},{seed,key:STORAGE_KEY});
const page=await context.newPage(),errors=[],uploads=[];page.on('dialog',dialog=>dialog.accept());page.on('pageerror',e=>errors.push(e.message));context.on('request',request=>{if(request.method()!=='GET')uploads.push(request.url());});
const csv=rows=>[CSV_COLUMNS,...rows.map(r=>CSV_COLUMNS.map(key=>r[key]||''))].map(r=>r.map(csvCell).join(',')).join('\r\n');
const row=(reference,invoice_reference,amount_BLCH)=>({reference,invoice_reference,amount_BLCH,record_date:'2026-09-22'});
const valid=[row('PAY-IN','INV-IN','10'),row('PAY-TINY','INV-IN','0.00000001'),row('PAY-OUT','INV-OUT','8'),row('PAY-IN','INV-IN','10')];
async function preview(rows){await page.locator('#batch-file').setInputFiles({name:'fixture.csv',mimeType:'text/csv',buffer:Buffer.from(csv(rows))});await page.locator('#batch-preview').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent.startsWith('Reviewed'));}
const saved=()=>page.evaluate(key=>localStorage.getItem(key),STORAGE_KEY);
try{
  await page.goto(base+'/app/reconcile',{waitUntil:'networkidle'});const initial=await saved();assert.equal(await page.locator('#batch-ledger-count').innerText(),'2 invoices');
  const template=page.waitForEvent('download');await page.locator('#batch-template').click();await(await template).saveAs(out+'/template.csv');assert.equal(await readFile(out+'/template.csv','utf8'),CSV_COLUMNS.join(',')+'\r\n');
  await preview([...valid,row('<img src=x onerror=alert(1)>','MISSING','5')]);assert.equal(await saved(),initial);assert.equal(await page.locator('#batch-apply').isDisabled(),true);assert.equal(await page.locator('#batch-ack').isDisabled(),true);await page.locator('#batch-filter').selectOption('blocked');assert.equal(await page.locator('#batch-rows tr').count(),1);assert.match(await page.locator('#batch-rows').innerText(),/not found/);assert.equal(await page.locator('#batch-rows img').count(),0);
  const report=page.waitForEvent('download');await page.locator('#batch-report').click();await(await report).saveAs(out+'/blocked-review.csv');assert.match(await readFile(out+'/blocked-review.csv','utf8'),/not chain-verified/);
  await preview(valid);assert.deepEqual(await page.locator('#batch-metrics strong').allTextContents(),['3','1','0','2']);assert.match(await page.locator('#batch-impacts').innerText(),/0.99999999/);assert.match(await page.locator('#batch-impacts').innerText(),/Matched records/);assert.equal(await saved(),initial);assert.equal(await page.locator('#batch-apply').isDisabled(),true);
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});for(const id of ['prepare','review','impact']){await page.locator('#'+id).scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/${id}-${width}.png`});}}
  await page.locator('#batch-ack').check();await page.locator('#batch-apply').click();assert.equal(await saved(),initial);await page.locator('#batch-cancel').click();assert.equal(await saved(),initial);
  await page.evaluate(key=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw new Error('Test quota exhausted');return window.originalSetItem.call(this,k,v);};},STORAGE_KEY);
  await page.locator('#batch-apply').click();await page.locator('#batch-confirm-save').click();assert.match(await page.locator('#batch-confirm-error').innerText(),/quota exhausted/);assert.equal(await saved(),initial);await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;delete window.originalSetItem;});await page.locator('#batch-confirm-save').click();await page.locator('#batch-confirm').waitFor({state:'hidden'});assert.equal(JSON.parse(await saved()).receipts.length,3);assert.equal(JSON.parse(await saved()).revision,1);assert.equal(await page.locator('#batch-apply').isDisabled(),true);assert.equal(await page.evaluate(()=>localStorage.getItem('bloch-pay-integration-workspace-v1')),'integration-isolation-sentinel');
  await preview(valid);assert.deepEqual(await page.locator('#batch-metrics strong').allTextContents(),['0','4','0','0']);assert.equal(await page.locator('#batch-apply').isDisabled(),true);await page.locator('#batch-clear').click();
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload({waitUntil:'networkidle'});await context.setOffline(true);await page.reload({waitUntil:'networkidle'});await preview(valid);assert.equal(await page.locator('#batch-connection').innerText(),'Offline · local mode');assert.equal(JSON.parse(await saved()).receipts.length,3);await context.setOffline(false);await page.locator('#batch-clear').click();
  await preview(Array.from({length:51},(_,i)=>row('PAGE-'+i,'INV-IN','0.00000001')));assert.equal(await page.locator('#batch-rows tr').count(),50);await page.locator('#batch-next').click();assert.equal(await page.locator('#batch-rows tr').count(),1);await page.locator('#batch-search').fill('PAGE-30');assert.equal(await page.locator('#batch-rows tr').count(),1);
  await page.locator('#batch-ack').check();await page.locator('#batch-apply').click();const other=await context.newPage();await other.goto(base+'/app/',{waitUntil:'networkidle'});await other.evaluate(key=>{const data=JSON.parse(localStorage.getItem(key));data.revision++;localStorage.setItem(key,JSON.stringify(data));},STORAGE_KEY);await page.waitForFunction(()=>!document.querySelector('#storage-notice').hidden);await page.locator('#batch-confirm-save').click();assert.match(await page.locator('#batch-confirm-error').innerText(),/no longer eligible/);assert.equal(JSON.parse(await saved()).receipts.length,3);await page.locator('#batch-cancel').click();await other.close();await page.locator('#batch-clear').click();
  await page.goto(base+'/app/',{waitUntil:'networkidle'});assert.match(await page.locator('#ledger').innerText(),/Matched records/);assert.match(await page.locator('#ledger').innerText(),/Over-recorded/);assert.equal(await page.locator('a[href="reconcile"]').count(),1);assert.deepEqual(errors,[]);assert.deepEqual(uploads,[]);
  const result={result:'PASS',origin:base,checks:['CSV preview never writes','All-or-nothing exceptions','Duplicate skipping and exact invoice impact','Review report and template downloads','HTML escaping','1440/390/320px layouts','Explicit confirmation and cancel','Quota rollback','Exact local ledger append','Repeat import idempotence','Integration storage isolation','Offline preview','Pagination and search','Cross-tab changes block confirmation','No data uploads'],errors};await writeFile(out+'/verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();if(server){server.closeAllConnections();await new Promise(done=>server.close(done));}}
