#!/usr/bin/env python3
"""Refuse the reproducibility claim while the Nix inputs are not actually pinned.

WHY THIS EXISTS
---------------
`flake.nix` says its revisions were "recorded from the committed flake.lock
generated by the human on the aarch64 Nix host". There is no committed
flake.lock. There never has been one on `main`: the only flake.lock in this
repository's whole history is a 7-line stub on an abandoned branch whose
`nodes` is `{"root": {}}` — it pins nothing. The commit that recorded the revs
(93ee0346, subject: "flake.lock generated on the aarch64 host
(mobile-nixos@458448d, nixpkgs@ac62194)") did not add the file, and
os/MOBILE.md's "Pinned revisions" block still holds its `<from nix flake
metadata>` placeholders — so nothing in the tree corroborates those two revs.

Every mechanism that was supposed to notice this was soft:

  * `flake-lock-drift` in .gitlab-ci.yml carried `allow_failure: true` plus a
    guard step that printed "not committed yet" — green by design, on a Nix
    runner tag, for a file that does not exist.
  * `repro-manifest.sh` wrote `flake.lock:  $(sha256sum flake.lock | ...)`.
    Command substitution in an argument does not trip `set -e`, so a missing
    lock emitted the FIELD WITH AN EMPTY VALUE rather than failing.
  * `repro-compare.sh` then read that field and only warned `if [ -n "$la" ]`
    — empty meant no warning at all, and even a genuine mismatch was a warning
    on stderr while the script went on to print REPRODUCIBLE. The cross-builder
    input-equality guard was skipped in exactly the case it exists for.

So two hosts could build from two different nixpkgs branch states and the
tooling would call the result "REPRODUCIBLE". That is the failure this guard
closes: the word must not be reachable without a pin.

WHAT THIS GUARD DOES
--------------------
Fails the pipeline unless ALL of:

  1. flake.lock exists at the repo root and parses as JSON.
  2. Every input declared in flake.nix has a node in flake.lock locked to a
     full 40-hex `rev` AND a non-empty `narHash`. A lock that resolves an input
     to a branch, or a stub whose only node is `root`, is refused: it looks
     like a pin and is not one.
  3. The revs recorded in scripts/flake-lock.sh (EXPECT_*) match what the lock
     actually pins. Prose that claims a pin must agree with the pin.
  4. The `flake-lock-drift` CI job is not `allow_failure: true`, so the drift
     gate cannot be quietly softened back.

RED UNTIL THE LOCK LANDS — BY DESIGN. Agents do not run Nix and MUST NOT
hand-write a flake.lock: its narHashes are content hashes of fetched sources,
and a fabricated one is a false pin, which is strictly worse than none. A human
runs scripts/flake-lock.sh on the aarch64 Nix host, commits flake.lock, records
the revs it prints, and this job goes green. Until then the pipeline says so out
loud instead of printing REPRODUCIBLE over unpinned inputs.

Pure Python 3. No toolchain, no build, no network, no Nix.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

# A rev is a pin only when it is the full 40-hex object id. A branch name or an
# abbreviated rev in a lock is not something a second builder can resolve to the
# same bytes.
FULL_REV = re.compile(r"^[0-9a-f]{40}$")

# scripts/flake-lock.sh sets these to this sentinel while no rev has been read
# out of a real lock. It is not a value to match against — it is the absence of
# one, and it fails.
UNRECORDED = "UNRECORDED"


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    return Path(out)


def declared_inputs(flake_nix: str) -> list[str]:
    """Input names declared in flake.nix, ignoring commented-out lines.

    Handles both spellings used here:
        inputs.nixpkgs.url = "...";
        inputs.mobile-nixos = { url = "..."; flake = false; };
    """
    names = []
    for line in flake_nix.splitlines():
        if line.lstrip().startswith("#"):
            continue
        m = re.match(r"\s*inputs\.([A-Za-z0-9_-]+)\s*(?:\.[A-Za-z0-9_.-]+\s*)?=", line)
        if m and m.group(1) not in names:
            names.append(m.group(1))
    return names


def recorded_revs(flake_lock_sh: str) -> dict[str, str]:
    """The EXPECT_* constants in scripts/flake-lock.sh, keyed by input name."""
    found = {}
    for var, value in re.findall(
        r'^EXPECT_([A-Z0-9_]+)="([^"]*)"', flake_lock_sh, re.M
    ):
        found[var.lower().replace("_", "-")] = value
    return found


def drift_job_is_blocking(ci_yml: str) -> tuple[bool, str]:
    """Is the `flake-lock-drift` job blocking?

    Scans the job's own block only — from `flake-lock-drift:` at column 0 to the
    next top-level key — so an `allow_failure: true` on some other job is not
    mistaken for this one's.
    """
    lines = ci_yml.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith("flake-lock-drift:"):
            start = i
            break
    if start is None:
        return False, "no `flake-lock-drift` job in .gitlab-ci.yml"
    for line in lines[start + 1:]:
        if line and not line[0].isspace() and not line.startswith("#"):
            break  # next top-level key: end of this job
        if re.match(r"\s+allow_failure:\s*true\b", line):
            return False, "`flake-lock-drift` is `allow_failure: true`"
    return True, "`flake-lock-drift` is blocking"


def main() -> int:
    root = repo_root()
    findings: list[str] = []
    notes: list[str] = []

    flake_nix_path = root / "flake.nix"
    lock_path = root / "flake.lock"
    lock_sh_path = root / "scripts" / "flake-lock.sh"
    ci_path = root / ".gitlab-ci.yml"

    inputs = declared_inputs(flake_nix_path.read_text())
    notes.append(f"flake.nix declares {len(inputs)} input(s): {', '.join(inputs)}")

    # ── 4. the drift gate must stay blocking ────────────────────────────────
    blocking, why = drift_job_is_blocking(ci_path.read_text())
    if blocking:
        notes.append(f"ok       {why}")
    else:
        findings.append(
            f"{why}. A drift gate that cannot fail is not a gate; the lock can "
            "move under two builders and the pipeline stays green."
        )

    # ── 1. the lock must exist and parse ────────────────────────────────────
    if not lock_path.is_file():
        findings.append(
            "flake.lock is MISSING. flake.nix and scripts/flake-lock.sh both "
            "describe it as committed; it is not, and no commit on main has "
            "ever carried it. Nothing pins nixpkgs, so `nixos-25.05` resolves "
            "to whatever that branch points at on the day and host of the build."
        )
        return report(findings, notes)

    try:
        lock = json.loads(lock_path.read_text())
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        findings.append(f"flake.lock does not parse as JSON: {exc}")
        return report(findings, notes)

    nodes = lock.get("nodes", {})
    root_key = lock.get("root", "root")
    root_inputs = nodes.get(root_key, {}).get("inputs", {})

    # ── 2. every declared input must be locked to a full rev + narHash ──────
    for name in inputs:
        node_key = root_inputs.get(name, name)
        if isinstance(node_key, list):  # follows-style indirection
            node_key = node_key[0] if node_key else name
        node = nodes.get(node_key)
        if not node:
            findings.append(
                f"input `{name}` is declared in flake.nix but has no node in "
                f"flake.lock — the lock pins nothing for it."
            )
            continue
        locked = node.get("locked", {})
        rev = str(locked.get("rev", ""))
        nar = str(locked.get("narHash", ""))
        if not FULL_REV.match(rev):
            findings.append(
                f"input `{name}` is not locked to a full 40-hex rev "
                f"(got {rev!r}). A branch or short rev is not a pin."
            )
        if not nar:
            findings.append(
                f"input `{name}` has no narHash in flake.lock — without it the "
                f"fetched content is unverified even at a fixed rev."
            )
        if FULL_REV.match(rev) and nar:
            notes.append(f"ok       {name} locked at {rev[:7]} ({nar[:16]}…)")

    # ── 3. recorded prose must agree with the lock ──────────────────────────
    expected = recorded_revs(lock_sh_path.read_text())
    for name in inputs:
        want = expected.get(name)
        if want is None:
            findings.append(
                f"scripts/flake-lock.sh records no EXPECT_ constant for input "
                f"`{name}`, so its drift check cannot see that input move."
            )
            continue
        if want == UNRECORDED:
            findings.append(
                f"scripts/flake-lock.sh has not recorded a rev for `{name}` "
                f"(still {UNRECORDED}). Run it on the Nix host and paste back "
                f"the rev it prints, so the drift check compares against a "
                f"measured value instead of a remembered one."
            )
            continue
        node_key = root_inputs.get(name, name)
        if isinstance(node_key, list):
            node_key = node_key[0] if node_key else name
        got = str(nodes.get(node_key, {}).get("locked", {}).get("rev", ""))
        if not got.startswith(want):
            findings.append(
                f"recorded rev for `{name}` is {want}, but flake.lock pins "
                f"{got[:12] or '<none>'}. The prose and the pin disagree; one "
                f"of them is wrong and a reader cannot tell which."
            )
        else:
            notes.append(f"ok       {name} recorded rev {want} matches the lock")

    return report(findings, notes)


def report(findings: list[str], notes: list[str]) -> int:
    for n in notes:
        print(f"  {n}")
    if not findings:
        print("check-repro-inputs: PASS")
        return 0

    print()
    print("=" * 74)
    print("REFUSED: the Nix inputs are not pinned, so no build here is repeatable.")
    print("=" * 74)
    for f in findings:
        print(f"\n  {f}")
    print(
        "\n  This job is RED BY DESIGN until a human runs scripts/flake-lock.sh on\n"
        "  the aarch64 Nix host, commits the flake.lock it writes, and records the\n"
        "  revs it prints. Agents do not run Nix and MUST NOT hand-write the lock:\n"
        "  a narHash is a content hash of fetched source, and a fabricated one is a\n"
        "  false pin — worse than no pin, because it reads as verified.\n"
        "\n  Do not resolve this by softening the check. Until the lock lands the\n"
        "  honest claim is the first rung of REPRO.md's ladder: NOT reproducible.\n"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
