#!/usr/bin/env python3
"""Build the Portuguese Bloch Inc deck with the English deck's shared layout."""
import ast
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "build_deck.py"

# Keep product names and technical abbreviations in their original form.
TRANSLATIONS = {
    "Bloch_Inc_Products_Services_EN_v4.pdf": "Bloch_Inc_Produtos_Servicos_PT_v4.pdf",
    "Bloch Inc — Products, Services and Evidence-Led Roadmap": "Bloch Inc — Produtos, Serviços e Roadmap Baseado em Evidências",
    "Current Bloch ecosystem and proposed global and LatAm roadmap": "Ecossistema Bloch atual e roadmap proposto para mercados globais e LatAm",
    "STRATEGIC ROADMAP  /  23 SEP 2026": "ROADMAP ESTRATÉGICO  /  23 SET 2026",
    "STRATEGIC VISION / PRODUCTS + SERVICES": "VISÃO ESTRATÉGICA / PRODUTOS + SERVIÇOS",
    "The next chapter of Bloch.": "O próximo capítulo da Bloch.",
    "What exists today. What Bloch Inc proposes next for Latin America and global markets. A roadmap built around evidence, security and utility.": "O que existe hoje e o que a Bloch Inc propõe para a América Latina e os mercados globais. Um roadmap baseado em evidências, segurança e utilidade.",
    "PRODUCT STAGES AND DELIVERY GATES / ENGLISH": "ESTÁGIOS DOS PRODUTOS E CRITÉRIOS / PORTUGUÊS",
    "01 / Current landscape": "01 / Cenário atual",
    "The ecosystem today": "O ecossistema hoje",
    "Five product lines, one operating L1 and access infrastructure — at different stages.": "Cinco linhas de produtos, uma L1 em operação e infraestrutura de acesso, em estágios distintos.",
    "L1 + Explorer": "L1 + Explorer",
    "Operating / qualify release": "Operando / qualificação",
    "Genesis-4 PoS, node, RPC, public explorer and historical receipts.": "Genesis-4 PoS, nó, RPC, explorer público e registros históricos.",
    "Wallet": "Wallet",
    "Public beta": "Beta público",
    "Native authorization, browser extension and a published JS exchange SDK.": "Autorização nativa, extensão e SDK JS publicado para corretoras.",
    "DEX": "DEX",
    "Development preview": "Prévia de desenvolvimento",
    "Interfaces and external EVM-chain pools; not production liquidity.": "Interfaces e pools em redes EVM externas; sem liquidez de produção.",
    "Aggregator": "Agregador",
    "Deployment unverified": "Implantação não verificada",
    "Route comparison in code; broad deployment has not been verified.": "Comparação de rotas no código; implantação ampla não verificada.",
    "L2 + Bridge": "L2 + Bridge",
    "Integration / qualification": "Integração / qualificação",
    "Local execution and references; public settlement and transfers pending.": "Execução local e referências; liquidação e transferências públicas pendentes.",
    "02 / What operates now": "02 / O que opera hoje",
    "A network with public evidence": "Uma rede com evidências públicas",
    "The foundation is usable; production service guarantees still require independent qualification.": "A base é utilizável; garantias de serviço em produção ainda exigem qualificação independente.",
    "Proof of stake produces blocks and exposes native transaction, balance and validator data.": "A prova de participação produz blocos e expõe transações nativas, saldos e dados de validadores.",
    "PUBLIC INTERFACE": "INTERFACE PÚBLICA",
    "Browse transactions, blocks, validators, finality and read-only historical receipts.": "Consulte transações, blocos, validadores, finalidade e registros históricos de leitura.",
    "DEVELOPER ACCESS": "ACESSO PARA DEV",
    "Published JavaScript transfer construction and transaction query API for integrators.": "Construção de transferências em JavaScript e API de consulta de transações publicadas para integradores.",
    "03 / Access layer": "03 / Camada de acesso",
    "Wallet and exchange integration": "Wallet e integração de corretoras",
    "Current client capabilities are available at different assurance levels.": "Os recursos atuais de cliente têm diferentes níveis de garantia.",
    "PUBLIC BETA": "BETA PÚBLICO",
    "On-device hybrid post-quantum signing for native Bloch. The wallet remains a public beta.": "Assinatura híbrida pós-quântica no dispositivo para Bloch nativa. A wallet segue em beta público.",
    "PUBLISHED SDK": "SDK PUBLICADO",
    "High-level signed transfer bytes, UTXO selection, fee and epoch handling; no exchange-side serializer.": "Transferência assinada de alto nível, seleção de UTXOs e tratamento de taxas e épocas; sem serializador na corretora.",
    "INTEGRATOR API": "API DE INTEGRAÇÃO",
    "TXID receipts": "Registros por TXID",
    "Canonical indexed inputs, outputs and sat amounts with height, slot, confirmations and finality.": "Entradas, saídas e valores em sat indexados, com altura, slot, confirmações e finalidade.",
    "04 / Existing product lines": "04 / Produtos existentes",
    "Trade and cross-network work": "Negociação e interoperabilidade",
    "Current code and interface previews do not imply live settlement.": "Código e prévias de interface ainda não significam liquidação ativa.",
    "PREVIEW": "PRÉVIA",
    "Market interfaces and external EVM-chain pools remain development software.": "Interfaces de mercado e pools em redes EVM externas seguem como software em desenvolvimento.",
    "UNVERIFIED": "NÃO VERIFICADO",
    "Route comparison exists in code; broad deployment and partner coverage remain unverified.": "Comparação de rotas existe no código; implantação ampla e cobertura de parceiros não foram verificadas.",
    "INTEGRATION": "INTEGRAÇÃO",
    "EVM execution components and bridge references exist; public asset transfers are not enabled.": "Há componentes de execução EVM e referências de bridge; transferências públicas de ativos não estão ativas.",
    "05 / Strategic thesis": "05 / Tese estratégica",
    "Turn trust into a product": "Transformar confiança em produto",
    "Build workflows that people and institutions can inspect, control and integrate.": "Criar fluxos que pessoas e instituições possam inspecionar, controlar e integrar.",
    "Verification": "Verificação",
    "Evidence for chain state, finality, data origin, software releases and service availability.": "Evidências do estado da rede, finalidade, origem dos dados, versões de software e disponibilidade.",
    "Control": "Controle",
    "Explicit authorization, approvals, limits, recovery and auditable operations.": "Autorização explícita, aprovações, limites, recuperação e operações auditáveis.",
    "Integration": "Integração",
    "Versioned APIs, SDKs, events, local testing and clear security boundaries.": "APIs versionadas, SDKs, eventos, testes locais e limites claros de segurança.",
    "06 / P0 proposed service": "06 / Serviço P0 proposto",
    "An evidence layer for exchanges, custodians, validators and risk teams.": "Uma camada de evidências para corretoras, custodiantes, validadores e equipes de risco.",
    "IMPLEMENTED MVP": "MVP IMPLEMENTADO",
    "Offline comparison": "Comparação offline",
    "The current CLI validates checkpoint bundles and compares independently supplied observations. It does not yet authenticate operators or prove finality.": "A CLI atual valida pacotes de checkpoints e compara observações independentes. Ainda não autentica operadores nem comprova finalidade.",
    "PROPOSED SERVICE": "SERVIÇO PROPOSTO",
    "Operator + state evidence": "Evidências de operador e estado",
    "Signed operator packages, authenticated trust roots, regular checkpoint publication and independently compared finality reports.": "Pacotes assinados de operadores, raízes de confiança autenticadas, checkpoints regulares e relatórios de finalidade comparados de forma independente.",
    "07 / P1 proposed service": "07 / Serviço P1 proposto",
    "A recurring service opportunity built on tools that reduce repeated operational work.": "Uma oportunidade de serviço recorrente baseada em ferramentas que reduzem trabalho operacional repetido.",
    "DATA": "DADOS",
    "Extend the live historical index into complete, provenance-rich transaction and account APIs.": "Expandir o índice histórico ativo para APIs completas de transações e contas, com origem verificável.",
    "INTEGRATION": "INTEGRAÇÃO",
    "Versioned clients, idempotent delivery, retries and exchange-ready examples.": "Clientes versionados, entrega idempotente, novas tentativas e exemplos prontos para corretoras.",
    "BUILD": "DESENVOLVIMENTO",
    "Local node, fixtures and transaction simulation before live submission.": "Nó local, dados de teste e simulação de transações antes do envio à rede.",
    "08 / P2 proposed services": "08 / Serviços P2 propostos",
    "Organizational control and payment tools, without claiming initial custody or rail access.": "Ferramentas de controle e pagamentos, sem alegar custódia inicial ou acesso a trilhos de pagamento.",
    "DESIGN ONLY": "EM CONCEPÇÃO",
    "Multi-step approvals, limits, allowlisted recipients, audit trail and on-device signing.": "Aprovações em etapas, limites, destinatários permitidos, trilha de auditoria e assinatura no dispositivo.",
    "Invoices, reconciliation, finality receipts and webhooks for native BLCH flows.": "Faturas, conciliação, comprovantes de finalidade e webhooks para fluxos nativos de BLCH.",
    "09 / Global market line": "09 / Mercado global",
    "Software for market participants; not an operating exchange or settlement system.": "Software para participantes do mercado; não é uma bolsa nem um sistema de liquidação em operação.",
    "START WITH SOFTWARE": "COMEÇAR PELO SOFTWARE",
    "Position reconciliation, reserve evidence and audit export with provenance.": "Conciliação de posições, evidências de reservas e exportação de auditoria com proveniência.",
    "PARTNER PILOT": "PILOTO COM PARCEIROS",
    "Issuance and corporate-action controls only with legal structure and authorized partners.": "Controles de emissão e eventos societários apenas com estrutura jurídica e parceiros autorizados.",
    "RESEARCH + PILOTS": "PESQUISA + PILOTOS",
    "Coordinated delivery or payment after verified finality, cash leg and risk controls.": "Entrega ou pagamento coordenados após verificação de finalidade, perna financeira e controles de risco.",
    "10 / Latin America": "10 / América Latina",
    "Regional interoperability begins with observation, reconciliation and qualified partners.": "A interoperabilidade regional começa com observação, conciliação e parceiros qualificados.",
    "BR-1 / PARTNERS": "BR-1 / PARCEIROS",
    "Connector design and BRL-flow reconciliation through authorized institutions; no live integration claimed.": "Desenho de conectores e conciliação de fluxos em BRL por instituições autorizadas; sem integração ativa declarada.",
    "BR-2 / PARTNERS": "BR-2 / PARCEIROS",
    "Receivables + assets": "Recebíveis + ativos",
    "Eligibility, lifecycle and audit trails with legal structure and regulated partners.": "Elegibilidade, ciclo de vida e trilhas de auditoria com estrutura jurídica e parceiros regulados.",
    "LA-3 / PILOT": "LA-3 / PILOTO",
    "Regional corridors": "Corredores regionais",
    "Controlled cross-border experiments with explicit FX, compliance and settlement.": "Experimentos transfronteiriços controlados, com câmbio, conformidade e liquidação explícitos.",
    "11 / Cross-network expansion": "11 / Expansão entre redes",
    "Routing with visible risk": "Roteamento com risco visível",
    "Execution follows evidence about cost, custody, backing and settlement.": "A execução depende de evidências sobre custo, custódia, lastro e liquidação.",
    "Compare": "Comparar",
    "Quotes, total costs, expected time and liquidity source are made visible.": "Cotações, custos totais, prazo esperado e origem da liquidez ficam visíveis.",
    "Explain": "Explicar",
    "Separate EVM ECDSA accounts from native post-quantum authorization and bridge operator risk.": "Separar contas EVM com ECDSA da autorização nativa pós-quântica e do risco do operador da bridge.",
    "Qualify": "Qualificar",
    "Public execution only after settlement proof, reserve reconciliation and independent review.": "Execução pública somente após prova de liquidação, conciliação de reservas e revisão independente.",
    "12 / Delivery gates": "12 / Critérios de avanço",
    "Four gates before scale": "Quatro etapas antes de escalar",
    "Move forward only when the prior capability has been demonstrated and documented.": "Avançar apenas depois que a capacidade anterior for demonstrada e documentada.",
    "Reliable base": "Base confiável",
    "Checkpoint publication, independent node sync, reproducible releases and finality comparison.": "Checkpoints publicados, sincronização independente, versões reproduzíveis e comparação de finalidade.",
    "Data + integration": "Dados + integração",
    "Complete index, versioned API, webhooks, SDK, monitoring and support.": "Índice completo, API versionada, webhooks, SDK, monitoramento e suporte.",
    "Value workflows": "Fluxos de valor",
    "Treasury policies, reconciliation, credit rules and controlled pilots.": "Políticas de tesouraria, conciliação, regras de crédito e pilotos controlados.",
    "Markets + networks": "Mercados + redes",
    "Qualified bridge, L2, global-market and LatAm pilots with audit and recovery.": "Bridge, L2 e pilotos globais e LatAm qualificados, com auditoria e recuperação.",
    "13 / Market sequencing": "13 / Sequência de mercados",
    "Two paths, one evidence model": "Dois caminhos, um modelo de evidências",
    "Regional and global programs share verifiable data but require different partners.": "Programas regionais e globais compartilham dados verificáveis, mas exigem parceiros distintos.",
    "GLOBAL": "GLOBAL",
    "Markets sequence": "Sequência global",
    "Proof Ledger software first; partner asset lifecycle next; DvP/PvP research and limited pilots only after verified finality and licensed participation.": "Primeiro, o software Proof Ledger; depois, ciclo de ativos com parceiros. Pesquisa DvP/PvP e pilotos limitados só após finalidade verificada e participação autorizada.",
    "LATAM": "LATAM",
    "Regional sequence": "Sequência regional",
    "Read-only rail observation first; authorized-partner reconciliation next; cross-border corridors only after legal, FX, compliance and settlement qualification.": "Primeiro, observação dos sistemas de pagamento; depois, conciliação com parceiros autorizados. Corredores transfronteiriços só após qualificação jurídica, cambial e de liquidação.",
    "14 / Research and limits": "14 / Pesquisa e limites",
    "Keep boundaries explicit": "Manter limites explícitos",
    "Research is separate from production products; no automatic transfer of L1 guarantees.": "Pesquisa é separada dos produtos em produção; garantias da L1 não se transferem automaticamente.",
    "RESEARCH": "PESQUISA",
    "Cryptographic agility": "Agilidade criptográfica",
    "Plan algorithm rotation and key migration with specification and audit.": "Planejar rotação de algoritmos e migração de chaves com especificação e auditoria.",
    "Verifiable privacy": "Privacidade verificável",
    "Advance Coherence circuits and proofs without claiming anonymity today.": "Avançar circuitos e provas Coherence sem alegar anonimato hoje.",
    "SECURITY": "SEGURANÇA",
    "Distinct domains": "Domínios distintos",
    "ECDSA applies to the L2/EVM domain. Native L1 uses hybrid ML-DSA-65 and Falcon-1024.": "ECDSA se aplica à L2/EVM. A L1 nativa usa a combinação ML-DSA-65 e Falcon-1024.",
    "15 / Execution model": "15 / Modelo de execução",
    "Sell measurable trust": "Oferecer confiança mensurável",
    "Infrastructure services can be useful before cross-network asset transfers are enabled.": "Serviços de infraestrutura podem gerar utilidade antes das transferências de ativos entre redes.",
    "CUSTOMERS": "CLIENTES",
    "Who benefits": "Quem se beneficia",
    "Exchanges, custodians, apps, node operators and treasury teams.": "Corretoras, custodiantes, aplicativos, operadores de nós e equipes de tesouraria.",
    "SERVICE MODEL": "MODELO DE SERVIÇO",
    "What to offer": "O que oferecer",
    "APIs, support, observability and deployment; routing fees only after qualification.": "APIs, suporte, observabilidade e implantação; taxas de roteamento apenas após qualificação.",
    "MEASURES": "MÉTRICAS",
    "What to prove": "O que comprovar",
    "Independent nodes, bootstrap time, event integrity, availability and reconciliation errors.": "Nós independentes, tempo de sincronização, integridade de eventos, disponibilidade e erros de conciliação.",
    "Source: Bloch_Inc_Products_Services_EN_v3.pdf and current product code.": "Fonte: Bloch_Inc_Products_Services_EN_v3.pdf e código atual dos produtos.",
    "New lines are proposals; Panama incorporation remains in progress.": "Novas linhas são propostas; incorporação no Panamá segue em andamento.",
    "THE NETWORK REMAINS OPEN; COMPANY SERVICES ARE OPTIONAL.": "A REDE SEGUE ABERTA; SERVIÇOS DA EMPRESA SÃO OPCIONAIS.",
}


class Translate(ast.NodeTransformer):
    def visit_Constant(self, node):
        if isinstance(node.value, str) and node.value in TRANSLATIONS:
            return ast.copy_location(ast.Constant(TRANSLATIONS[node.value]), node)
        return node


tree = ast.parse(SOURCE.read_text(), filename=str(SOURCE))
tree = Translate().visit(tree)
ast.fix_missing_locations(tree)
exec(compile(tree, str(SOURCE), "exec"), {"__file__": str(HERE / "build_deck_pt.py")})
